### ISSUE TITLE
Boiler plate for skulpt generator functions

### ISSUE THREAD

**Issue by s-cork** [skulpt/skulpt#1015]
I was looking at working on itertools #971 
I figured I might start with the generators namely `count` 
I wrote the function in python and looked at the compiled code. 
Then used the compiled code as a template but it was a bit of a struggle to know which parts were required or not... 🤷‍♂

Is there a boilerplate for writing a skulpt generator? Couldn't find one in the src lib...

**Comment by albertjan** [comment]
I'm not sure there are any generators in the code. But paste your code here and I can have a look at what's required and what's compiler generated and not needed.

**Comment by s-cork** [comment]
This is the python code I'm trying to compile [Count Compiled JS.txt](https://github.com/skulpt/skulpt/files/4152234/Count.Compiled.JS.txt)
```python
def count(start=0, step=1):
  n = start
  while True:
    yield n
    n += step
```

This is what I've come up with so far - taking the compiled code as a template:
```javascript
    var _count_gen = function ($gen) {
        let start, step;
        start = $gen.gi$locals.start;
        step = $gen.gi$locals.step;
        let n = start;
        while (true) {
            return [ /*resume*/ 6, /*ret*/ n];
            n = Sk.abstr.numberInplaceBinOp(n, step, 'Add');
        };
    };
    
    var _count = function (start, step) {
        Sk.builtin.pyCheckArgsLen("count", arguments.length, 0, 2);
        Sk.builtin.pyCheckType("start", "number", Sk.builtin.checkNumber(start));
        Sk.builtin.pyCheckType("step", "number", Sk.builtin.checkNumber(step));
        return new Sk.builtin.generator(_count_gen, Sk.$gbl, [start,step]);
    };
    _count.co_name = new Sk.builtins.str('count');
    _count.$defaults = [new Sk.builtin.int_(0), new Sk.builtin.int_(1)];
    _count.co_varnames = ['start', 'step'];
    _count_gen.co_name = new Sk.builtins.str('count');
    _count_gen.$defaults = [new Sk.builtin.int_(0), new Sk.builtin.int_(1)];
    _count_gen.co_varnames = ['start', 'step'];

    mod.count = new Sk.builtin.func(_count);
```

- I get a generator object 👍 
- the first call to next yields `start` 👍 
- subsequent calls to next also yield `start`  👎 

<br>

- I guess I can't get past the `return` statement 
- the compiled code got a bit complex for me to decipher
- I wasn't sure if I needed to use suspensions or not 😨 
- I also noted that I couldn't just use a javascript yield 😞 (it gets blocked by `BABEL_PARSER` so i guessed it wasn't supported by skulpt as valid syntax)

**Comment by albertjan** [comment]
Ah yes, I'll have to study this a bit too 😄 

> - I wasn't sure if I needed to use suspensions or not 

No I think we can do without. nothing can actually suspend except for maybe an overridden `__add__` 

> - I guess I can't get past the return statement

Yeah I think you might want to put the: 
`n = Sk.abstr.numberInplaceBinOp(n, step, 'Add');` in a try finally.

```
try {
    return [];
} finally {
    n = Sk.abstr.numberInplaceBinOp(n, step, 'Add');
}
```

> - I also noted that I couldn't just use a javascript yield

A javascript generator is also something completely different to a skulpt generator so I doubt it would have done you much good. 😄 It would be interesting to have a `Sk.ffi.generator(jsGenerator): skulptGenerator` function 😄. But that's something for the future.

**Comment by s-cork** [comment]
I think i've got it.

```javascript

    var _count_gen = function ($gen) {
        console.log(arguments)
        const n = $gen.gi$locals.n;
        const step = $gen.gi$locals.step;
        while (true) {
            try {
                return [ /*resume*/, /*ret*/ n];
            } finally {
                $gen.gi$locals.n  = Sk.abstr.numberInplaceBinOp(n, step, 'Add');
            }
        };
    };

    var _count = function (start, step) {
        Sk.builtin.pyCheckArgsLen("count", arguments.length, 0, 2);
        Sk.builtin.pyCheckType("start", "number", Sk.builtin.checkNumber(start));
        Sk.builtin.pyCheckType("step", "number", Sk.builtin.checkNumber(step));
        const n = start;
        return new Sk.builtin.generator(_count_gen, Sk.$gbl, [n, step]);
    };
    _count.co_name = new Sk.builtins.str('count');
    _count.$defaults = [new Sk.builtin.int_(0), new Sk.builtin.int_(1)];
    _count.co_varnames = ['start', 'step'];
    _count_gen.co_name = new Sk.builtins.str('count');
    _count_gen.co_varnames = ['n', 'step'];

    mod.count = new Sk.builtin.func(_count);


```
