### ISSUE TITLE
Outdated NPM package

### ISSUE THREAD

**Issue by gda-gp** [skulpt/skulpt#1022]
Noticed the NPM package is very outdated with the last publish 3 years ago.

https://www.npmjs.com/package/skulpt

Any plans for an updated package?

**Comment by albertjan** [comment]
@daluege are you the same that published this package? If so? Would you like to transfer ownership of this package so we can update it?

**Comment by gda-gp** [comment]
@albertjan could be worth going through the official channels of an abandoned package so you can keep it up to date:

https://www.npmjs.com/policies/disputes

```
    Get the author email with npm owner ls <pkgname>
    Email the author, CC support@npmjs.com
    After 4 weeks, if there's no resolution, we'll address it.
```

Being able to install with npm would simplify the dependency management for everyone.

**Comment by albertjan** [comment]
I'll try

**Comment by timmartin** [comment]
Is there any update on this? I'm getting security errors when I import the package due to old dependencies, it would be nice to sort this out.

**Comment by albertjan** [comment]
@timmartin @gda-gp I've emailed npm and @daluege so please bear with us a little longer.

**Comment by albertjan** [comment]
I've got access to the npm package :tada:

**Comment by albertjan** [comment]
How are you all using the package? Are you importing files from `src/` or are you importing built files from `/dist`?

**Comment by gda-gp** [comment]
I import the built files from /dist.

**Comment by albertjan** [comment]
@skulpt/committers @gda-gp @timmartin what shall we do here? publish 1.0.0 and then publish a new version of master? 

I'd like to publish 1.0.0 because that's also published everywhere else.

**Comment by timmartin** [comment]
I'm not a maintainer, but for my money given there's already a v1.0.0 tag that people may have been using, it would make sense to publish from that tag as v1.0.0 on NPM. I suppose it doesn't greatly matter since the only people using the NPM dist will be stuck on an old version anyway, so they can just as easily upgrade to 1.1.0 or whatever.

**Comment by albertjan** [comment]
That was my plan @timmartin 😄

**Comment by albertjan** [comment]
published 🎉 without dependencies this time 😄 we'll have to work on our deployment/release documentation and process

**Comment by vthommeret** [comment]
This could be user error, but I was previously (5 days ago) able to `npm install skulpt` and import skulpt but now I'm getting `Module not found: Can't resolve 'skulpt'` with `import skulpt from 'skulpt'`.

Based on this issue it seems like I was maybe getting an older version? It was pinned to:

`"skulpt": "^0.11.1",`

And now it's:

`"skulpt": "^1.0.0",`

I'm continuing to investigate / will probably build from source, but sharing in case it's a more widespread issue.

**Comment by albertjan** [comment]
@vthommeret I'll have a look

**Comment by albertjan** [comment]
Sorry @vthommeret the package wasn't previously maintained by us, there was apparently a `main.js` file added that did the importing but you can do this now. I'll make sure that future packages will include this. 

See below on how it works now:

```
require("skulpt/dist/skulpt.min.js");
require("skulpt/dist/skulpt-stdlib.js);

function builtinRead(file) {  
  if (Sk.builtinFiles === undefined || Sk.builtinFiles.files[file] === undefined) {
    throw "File not found: '" + file + "'";
  }
  
  return Sk.builtinFiles.files[file];
}

Sk.configure({
  read: builtinRead,
  output: console.log,
  __future__: Sk.python3,
});

Sk.importMainWithBody("<stdin>", false, "print('hello')");
```

**Comment by vthommeret** [comment]
Thanks for the quick reply! That got it working!

Also thanks for the minimal example to directly evaluate a line of Python. I was having some trouble finding a simple example from the example given here: http://skulpt.org/using.html

Are there any active efforts to improve documentation? Skulpt seems like an awesome project, but I can't seem to find e.g. API documentation for supported methods, guides for passing in data, retrieving data from Skulpt, etc... The docs seem to be more oriented to developers working on Skulpt itself vs. end users. I found this blog post pretty helpful — http://0xdabbad00.com/2013/01/29/things-ive-learned-using-skulpt-for-in-browser-python-code/ as well as extrapolating from a few different code examples.

I'm still evaluating whether Skulpt will work for my use case, but if it does I might be open to helping with documentation.

**Comment by albertjan** [comment]
We're are definitely aware of the lack of up to date documentation. And we've definitely neglected it, we've had several attempts with different levels of success. I think this might help you a bit: http://skulpt.org/docs/Sk.html

A good quick start guide is definitely something we miss. 😄

**Comment by albertjan** [comment]
@vthommeret Feel free to ask any questions, I usually have an example of something lying around. 😄

**Comment by vthommeret** [comment]
Thanks. It's actually related to importing numpy, so I'll ask in #1101.

**Comment by alexandruionascu** [comment]
Really helpful thread, I just managed easily to integrate it into React Native.

**Comment by gda-gp** [comment]
@albertjan I'd like to try out one of the new features in Skulpt for strings and I noticed that there is quite frequent development going on here.

Is there some sort way process to keep the npm version updated?

Perhaps Skulpt could release a version every month, e.g. version 1.1.0 this month and 1.2.0 next month and so on, until a major version (or patch release if a bug fix https://semver.org/).
