### ISSUE TITLE
npm run repl

### ISSUE THREAD

**Issue by s-cork** [skulpt/skulpt#1031]
When doing `npm run repl` how do I set it to `python3` mode?

**Comment by albertjan** [comment]
looking at the code there's no way to run it in py3 mode from the console. but if you edit `repl/repl.js` and add `__future__: Sk.python3` to the call to `Sk.configure` you'll have a py3 repl. We should have a command line arg for that really.

**Comment by s-cork** [comment]
thanks @albertjan I might see if I can add `npm run py2/py3 repl` ... or maybe just `npm run repl3`?

It would also be nice to have arrow keys for the repl too...

**Comment by albertjan** [comment]
lets mimic the other run commands 

It would be nice, there's probably a node library to do better terminal emulation somewhere.
