### ISSUE TITLE
How to get the compiled JS code after we transfer skulpt.py to npm?

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#1057]
It seems that `./skulpt.py run test.py` not work any more.
Thank you.

**Comment by rixner** [comment]
You need to first build skulpt:

Production build:
```npm run build```

Development build:
```npm run devbuild```

Then you can run individual files:
```npm start py3 foo.py```

Use "py2" instead of "py3" to run in Python 2 mode.

**Comment by alexwenbj** [comment]
@rixner Got it,Thank you.
