### ISSUE TITLE
One Test failing on master

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#1066]
Hi, so in preparation for syncing up master to my Fork of skulpt today I made a clean clone and ran `npm install` and `npm run dist`

```
test/unit3/test_counter.py

Fail: Expected [('l', 5), ('e', 4), ('o', 3), ('r', 2), ('h', 2), (' ', 2), ('!', 2), ('d', 1), ('w', 1), ('u', 1), ('n', 1), ('i', 1), ('v', 1), ('s', 1)] 
      to equal [('l', 5), ('e', 4), ('o', 3), ('h', 2), (' ', 2), ('r', 2), ('!', 2), ('w', 1), ('d', 1), ('u', 1), ('n', 1), ('i', 1), ('v', 1), ('s', 1)]
Tests failed in  CounterTests.test_most_common
Ran 5 tests, passed: 4 failed: 1
```

The counts are fine but the order is different.

I have npm 6.14.4 and node 13.12.0

I wonder if this is due to a difference in the node version I'm running versus what we have in our CI ??

**Comment by s-cork** [comment]
from what i've read it's due to different node versions. Just tagged you in a comment from @albertjan where he mentions this issue in a recent pull request.

**Comment by rixner** [comment]
@bnmnetp I'll try to pull that one change out into it's own pull request, so that it can quickly and easily be merged without baggage.  This is really just a bad test as it is currently written.  My change fixes the test to check the right things.

**Comment by rixner** [comment]
Done in #1069.  I probably should have done that a while ago.
