### ISSUE TITLE
Wrong string decoded with escape and unicode characters

### ISSUE THREAD

**Issue by paladin-t** [skulpt/skulpt#1072]
(Python3) code to reproduce:

```py
print("你好\t世界")
```

Got:

```
ä½ å¥½	ä¸ç
```

Expected:

```
你好	世界
```

Possible try:

In [`function parsestr`](https://github.com/skulpt/skulpt/blob/180bb5bdad56d6bdfd54280feb5f4ed253fa0568/src/ast.js#L2244) in `/arc/ast.js`:

```js
function parsestr (c, s) {
    var encodeUtf8 = function (s) {
        // Change `return unescape(encodeURIComponent(s));` to:
        return decodeURIComponent(encodeURIComponent(s)); // would fix this issue.
    };
    ...
}
```

What was the purpose of doing `unescape(encodeURIComponent(s))`?

**Comment by Dustyposa** [comment]
In latest version , had fix this problem.

**Comment by paladin-t** [comment]
I dont think it had.

**Comment by s-cork** [comment]
This is working in the current version of master branch
