### ISSUE TITLE
tp$name on instances and klasses are equivalent...?

### ISSUE THREAD

**Issue by s-cork** [skulpt/skulpt#1079]
```
class A:
  pass

>>> A().foo
'A' object has no attribute 'foo'
>>> A.foo
'A' object has no attribute 'foo'
```

But `A` is not an instance of `'A' object` it is an instance of `type` and should read `type object 'A'`

I've been working on a fix for this so will do a pr later.

**Comment by meredydd** [comment]
Yeah...line 485 of `type.js` looks Just Wrong to me.

```
Sk.builtin.type.makeIntoTypeObj = function (name, t) {
    Sk.asserts.assert(name !== undefined);
    Sk.asserts.assert(t !== undefined);
    t.ob$type = Sk.builtin.type;
    t.tp$name = name;
    (snip)
```
I think `t.tp$name` should be `"type"`.

**Comment by s-cork** [comment]
I've done some looking around and here's what i've found

this is based on both the pypy implementation:
https://foss.heptapod.net/pypy/pypy/blob/branch/default/pypy/module/__builtin__/interp_classobj.py
`W_ClassObject`s get a `.name` attibute but `W_instanceObject`s only get `.w_class` attribute
#### example code
```python
        if exc:
            raise oefmt(space.w_AttributeError,
                        "%s instance has no attribute '%s'",
                        self.w_class.name, name)


```

and the cpython implementation:
https://docs.python.org/3.0/c-api/typeobj.html#tp_name

https://github.com/python/cpython/blob/master/Objects/typeobject.c
#### Example code
```
type -> tp$name
```

#### Another similar example:
```c
        PyErr_Format(PyExc_TypeError,
                     "first argument must be a string, not %.80s",
                     Py_TYPE(pystr)->tp_name);
```

#### and another...
```c
    if (!PyDict_Check(value)) {
        PyErr_Format(PyExc_TypeError,
                     "attrib must be dict, not %.200s",
                     value->ob_type->tp_name);
        return -1;
    }
```

---

#### My question is then - what is the paradigm?

Should it be that in Cpython when we do 
```c
PyType(value)->tp_name
/* and similarly */
value->ob_type->tp_name
```
This maps to Skulpt as
```
value.tp$name
/* and similarly */
value.ob$type.prototype.tp$name
// or equivalently
```

I see that this is true of functions... So it would be good to be consistent here.

@meredydd - Am I on the right track here. 
I think the confusion comes from trying to directly map the `Cpython`/`PyPy` paradigm on to skulpt... 

It would be good to document this if it isn't already...

**Comment by s-cork** [comment]
If implemented I think the above would cause confusion:

```
class A:
  pass
a = A()
```
Would result in... 
```
/* value = A */
value->ob_type->tp_name  /* return 'type' */
value.ob$type.tp$name /* return 'type' */

/* value = a */
value->ob_type->tp_name  /* return 'A' */
value.ob$type.tp$name /* return 'type' */
```


A possible avenue:

Move away from using `prototype` as a shortcut for `ob_type` and instead just use `ob$type`

Justification 
-  Skulpt seems to be trying to do both when it suits (The example is in `Sk.abstr.typeName`)
- Mapping Cpython/pypy implementations onto skulpt would become more readable
- Thereby making implementing new features easier

---
Reading CPython

```
/* value = A */
value->ob_type->tp_name  /* return 'type' */
value.ob$type.tp$name /* return 'type' */

/* value = a */
value->ob_type->tp_name  /* return 'A' */
value.ob$type.tp$name /* return 'A' */
```
And similarly in Cpython
```
value->ob_type->tp_call
value.ob$type.tp$call
```

**Comment by meredydd** [comment]
I think you've got it right here, @s-cork, when you say:

> This maps to Skulpt as
> ```
> value.tp$name
> /* and also */
> value.ob$type.prototype.tp$name
> ```

My understanding is that Skulpt puts all the `tp$xxx` values on the prototype of the type, which makes them accessible directly on any instance. This is obviously helpful for things like `tp$getattr` and `tp$call`, where it helps us avoid indirection in hot paths; it's less obviously useful for `tp$name` or `tp$bases` but I think it's worth keeping all the `tp$xxx` flags in the same place.

(This is definitely _not_ what CPython or PyPy do, but they don't have prototypical inheritance so they don't get the option :) )

**Comment by s-cork** [comment]
yeah - got it. And have a working version with this implementation. 
So since `tp$` should be on the prototype does this mean that also `tp$mro` and `tp$bases` should follow suit?

I think the answer is yes 🤔 maybe...

Skulpt has a flag for klass `sk$klass` which can be used to replace `tp$mro` as a check for am I a klass?

**Comment by meredydd** [comment]
I'm inclined to say "yes", but I'd appreciate it if any other @skulpt/committers could weigh in here; this is not a part of the code I am 100% confident with.
