### ISSUE TITLE
turn off automatic type conversion?

### ISSUE THREAD

**Issue by lg-elit** [skulpt/skulpt#1089]
Hi,

is there a way to make code like this trigger an error/exception:

`print(50>"45");`

**Comment by bnmnetp** [comment]
You are correct, Python 3 semantics say that this should be a TypeError
```
>>> 50 > "45"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'int' and 'str'
```

Whereas in Python 2.x this was a valid statement.  It seems we are still following python2 semantics on this one.

**Comment by alexwenbj** [comment]
It is OK in the new version: It raised an TypeError in python3 mode, and return False in Python 2 mode.

**Comment by bnmnetp** [comment]
Thanks @alexwenbj -- I gotta get my fork updated !
