### ISSUE TITLE
int vs long in python 3

### ISSUE THREAD

**Issue by s-cork** [skulpt/skulpt#1093]
One issue with the current setup for `int` and `long` in py3 is that the only thing that changes is the `tp$name` of `long` becomes `int`. 

```python
>>> x = 2**53
>>> x
9007199254740992
>>> type(x)
<class 'int'>
>>> isinstance(x, int)
False
```

so yes `x` has the correct type name but it's `type` is not really `int` if you ask the right questions...

**Comment by alexwenbj** [comment]
In contrast to `isinstance(x, int) `returning False, `isinstance(x, long) `returning True.

**Comment by s-cork** [comment]
One issue with this set up is that you can never really inherit from int...

```python
class A(int):
  pass

>>> a = A(2**53)
>>> a
# TypeError: Cannot read property 'toString' of undefined 
# since the constructor for int diverts to long, a.v becomes undefined
>>> b = A(1)
>>> b
1
>>> a+b
NaN
# we're basically trying to add a.v (undefined) with b.v (1)
```
