### ISSUE TITLE
Get "pyName.$jsstr is not a function" when reproducing callin_from_js exemple

### ISSUE THREAD

**Issue by lalop** [skulpt/skulpt#1096]
I tried to reproduce the calling_from_js exemple 
https://github.com/skulpt/skulpt/blob/master/example/calling_from_js.html#L17 and call a function on the compiled script but I get `pyName.$jsstr is not a function` on `module.tp$getattr('root_cell')`

Here is my code 

```
const module = Skulpt.importMainWithBody("<stdin>", false, code);
const obj = module.tp$getattr('root_cell');
const runMethod = obj.tp$getattr('export');
Skulpt.misceval.callsim(runMethod);
```

**Comment by s-cork** [comment]
try doing `module.tp$getattr(new Sk.builtin.str('root_cell'))` 

all `tp$getattr` should take in an `Sk.builtin.str` as a parameter rather than a native js `String`

**Comment by lalop** [comment]
This work but the call to the method still doesn't work

**Comment by albertjan** [comment]
Hi @lalop sorry that documentation it quite old. I'll update it please have a look at this JSbin: https://jsbin.com/kidorux/edit?js,console

See the code below:

```js
function builtinRead(x) {
  if (Sk.builtinFiles === undefined || Sk.builtinFiles.files[x] === undefined) {
    throw "File not found: '" + x + "'";
  }
  
  return Sk.builtinFiles.files[x];
}

Sk.configure({
  read: builtinRead,
  output: console.log,
  __future__: Sk.python3
});


var module = Sk.importMainWithBody("<stdin>", false, [
  "class Test:",
  "     def run(self, b):",
  "         self.a = 10 + b",
  "         return self.a",
  "",
  "print('Hello World')",
  "a = Test()",
  ""
].join("\n"));


var a = Sk.globals.a;

var run = a.tp$getattr(Sk.ffi.remapToPy("run"));

var result = Sk.misceval.callsim(run, Sk.ffi.remapToPy(10));

console.log(Sk.ffi.remapToJs(result))
```

**Comment by lalop** [comment]
thank you @albertjan

**Comment by albertjan** [comment]
you're welcome 😄 sorry the docs were out of date
