### ISSUE TITLE
CLI Examples on skulpt.org are broken

### ISSUE THREAD

**Issue by tusharsadhwani** [skulpt/skulpt#1100]
Going to the website and simply running the `print "Hello world"` example throws an error.

Turtle graphics and DOM manipulation works, but something as basic as print shouldn't be broken

**Comment by bnmnetp** [comment]
print("hello") works just fine.

**Comment by tusharsadhwani** [comment]
Well if it's using python3 now, the examples need to be updated so that they work
![Screenshot_20200530-083201](https://user-images.githubusercontent.com/43412083/83318203-2597a500-a250-11ea-8dd2-a5f5c5d5b3b1.jpg)

**Comment by tusharsadhwani** [comment]
Is the skulpt.org website open sourced? I could issue a PR changing the codes to Python3 if needed

**Comment by ddejohn** [comment]
Came here to second this. The CLI does not work for recursive functions, it seems.

```python
def fac(n: int) -> int:
    if n < 2:
        return 1
    return n * fac(n-1)

print(fac(5))
```

**Comment by bnmnetp** [comment]
Yes, check out the gh-pages branch.

Thanks!
