### ISSUE TITLE
Add Math to Code to project gallery

### ISSUE THREAD

**Issue by vthommeret** [skulpt/skulpt#1104]
Hi,

I'm not sure if this is the best place to request this, but I'd like to add a project I created called Math to Code to the gallery: https://mathtocode.com

You can the description "Interactive NumPy tutorial for engineers". It uses Skulpt under the hood and is open source:

https://github.com/vthommeret/mathtocode

It also reached number 5 on Hacker News:

https://news.ycombinator.com/item?id=23513438

Thanks!
Vernon

**Comment by albertjan** [comment]
Hi @vthommeret you can add it yourself to the gh-pages branch of this repository.

**Comment by vthommeret** [comment]
Ahh, got it. Will add. Thanks!
