### ISSUE TITLE
Math.log fail to calculate long int

### ISSUE THREAD

**Issue by Shoodown** [skulpt/skulpt#1113]
Hello,

I'm trying to debug a problem in last Skulpt version (with Python 3 enabled) on Github.

Python code : 
```
import math
def Coef(n,k):
    return math.factorial(n)//(math.factorial(k)*math.factorial(n-k))

def lnP(n,k,p):
    return math.log(Coef(n,k))+k*math.log(p)+(n-k)*math.log(1-p)

n=1032
proba=0
for k in range(n//2+1):
    proba=proba+math.exp(lnP(n,k,0.47))
print(1-proba)
```

This program can't be run with Skulpt (Python 3), so I searched and this is what I've found for now : 

In the fourth iteration, inside lnP function, there is a problem because of Coef returning a negative number (which is of course incompatible with math.log).
But it's wrong because CPython 3.7 can calculate it without any problem and this number is correct with print function.

This is the first fourth iterations with print function (good result): 

- 1 => Coef(1032, 1) return 1032
- 2 => Coef(1032, 2) return 531996
- 3 => Coef(1032, 3) return 182651960
- 4 => Coef(1032, 4) return 46987216710

Now, with Math.log received as args (wrong result by Math.log) : 

- 1 => Coef(1032, 1) return 1032
- 2 => Coef(1032, 2) return 531996
- 3 => Coef(1032, 3) return 182651960
- 4 => Coef(1032, 4) return -257423546

The obj with big integer values for print and Math.log are exactly the same, so It's look like Math.log doesn't read it like print function.

Thanks :)

**Comment by s-cork** [comment]
Good find
it seems to be a specific problem is with the biginteger conversion to int

this is the case for
```
a = new Sk.builtin.lng("46987216710")
a.toInt$() // -257423546
```
It specifically is a failure with the biginteger libary/javascript which does 
```
15 << 28 // -257423546
```
in the function 
```javascript
//(public) return value as integer
Sk.builtin.biginteger.prototype.bnIntValue = function () {
    if (this.s < 0) {
        if (this.t == 1) {
            return this[0] - this.DV;
        } else if (this.t === 0) {
            return -1;
        }
    } else if (this.t == 1) {
        return this[0];
    } else if (this.t === 0) {
        return 0;
    }
    return ((this[1] & ((1 << (32 - this.DB)) - 1)) << this.DB) | this[0];
//  return                           15                                 << 28
};
```

I'm not sure what the best fix is for this...

**Comment by Shoodown** [comment]
I tried your fix, working great :)

I've some other programs that manipulate big int, will try them with your fix and let you know if there is any problems.
