### ISSUE TITLE
Skulpt hosted files give invalid certificate error on HTTPS on chrome android 

### ISSUE THREAD

**Issue by tusharsadhwani** [skulpt/skulpt#1118]
![image](https://user-images.githubusercontent.com/43412083/87218531-7ea33000-c308-11ea-8cef-8e302b3349b4.png)

I'm loading https://www.skulpt.org/js/skulpt.min.js in my demo website, and it works just fine on my windows pc, but doesn't work on Chrome for Android, says the certificate from github.com is invalid.

Any clues as to why that might be?

**Comment by tusharsadhwani** [comment]
Checking "Enforce HTTPS" in repository settings might be a possible fix? I'm not really sure about this

**Comment by albertjan** [comment]
please use javascript hosted on a cnd like jsdeliver.net, something like this: https://cdn.jsdelivr.net/combine/npm/skulpt@1.0.0/dist/skulpt.min.js,npm/skulpt@1.0.0/dist/skulpt-stdlib.min.js

or https://cdn.jsdelivr.net/npm/skulpt@1.0.0/dist/skulpt.min.js and https://cdn.jsdelivr.net/npm/skulpt@1.0.0/dist/skulpt-stdlib.min.js

**Comment by tusharsadhwani** [comment]
Okay
