### ISSUE TITLE
Decorator wraps in wrong order

### ISSUE THREAD

**Issue by LucasSaintrain** [skulpt/skulpt#1147]
When chaining decorators into a function, they are executed in the opposite order.

Considering this example from stackoverflow:
[https://stackoverflow.com/questions/27342149/decorator-execution-order](https://stackoverflow.com/questions/27342149/decorator-execution-order)

The output of the code should be: "&lt;b&gt;&lt;i&gt;hello world&lt;/i&gt;&lt;/b&gt;"
But instead I get: "&lt;i&gt;&lt;b&gt;hello world&lt;/b&gt;&lt;/i&gt;"

**Comment by LucasSaintrain** [comment]
Also using the editor at [skulpt.org](http://skulpt.org/), only the topmost decorator is executed

**Comment by s-cork** [comment]
so it does! 

executing multiple decorators was tackled in #977 and skulpt.org isn't up to date with the master branch. We should really update that - how do we do that @albertjan
