### ISSUE TITLE
Turtle artifacts

### ISSUE THREAD

**Issue by cgibin** [skulpt/skulpt#1165]
Hello guys, any ideas how to avoid such artifacts? Looks like some sort of antialiasing
![turtle-artifacts](https://user-images.githubusercontent.com/17925418/89984832-b6442580-dc82-11ea-900b-466f5b469a6f.png)

This is a tiny thing, but completely ruins my attempt of implementing image comparison of different programs drawing same image

**Comment by Dustyposa** [comment]
This caused by canvas, you can change the turtle source code by repeatedly `stroke` line can solve this problem when turtle draw a line.

**Comment by cgibin** [comment]
Thanks, @Dustyposa
Also could be fixed by using thickness of 2 or more or position turtle with +0.5 adjustment
