### ISSUE TITLE
This latest version make some skulpt numpy's methods not work

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#1179]
This latest version make the [skulpt numpy](https://github.com/ebertmi/skulpt_numpy) methods not work, for example: dot()/v_dot(), I check the code, maybe because of the Sk.builtin.type(), in old version,Sk.builtin.type() returns(for Sk.builtin.int_ type):
```
_ƒ (a,b){if(!(this instanceof Sk.builtin.int_))return new Sk.builtin.int_(a,b);if(this instanceof Sk.builtin.bool)return this;if(a instanceof
Sk.builtin.int_&&void 0===b)return this.v=a.v,this;if(b!==Sk…_
```
and in this version, it returns:
`ƒ [object Function]`

**Comment by s-cork** [comment]
it looks like it's the change to `tp$name` which the `numpy` implementation relied the typename of a class object being returned. 

```
  function Internal_DType_To_Num(dtype) {
      var name = Sk.abstr.typeName(dtype); // dtype is a type object and so it's tp$name is now 'type'
      var num = Internal_TypeTable[name];
      if (num == null) {
          return -1;
      }
      return num;
  }
```

suggested change: 
```
var name = dtype.prototype && dtype.prototype.tp$name;
```

maybe there needs to be an api for getting the typeName of a type object.

**Comment by alexwenbj** [comment]
@s-cork Yes, you are right, it is caused by typename implementation.
I guess other third-party libs may have same problem.
