### ISSUE TITLE
Implemented function Math.isqrt

### ISSUE THREAD

**Issue by BioMedTech** [skulpt/skulpt#1201]
Also ready to open a pr.

**Comment by mdickinson** [comment]
It's worth noting that `math.isqrt(x)` isn't quite as simple as `floor(sqrt(x))` - if it were, there wouldn't have been a whole lot of value in implementing a whole separate function for it. The `floor(sqrt(x))` version has floating-point rounding difficulties, even with "safe" values that are exactly representable in JavaScript. For example, in CPython:

```python
>>> from math import sqrt, isqrt, floor
>>> n = 4503599761588224  # (== 2**52 + 2**27)
>>> floor(sqrt(n))
67108865
>>> isqrt(n)
67108864
>>> n == float(n)  # n is exactly representable as an IEEE 754 binary64 float
True
```
