### ISSUE TITLE
annotations without an equals are not compiled

### ISSUE THREAD

**Issue by s-cork** [skulpt/skulpt#1210]
```python 3
>>> class A:
...    x: int
...
Cannot read property 'lineno' of null
>>> y: int
Cannot read property 'lineno' of null
```

It would also be great to support `__annotations__` since we pass them correctly (except for the above examples)

I think if the above works then `dataclasses` might even be possible... nearly.

**Comment by sschaub** [comment]
I would love to see this issue addressed. I contribute to Runestone books and would like to be able to cover these annotations in chapters on OOP in Python.
