### ISSUE TITLE
import other codeblock as module into current code?

### ISSUE THREAD

**Issue by unhott** [skulpt/skulpt#1224]
Hi, I'm wondering if it is possible to have 2 text elements on a page or in memory and import one like a module from the other. 

let's call one 'module_text' and one 'code_text'. 

module_text contains 
'def test(): 
    print('hello world')' 

and code_text says 
'import module_text
module_text.test()'

or

'from module_text import test
test()'

which ideally should print 'hello world'

**Comment by bofeng** [comment]
it is possible, first your have configure like this `Sk.configure({read: builtin_read});`, the in the `builtin_read` method, you can intercept the logic like below: (Pseudo code, not tested)
```
function builtin_read(x) {
    if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined) {
        // means this name "x" is not a builtin library in Python
       if (x === "module_text") {
           return "<your module_text code>";
       }
       else {
           throw "File not found: '" + x + "'";
       }
    }
    else {
        return Sk.builtinFiles["files"][x];
    }
}
```

**Comment by unhott** [comment]
This seems perfect. So I am trying to apply this modification to the builtinRead function from the simpleskulpt gist. I added a textarea with an id of module_text and used this builtinRead function, passed it into Sk.configure, but I think I'm not really sure what to do with the line return"<your module_text code>"; 

I tried to do return document.getElementById('module_text').value;, but I am getting 
ImportError: No module named module_text on line 2

I have probably missed something basic, as I am not super familiar with js, and especially not familiar with skulpt yet. 
[skulpt-module-test.html.txt](https://github.com/skulpt/skulpt/files/5527379/skulpt-module-test.html.txt)

Do I need to present the module_text content as a file instead of a string, maybe?

**Comment by bofeng** [comment]
When skulpt looks for the extra library, it will try the following names/paths (which is the passed `x` value in the function):
```
src/builtin/module_text.js
src/builtin/module_text/__init__.js
src/lib/module_text.js
src/lib/module_text/__init__.js
./module_text.js
./module_text/__init__.js
src/builtin/module_text.py
src/builtin/module_text/__init__.py
src/lib/module_text.py
src/lib/module_text/__init__.py
./module_text.py
```

So make sure your "x === " check at least match one of them, for example, in your file if you change the code to:
```
if (x === "./module_text.py") {
    return  document.getElementById('module_text').value;
}
```
It should work.

**Comment by unhott** [comment]
It worked, thank you!
