### ISSUE TITLE
Move CI to Github Workflows

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#1238]
@skulpt/committers 

Some of you may be aware that Travis-CI is shutting down travis-ci.org and migrating everyone to travis-CI.com.  The practical implications of this are that build minutes are now limited by credits for a free account even for open source project.  It seems that Bitcoin miners and others were abusing the system and have now forced limits onto everyone.

Unfortunately with the number of projects I have linked to my GitHub account I blew through those credits pretty quickly.

My solution was to move other projects to Github Workflows.

Any interest in doing the same here?

I can do it (unless someone else has a real burning desire to do so). I think most of our work is already in a script so it should not be too hard.  

Are there other improvements we would like to make to our continuous integration while we are at it?

**Comment by s-cork** [comment]
Looks like it's the perfect time to migrate from Travis CI to Github Workflows. I'm in favour!
What other improvements did you have in mind?

**Comment by acbart** [comment]
This would be nice. I've liked Github Actions a lot more than Travis.

**Comment by timmartin** [comment]
If it's of interest, I've set up my own forked version using GitHub actions to build and deploy to NPM as a scoped package, [here](https://github.com/timmartin/skulpt/tree/scoped_package/.github/workflows). This branch can't be merged back as-is, but if someone wants to copy my GitHub actions config file they're welcome to do so.

**Comment by bnmnetp** [comment]
Thanks @timmartin 

It seems that for your workflow to run we need to commit package-lock.json

I'm not sure why we do not do that?  I thought that it was recommended that projects DO commit the package-lock file to git.
