### ISSUE TITLE
'Screen' object has no attribute 'title' 

### ISSUE THREAD

**Issue by davidhadas** [skulpt/skulpt#1239]
seems like this code does not work - as if screen.title is not supported.

```
import turtle

s = turtle.Screen()
s.title("a")
```
AttributeError: 'Screen' object has no attribute 'title' on line 4

**Comment by bofeng** [comment]
In standard Python, it will change the turtle window's title. But since skulpt is running in browser, I am just wondering what do you expect to change when call `screen.title` ? like change the browser window's title which is inside `<title></title>` tag?

**Comment by davidhadas** [comment]
As a starting point compatiabilty requires that code that runs on python
will not fail on skulpt even if in this case it is to be ignored.
