### ISSUE TITLE
Infinite loop could makes browser crash,is there some way to stop it after memory overflow,by set the max memory or other stuff?

### ISSUE THREAD

**Issue by mindhacker0** [skulpt/skulpt#1245]

**Comment by s-cork** [comment]
There are a few options you can set in your call to `Sk.configure`.

Here's a demo that shows how you can overcome the infinite loop problem:
https://jsfiddle.net/sc549/bjLuq5s7/

I set the `killableWhile: true` 
This suspends the execution during a while loop
I then set a handler in the `Sk.importMainWithBody` to handle all suspensions. This handler checks to see if the `Stop` button has been clicked. If it has been clicked I throw an error.

You can also set other options like `execLimit` - i've added some comments to the `jsFiddle` to show some of the other options you can work with.
