### ISSUE TITLE
Can you add module pytesseract?

### ISSUE THREAD

**Issue by runboy1581** [skulpt/skulpt#1249]
Hi, I don't have enough ability to do Javascript coding for OCR function in web environment, so instead I have searched for a python-type program in web and I have found Skulpt.

However, I have also found that unlike normal python, Skulpt can only use modules that has been added by developers.

So I want to ask: can you add, or have you already added module pytesseract, which is a module to utilize Tesseract OCR?

I will not be surprise even if you cannot do that, since unlike other modules this module requires Tesseract being installed in the computer for normal python.

Thank you.

**Comment by s-cork** [comment]
You might want to check out anvil.works which might allow you the ability to integrate a web frontend with a python backend all written in python. 

anvil.works uses skulpt to facilitate python code on the front end.

Lesser known python modules are unlikely to be added to skulpt (unless they're part of the builtin modules). And if those lesser known modules have dependencies then even less unlikely.
