### ISSUE TITLE
type() not working in "using Skulpt"-example

### ISSUE THREAD

**Issue by darth83** [skulpt/skulpt#1259]
`print( type('string') )`

does work when testing on the skulpt.org front page but it doesn't work in the example given on https://skulpt.org/using.html under "Using Skulpt with HTML" (it prints nothing). 

Wish I could help but I have no idea on why this happens.

**Comment by Dustyposa** [comment]
![image](https://user-images.githubusercontent.com/27180793/104979092-6726cb80-5a3e-11eb-94ef-937d8636e17d.png)
It looks fine.

**Comment by darth83** [comment]
Not the trinket example, the one under "Using Skulpt with HTML". I have copy-pasted the HTML and put it here so you can test it: http://emilg.se/skulpt.html (this is an exact copy of the simple example).

**Comment by Dustyposa** [comment]
Used new skulpt version ?

**Comment by darth83** [comment]
Hm, what do you mean?

The example is using:
`<script src="http://www.skulpt.org/js/skulpt.min.js" type="text/javascript"></script> 
<script src="http://www.skulpt.org/js/skulpt-stdlib.js" type="text/javascript"></script> `

which are the same files that the front page is using (and where it works).

**Comment by s-cork** [comment]
ah this is the problem with having `<` as part of the innerHtml property
try doing
`mypre.textContent = mypre.textContent + text`
instead

**Comment by darth83** [comment]
Ah, of course. Yes that solves the problem, thanks! Perhaps change the example on the website?

**Comment by darth83** [comment]
Actually decided to use 

`text = text.replace("<","&lt;").replace(">","&gt;");`

instead, as I wanted HTML inside the output element.
