### ISSUE TITLE
How to stop running skulpt , is there any config value to set ?

### ISSUE THREAD

**Issue by tustzdm** [skulpt/skulpt#1260]
just stop normal script that spends within，we don't talk about infinite loop。
is there a function or value to stop running skulpt?

**Comment by s-cork** [comment]
This post may be useful 

https://github.com/skulpt/skulpt/issues/1245

**Comment by s-cork** [comment]
closing as this topic needs more info. Do reopen this and elaborate more on what you're trying to do. Hopefully the example in #1245 will help.
