### ISSUE TITLE
Math operations not correct

### ISSUE THREAD

**Issue by Foscat** [skulpt/skulpt#1272]
The math operations work only to a point, then seem to break down in questionable ways. 

I was working doing math operations to find the size of objects and can calculate the surface area of a sphere but when I tried to get the volume it is way off. I triple checked that I wrote it correctly and ran it in a python IDE and got the correct answer. So it is something with how skulpt is running it.

```py
import math

def surfaceOfSphere(radius):
    return 4*math.pi*radius**2

print("Surface area of sphere",surfaceOfSphere(5))
# This works as expected returning 
def volOfSphere(radius):
    return (4/3)*math.pi*radius**3
    
print("Volume of sphere",volOfSphere(5))
# This should output 523.5987755982987 but actually outputs 392.699081699
```
I did this with just 3.14 rather than using math import to ensure the least amount of potential problems. The result was equally off just less decimal trailing.

**Comment by bnmnetp** [comment]
I've run this on skulpt.org and on my own Fork, and I get the correct answers.  Where are you running this?  What version of skulpt are you using?

**Comment by Foscat** [comment]
I am running this in an site built our company has built to learn coding on. The npm and cdn versions did not work so a local copy of the library is used, the stated version of it in the bower.json is 0.11.0

**Comment by Dustyposa** [comment]
@Foscat 
You can use 
```
npm run dist
``` 
to get latest js. I tried it, fine.

**Comment by Foscat** [comment]
This issue is really with https://github.com/skulpt/skulpt-dist so I'll close this issue on this repo. I cloned the most recent version of it today and it is still a issue.
