### ISSUE TITLE
Skulpt overrides global JavaScript Set object

### ISSUE THREAD

**Issue by camilstaps** [skulpt/skulpt#1281]
In skulpt.js `function Set` is defined. This overrides the global [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) object in JavaScript.

I believe the definition comes from https://github.com/skulpt/skulpt/blob/6c99c2196851bb29f0e503afccb01804f089cb60/src/pgen/ast/Python.asdl#L74 and is used in the parser to parse Python `{}` expressions (`set` instances). Would it be possible to simply rename the constructor in the DSL to avoid the naming conflict?

**Comment by s-cork** [comment]
I don't think that's the problem since it ends up in the namespace `Sk.astnodes.Set` If you take a look at skulpt.org and look at Set in the console you get the native javascript Set object.

**Comment by camilstaps** [comment]
@s-cork is it possible that the version on npm is more or less recent than what is used on the website? That version does not define `Sk.astnodes` at all.

**Comment by s-cork** [comment]
Perhaps - it looks like the npm version is at `1.0.0`. The github branch is at `1.3.0`.
