### ISSUE TITLE
Silent failure binding static callback - python 2 vs 3 issue?

### ISSUE THREAD

**Issue by BBI-YggyKing** [skulpt/skulpt#1282]
In python 3 the following code compiles and runs fine, and prints "static goodbye". In python 2 and Skulpt it compiles but throws an exception when run:
`TypeError: unbound method myhelper() must be called with StaticHelper instance as first argument (got str instance instead)`

It seems like the `help` member, when set to a function, is treated like an instance method even though it is declared and initialized like an instance variable. I don't know enough about the internals of python to speculate why this is so.

```
class StaticHelper:
  help = None

  @staticmethod
  def setHelper(h):
    StaticHelper.help = h

  @staticmethod
  def getHelp(obj):
    if StaticHelper.help:
      StaticHelper.help(obj)

def myhelper(obj):
  print(obj)

StaticHelper.getHelp("static hello")
StaticHelper.setHelper(myhelper)
StaticHelper.getHelp("static goodbye")
```

By contrast, the following code works as I expected in python 2, python 3, and Skulpt, and prints "dynamic goodbye":
```
class DynamicHelper:
  help = None

  def setHelper(self, h):
    self.help = h

  def getHelp(self, obj):
    if self.help:
      self.help(obj)

def myhelper(obj):
  print(obj)

dh = DynamicHelper()
dh.getHelp("dynamic hello")
dh.setHelper(myhelper)
dh.getHelp("dynamic goodbye")
```

I can get StaticHelper to work as intended in python 2 and Skulpt with this kludge, but I'm not clear why it's necessary:
```
class StaticHelper:
  help = None

  @staticmethod
  def setHelper(h):
    StaticHelper.help = [ h ]

  @staticmethod
  def getHelp(obj):
    if StaticHelper.help:
      StaticHelper.help[0](obj)

def myhelper(obj):
  print(obj)

StaticHelper.getHelp("static hello")
StaticHelper.setHelper(myhelper)
StaticHelper.getHelp("static goodbye")
```

The workaround is acceptable for my purposes, but I thought I would contribute the issue in case it's enlightening in any way.

**Comment by s-cork** [comment]
This is fixed in skulpt 1.3.0

**Comment by BBI-YggyKing** [comment]
Nice, thanks @s-cork! I guess this is not-quite-a-bug in python 2, more just a characteristic of the implementation?

**Comment by s-cork** [comment]
Correct - it's a python 2ism. In python 3 unbound methods were removed. Skulpt was previously aligned with python 2 and is continually aiming to be aligned with python 3 (without breaking python 2 in the process).
