### ISSUE TITLE
Skulpt can't be embedded into secure web pages

### ISSUE THREAD

**Issue by iswCS110cCCSF** [skulpt/skulpt#1287]
I am trying to create a test page using github-pages but can't embed Skulpt as I get following errors,
Mixed Content: The page at 'https://iswcs110cccsf.github.io/coursera-test2/site/python.html' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by bnmnetp** [comment]
skulpt does not include jquery.  If you look more closely at the error message you will see that your page is `https` but you are trying to include jquery from an `http` address that is the mismatch the browser is complaining about.

**Comment by iswCS110cCCSF** [comment]
Below is the entire error I get,
Mixed Content: The page at 'https://iswcs110cccsf.github.io/coursera-test2/site/python.html' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
python.html:1 Mixed Content: The page at 'https://iswcs110cccsf.github.io/coursera-test2/site/python.html' was loaded over HTTPS, but requested an insecure script 'http://www.skulpt.org/js/skulpt.js'. This request has been blocked; the content must be served over HTTPS.
python.html:1 Mixed Content: The page at 'https://iswcs110cccsf.github.io/coursera-test2/site/python.html' was loaded over HTTPS, but requested an insecure script 'http://www.skulpt.org/js/skulpt-stdlib.js'. This request has been blocked; the content must be served over HTTPS.
I was simply trying your code linked here, http://skulpt.org/using.html#embed  to check whether I can embed Skulpt. 
Anyway my final questions is how do I embed Skulpt in this particular case.

**Comment by bnmnetp** [comment]
Just as the error message is telling you you need to use `https://skulpt.org/...` instead of `http`. That example is a bit outdated since it came before https was used everywhere, but you can adapt.

Even better would be for you to have your own copy on your server and just use  the first example.

**Comment by iswCS110cCCSF** [comment]
Thanks so much. I will give both a try.
