### ISSUE TITLE
Calling an async JS function from Python

### ISSUE THREAD

**Issue by Matthieu-BRANTHOME** [skulpt/skulpt#1290]
Hi, I'm trying to call an async JS function from my Python code run by Skulpt.

In my JS script:

```javascript
function myPromiseFunction() {
  return new Promise((resolve, reject) => {
    // Do things
    setTimeout( () => {
      // Do things      
      resolve("Successfully done");
    }, 1000);
  })
}
Sk.builtins.myPythonFunction = async function(){await myPromiseFunction();}        
```
I'm running my Python code in Skulpt using:
```javascript
Sk.configure({
  output: outf,
  killableWhile: true,
  killableFor: true,
  __future__: Sk.python3
});
        
stopExecution = false;
var code = codeEditor.getValue();
Sk.misceval.asyncToPromise(() =>
  Sk.importMainWithBody("<stdin>", false, code, true), {
  "*": () => {
    if (stopExecution) throw "Execution interrupted"
  }
},
).catch(err => {
  toErrorAlert(err.toString());
}).finally(() => {
 // Do things
})
```
And my Python Code is: 
``` python
myPythonFunction()
# Do things
```
Actualy, I want my Python code wait myPromiseFunction end before executing the next instructions, but it doesn't work.
I want to performe something like 'await myPythonFunction()' in Python code. Is that possible?

Thanks in advance for your help,

Matthieu

**Comment by s-cork** [comment]
It's not the best idea to expose a raw javascript function to your end users. I'd recommend turning it into a python func.
Also worth returning `None` rather than `undefined`.

```javascript
function myPromiseFunction() {
  return new Promise((resolve, reject) => {
    // Do things
    setTimeout( () => {
      // Do things      
      resolve("Successfully done");
    }, 1000);
  })
}

Sk.builtins.myPythonFunction = new Sk.builtin.func(function () {
    return new Sk.misceval.promiseToSuspension(myPromiseFunction().then(() => Sk.builtin.none.none$));
});


```

Promises in javascript should become Suspensions in skulpt.
If you check out the code in `time.js` for `sleep`, it basically does exactly the same thing

**Comment by Matthieu-BRANTHOME** [comment]
It perfectly works! Thank you very much for this quick answer!

However, I have an extra question:

Some of my promise JS functions return a boolean or an integer value, like:

``` javascript
function myPromiseFunction() {
  return new Promise((resolve, reject) => {
    // Do things
    a = 2; // or a = true;
    setTimeout( () => {
      // Do things      
      resolve(a);
    }, 1000);
  })
}
```
How can I change:
``` javascript
Sk.builtins.myPythonFunction = new Sk.builtin.func(function () {
    return new Sk.misceval.promiseToSuspension(myPromiseFunction().then(() => Sk.builtin.none.none$));
});
```
to get the return value in my Python code ?

Thanks in advance,

Matthieu

**Comment by s-cork** [comment]
If it's javascript numbers and javascript booleans then

```javascript
Sk.builtins.myPythonFunction = new Sk.builtin.func(function () {
    return new Sk.misceval.promiseToSuspension(myPromiseFunction().then((r) => Sk.ffi.remapToPy(r)));
});
```

`Sk.ffi.remapToPy` will work on simple javascript objects like null, undefined, number, string, array, simple objects to their python counterparts

**Comment by Matthieu-BRANTHOME** [comment]
It works!

Thanks a lot for your precious and reactive help!

Matthieu

**Comment by DegrangeM** [comment]
> It's not the best idea to expose a raw javascript function to your end users.

Could you elaborate why ? Thanks.

**Comment by s-cork** [comment]
The function doesn't behave like a python function. If your users decide to use introspection and start printing the function or exploring its attributes they might get some surprises.
