### ISSUE TITLE
Typo in http://skulpt.org/using.html

### ISSUE THREAD

**Issue by DegrangeM** [skulpt/skulpt#1294]
```html
<script src="https://gist.github.com/20bd9105f11f2a164fc0.js.js"> </script>  
```

need to be replaced by

```html
<script src="https://gist.github.com/20bd9105f11f2a164fc0.js"> </script>  
```

**Comment by timmartin** [comment]
I'd be happy to fix this, and to make more substantial contributions to the docs, but I haven't been able to figure out how the main web site is built. There's a `gh-pages` branch that appears to be an attempt to redo the site in GitHub pages, but as far as I can tell that attempt didn't get completed. Is there any way for people to submit patches to the documentation?

**Comment by bnmnetp** [comment]
Skulpt.org **is** using the `gh-pages` branch.  So feel free to make changes and submit PRs against that branch.  

There is also work in progress on using `jsdoc` to document the code.  My memory is a bit fuzzy about how the generated docs in progMan on the main branch end up in the gh-pages branch.... I think that may require a bit of git fun and games.

**Comment by timmartin** [comment]
Thanks for the clarification on the `gh-pages` situation. I must have been looking at an outdated pull or something.
