### ISSUE TITLE
Use input field when using input()

### ISSUE THREAD

**Issue by adithraghavs** [skulpt/skulpt#1304]
I've seen another issue regarding the same problem, but I am a total newbie to skulpt. I really need the whole code of the webpage including the code, sk.configure, and the textarea. can anyone please help?

**Comment by Dustyposa** [comment]
How  about this [one](https://github.com/skulpt/skulpt/blob/master/example/turtle.html)

**Comment by s-cork** [comment]
closing - thanks @Dustyposa - @adithraghavs  please reopen if that wasn't enough.
