### ISSUE TITLE
Could you add Pandas, NumPy, Matplotlib and Scikit-learn to Skulpt?

### ISSUE THREAD

**Issue by adithraghavs** [skulpt/skulpt#1305]
Could you add Pandas, Numpy, Matplotlib and Scikit-learn to Skulpt?

**Comment by s-cork** [comment]
This isn't something we'll be adding to the core anytime soon. 

There are skulpt implementations of numpy out there. If you search on GitHub you should find them. Though it's not clear if they are maintained. 

One focus of skulpt is to implement more of the standard library and builtins, and Numpy etc are not part of the standard lib.
