### ISSUE TITLE
Compiling code

### ISSUE THREAD

**Issue by PythonLinks** [skulpt/skulpt#1316]
In python you can compile some code.  If it fails it generates a nice error message.  Makes for a simple syntax checker.  So I tried the same thing in Skulpt.  Sk.compile ("fred", "value =", "single", false).code
 
 Sadly it did not return an error, it returned some string.  

I wonder if there is any way to generate an error message when compiling some python?    After two hours reading the code, I think not.

**Comment by s-cork** [comment]
That's valid compiled code. The second argument is the name of the file and `fred` is valid python.

If you try to compile `Sk.compile("value =", "?", "eval", false)` you'll get a syntax error.
If you call `.toString()` on the error it will give you a formatted error message.

Note that the compiler only supports eval mode.

**Comment by s-cork** [comment]
closing this issue - reopen if needs further clarification
