### ISSUE TITLE
How to convert any python object back into plain javascript object

### ISSUE THREAD

**Issue by chrisjd20** [skulpt/skulpt#1319]
How would I convert any python object back into a normal javascript object. For example:

``` javascript
var test = new Sk.builtin.dict()
Sk.builtin.dict.prototype.set$item.call(test, new Sk.builtin.str("y"),new Sk.builtin.int_(1));
Sk.builtin.dict.prototype.set$item.call(test, new Sk.builtin.str("x"),new Sk.builtin.bool(true));
```

This produces a python object that looks like this (to python):

``` python
{'x': True, 'y': 1}
```

I can't just pass this to a normal javascript function though cause the object looks like this to javascript:

``` json
{"size":2,"entries":{"x":[{"$mangled":"x","$savedKeyHash":"x","v":"x"},{"v":1}],"y":[{"$mangled":"y","$savedKeyHash":"y","v":"y"},{"v":1}]},"buckets":{},"in$repr":false,"$version":2}
```

How do I flatten/convert it back so that javascript sees it as:
``` json
{"x": true, "y": 1}
```

Also, heres an additional question. How would I more easily convert a json object `{"x": true, "y": 1}` to a python object without having to manually do what I did in my first code example (see above).

Thanks!

**Comment by s-cork** [comment]
You'll want the `ffi` tools. 

`Sk.ffi.remapToJs` and `Sk.ffi.remapToPy`.

**Comment by chrisjd20** [comment]
Ohhh perrrfect. I figured there was already a way to do that. I didnt want to have to reinvent the wheel if I didnt have to. Thanks a bunch!
