### ISSUE TITLE
Using super results in recursion error

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#1345]
The following code crashes out on the current HEAD of master.

```python
class Point:

    def __init__(self, initX, initY):
        self.x = initX
        self.y = initY

    def distanceFromOrigin(self):
        return ((self.x ** 2) + (self.y ** 2)) ** 0.5

    def __str__(self):
        return "x=" + str(self.x) + ", y=" + str(self.y)

class LabeledPoint(Point):

    def __init__(self, initX, initY, label):
        super().__init__(initX, initY)
        self.label = label

    def __str__(self):
        return super().__str__() + " (" + self.label + ")"

p = LabeledPoint(7,6,"Here")
print(p)
print(p.distanceFromOrigin())
```

The error is: `UNCAUGHT EXCEPTION: RecursionError: Maximum call stack size exceeded on line 20`

This does work on skulpt.org so it must be a fairly recent regression.

Any ideas?  I would love to get this fixed before fall classes start.

**Comment by bnmnetp** [comment]
Just playing around a bit more and it looks even more broken:

```python
class Point:

    def __init__(self, initX, initY):
        self.x = initX
        self.y = initY

    def distanceFromOrigin(self):
        return ((self.x ** 2) + (self.y ** 2)) ** 0.5

    def __str__(self):
        return "x=" + str(self.x) + ", y=" + str(self.y)

class LabeledPoint(Point):

    def __init__(self, initX, initY, label):
        super().__init__(initX, initY)
        self.label = label

#    def __str__(self):                                                                                                    
#        debugger                                                                                                          
#        return super().__str__() + " (" + self.label + ")"                                                                

p = LabeledPoint(7,6,"Here")
print(p.x)
#print(p.distanceFromOrigin()) 
```

Running this results in `UNCAUGHT EXCEPTION: AttributeError: 'LabeledPoint' object has no attribute 'x' on line 11`

This seems really weird as we must have some unit tests that test basic inheritance!

**Comment by alexwenbj** [comment]
> Just playing around a bit more and it looks even more broken:
> 
> ```python
> class Point:
> 
>     def __init__(self, initX, initY):
>         self.x = initX
>         self.y = initY
> 
>     def distanceFromOrigin(self):
>         return ((self.x ** 2) + (self.y ** 2)) ** 0.5
> 
>     def __str__(self):
>         return "x=" + str(self.x) + ", y=" + str(self.y)
> 
> class LabeledPoint(Point):
> 
>     def __init__(self, initX, initY, label):
>         super().__init__(initX, initY)
>         self.label = label
> 
> #    def __str__(self):                                                                                                    
> #        debugger                                                                                                          
> #        return super().__str__() + " (" + self.label + ")"                                                                
> 
> p = LabeledPoint(7,6,"Here")
> print(p.x)
> #print(p.distanceFromOrigin()) 
> ```
> 
> Running this results in `UNCAUGHT EXCEPTION: AttributeError: 'LabeledPoint' object has no attribute 'x' on line 11`
> 
> This seems really weird as we must have some unit tests that test basic inheritance!

This problem may be the same issue as https://github.com/skulpt/skulpt/pull/1306#issuecomment-889195723 ,the inheritance mechanism broken for some reasons.
