### ISSUE TITLE
print("hello", end=" ") not working on previous version of skulpt

### ISSUE THREAD

**Issue by rahulrawat17** [skulpt/skulpt#1364]
help me implement this feature on old skulpt version.

problem:
print("hello", end=" ")
print("world")
both line output should be on same line "hello world" but it giving in separate line, how to implement this feature in old version of skulpt.
this issue is not there in this/latest version of skulpt.
please help.

**Comment by s-cork** [comment]
We won't be fixing previous versions of skulpt I'm afraid.

The best option is probably to use the latest version.
If that's not an option you could look through https://github.com/skulpt/skulpt/blame/master/src/print.js to see if you can find the fix in the blame somewhere. Though I'm not aware it was ever broken.
