### ISSUE TITLE
[feature] Support for arbitrary number of arguments for builtin functions

### ISSUE THREAD

**Issue by quentincaffeino** [skulpt/skulpt#1366]
The question is how it could be implemented and if it is even possible?

I know very little of this library internals but from a quick look it seems that it would be enough to remove hardcoded arguments and Sk.builtin.pyCheckArgsLen from lib js files.

Reason I'm asking is that I wan't to add some math functions from latest versions and they are documented with arbitrary amount of arguments (ex.: lcm).

**Comment by s-cork** [comment]
For a builtin function - we're looking at the `Sk.builtin.sk_method` api.
To define how the args work in a builtin function the `$flags` will determine the behaviour.

See the description in `sk_method.js`

The typescript definition for a builtin function might look like this

```typescript
type Flag = "NoArgs" | "OneArg" | "FastCall" | "NoKwargs" | "MinArgs" | "MaxArgs" | "NamedArgs" | "Defaults";
interface MethodDef {
    $meth(...args): pyObject;
    $flags: { [flag: Flag]: boolean }
    $doc?: string | null
    $textsig?: string
}

```

For arbitrary number of args - i.e. `*args`. Use `$flags: { MinArgs: 0 }`. `MaxArgs` will default to `Infinity` and the function will check there are no keyword arguments before passing the `...args` to the function.

See:
https://github.com/skulpt/skulpt/blob/master/src/sk_method.js#L85-L89
