### ISSUE TITLE
Double starred unpacking doesn't work

### ISSUE THREAD

**Issue by Inspired1601** [skulpt/skulpt#1370]
```python
d1 = {
    'a': 1,
    'b': 2
}

d2 = {
    'c': 3,
    'd': 4
}

print({**d1, **d2})
```

Expected behaviour:
`{'a': 1, 'b': 2, 'c': 3, 'd': 4}`

Real behaviour:
`<TypeError: Cannot read properties of null (reading 'lineno')>`

**Comment by s-cork** [comment]
This works on the master branch. Fixed in #1225
