### ISSUE TITLE
The `__del__()` method is not called when the object is destroyed

### ISSUE THREAD

**Issue by Inspired1601** [skulpt/skulpt#1375]
```python
class Demo:
    def __init__(self):
        print('Instance created')

    def __del__(self):
        print('Instance will be deleted soon')


demo = Demo()
del demo
```

**Expected behaviour:**
Instance created
Instance will be deleted soon

**Real behaviour:**
Instance created

**Comment by Mathbone** [comment]
Per the Python documentation for [`__del__`](https://docs.python.org/3/reference/datamodel.html#object.__del__), the `__del__` function is not guaranteed to be called.

**Comment by Inspired1601** [comment]
> Per the Python documentation for [`__del__`](https://docs.python.org/3/reference/datamodel.html#object.__del__), the `__del__` function is not guaranteed to be called.

It is not guaranteed that __del__() methods are called for objects **that still exist when the interpreter exits.**

In the above example, `del` is called explicitly.

**Comment by s-cork** [comment]
It may be explicitly called but there's no way skulpt knows that you didn't assign it to another variable before deleting it. 
At which point there would be another reference to that object and `__del__` wouldn't be called. 

Skulpt doesn't count references to objects or handle garbage collection - it relies on the JavaScript to do the garbage collection.
