### ISSUE TITLE
npm run dist erro

### ISSUE THREAD

**Issue by AndersonHJB** [skulpt/skulpt#1396]
test/unit3/test_strptime.py

Ran 6 tests, passed: 6 failed: 0

Test threw exception in test_timezone (time data '' does not match format '%Z')
Ran 24 tests, passed: 23 failed: 1

Ran 1 tests, passed: 1 failed: 0

Test threw exception in test_day_of_week_calculation (time data '2021 11 04 14 57 308 ' does not match format '%Y %m %d %H %S %j %Z')
Test threw exception in test_gregorian_calculation (time data '2021 14 51 57 4 308 ' does not match format '%Y %H %M %S %w %j %Z')
Test threw exception in test_julian_calculation (time data '2021 11 04 14 51 57 4 ' does not match format '%Y %m %d %H %M %S %w %Z')
Ran 5 tests, passed: 2 failed: 3

Summary
Passed: 2358 Failed: 4
Total run time for all unit tests: 59.892s

**Comment by s-cork** [comment]
What happens when you do the following in skulpt?

```python
import time
print(time.timezone)
t = time.struct_time([1999, 3, 17, 22, 44, 55, 2, 76, 0]);
print(time.strftime("%c", t))
```

And in javascript
```js
new Date().toString()

```

I have a feeling this bug is from [`strftime.js`](https://github.com/samsonjs/strftime)
Which is where we derive the "%Z" information from
