### ISSUE TITLE
Exclude certain library modules during Skulpt compilation

### ISSUE THREAD

**Issue by SubwayMan** [skulpt/skulpt#1402]
Hi All,

I've been trying without success to remove certain modules before skulpt compilation. I wish to remove the ability to open hyperlinks given by the `webbrowser` module. In my use case, this is problematic since users will run each other's code in the browser, allowing for this to be possible:

```python
import webbrowser
webbrowser.open("www.nastylink.com")
```

I've been researching and I can't seem to find a way to exclude these libraries during compilation, aside from manually deleting the offending files, which would make updating in the future a nuisance. Is there an easier way to exclude certain library modules during compilation that allows me to easily update Skulpt later without dealing with conflicts?

**Comment by s-cork** [comment]
Take a look at the comment in this file https://github.com/skulpt/skulpt/blob/master/support/build/wrapmodules.js

If you define libexcludes.json with an array of files to exclude then they should be excluded from your final build.

**Comment by SubwayMan** [comment]
This worked like a charm, thanks.
