### ISSUE TITLE
Is the "old style" default values setting way not supported any more?

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#1410]
For example,it seems this definition:
`mod.mymethod.$defaults = [Sk.builtin.none.none$, Sk.builtin.none.none$, Sk.builtin.none.none$, Sk.builtin.none.none$, Sk.builtin.none.none$]`
not work.

**Comment by s-cork** [comment]
it should be - the source code still uses `$defaults`.

I think you need to to make sure that you define the javascript function
apply any attributes like `$defaults`
the call `new Sk.builtin.func()` after the attributes have been added.
e.g. the current re module does this for `_split`.


```js
    function (pattern, string, maxsplit, flags) {
        // body
    }

    _split.co_varnames = ["pattern", "string", "maxsplit", "flags"];
    _split.$defaults = [ new Sk.builtin.int_(0), new Sk.builtin.int_(0) ];

    mod.split = new Sk.builtin.func(_split);

```

**Comment by alexwenbj** [comment]
OK, thank you. It should be my own code's problem. I will review it. @s-cork
