### ISSUE TITLE
import numpy

### ISSUE THREAD

**Issue by el2t** [skulpt/skulpt#1432]
Hi, I've been searching for a few hours on how to import skulpt libraries and now I can import json and pygal and it's working properly.

But when I try to import numpy I get the following error:
> ExternalError: Error: Assertion failure: bad call to float use 'new' on line 1

**Comment by s-cork** [comment]
If you're using the latest version of Skulpt there were breaking changes and some external libraries may not have upgraded.

You'll need to raise an issue with the skulpt numpy repo to get that fixed.
the use of `new` in `new Sk.builtin.float_(x)` is now required.
