### ISSUE TITLE
Check the syntax without running the code

### ISSUE THREAD

**Issue by OctopussyO** [skulpt/skulpt#1459]
Is it possible to check the syntax without running the code?

We have a python-unity bundle. You can write Python code with custom commands. Such commands send a request to a unity.
We need to be able to check the syntax without sending requests to the unity, and this case should not cause a time exceed error:
```
while (checkColor() != red):
    doSmth()
```

`checkColor` and `doSmth` are custom commands.
At the same time we want to see Syntax error if command entered in the editorthere is not in Sk.builtins or if there is a Syntax error in the code.

**Comment by OctopussyO** [comment]
@s-cork maybe you could help?

**Comment by s-cork** [comment]
If you're using master on this repo you can do `Sk.builtin.compile(source, filename, mode)`
You can also check out the source code for that function in `builtin.js` if you're running a different version.
`Sk.compile(source, filename)` is probably also sufficient for your use case.

`NameError`s in python can only happen at execution time. Ahead of time, the compiler doesn't know what globals/builtins exist in the current namespace.

**Comment by OctopussyO** [comment]
Thanks, I already tried that, it's not quite what we need. Thought there was another way. 
But if "NameErrors in python can only happen at execution time.", we will look for another solution. 

Thanks for the quick response!

**Comment by s-cork** [comment]
You might have some luck looking at tools that do type checking. But not sure I know of anything that would be able to run in the browser.
