### ISSUE TITLE
Can I directly replace the old version of skulpt?

### ISSUE THREAD

**Issue by Micro-sun** [skulpt/skulpt#1460]
At present, the old version of skulpt is being used in the project. Will there be breaking change problems replacing it with a new version?

**Comment by s-cork** [comment]
Yes. The `new` keyword will be required for all skulpt types, whrere previously this was optional. But other than that you'll probably be ok. It depends how much your project touches the internals of skulpt.

If you look at the tagged releases you'll see a list of some of the changes associated with moving to the latest version.
