### ISSUE TITLE
Make the compiled javascript functions support non-blocking execution

### ISSUE THREAD

**Issue by LeszekSwirski** [skulpt/skulpt#150]
Given that every function is compiled to a state machine, and all state is held in a couple of variables, it shouldn't be too hard to put that state machine and function state into a closure, and so allow functions to pause and resume.

This would lead to allowing a trampoline to resume these functions in a loop, and so to use `setTimeout` to cooperatively thread the execution of these functions with the browser event loop, allowing long-running functions without blocking/crashing the browser.

I've knocked together a hand-compiled example prototype of a python `meansq` function which calculates the average of square values in a given range. This runs for a couple of seconds, but doesn't block:
http://jsfiddle.net/LeszekSwirski/VvcMA/

**Comment by eah13** [comment]
@LeszekSwirski did your suspensions PR in #286 address your original issue here fully enough to close it?

**Comment by LeszekSwirski** [comment]
Entirely, thanks.
