### ISSUE TITLE
customize input returns wrong Type

### ISSUE THREAD

**Issue by moritzwicki** [skulpt/skulpt#1500]
Hey

In my app i want to customize the inputfun. it looks like this:

```
Sk.configure({
      inputfunTakesPrompt: true,
      output: this.outf.bind(this),
      read: this.builtinRead.bind(this),
      debugout: console.log,
      killableWhile: true,
      killableFor: true,
      inputfun(args: any) {
        return Promise.resolve(Number(window.prompt(args)));
      },
      __future__: Sk.python3
    });
```
it should return a number but its always a string. Is it possible give a number back?

**Comment by alexwenbj** [comment]
Why do you need number back?In Python,input() always return str, not other types.

**Comment by moritzwicki** [comment]
i want to parse the input to a int if the input is only a number

**Comment by bnmnetp** [comment]
@moritzwicki Why not just get the result back as a string and then use `isnumeric` and `int` to parse it to an int if needed?  There is not really any reason to change the internals when there are standard pythonic ways to do what you want.

**Comment by moritzwicki** [comment]
Where can I do that?
