### ISSUE TITLE
Display message text in prompt via "input()" Python function

### ISSUE THREAD

**Issue by l-atome** [skulpt/skulpt#1501]
Hello and thank you for your works ... 

I tried to use the "input()" function of Python and the message doesn't appear in the dialog box of Javascript ... And the message d'oesn't appaer in the "console python" because this instruction stop all the javascript execution ...

So my workaround to display my text message in the dialog box was :

1) add b.v in the "c=Sk.inputfun(b.v)"

`Sk.builtin.file.prototype.readline=new Sk.builtin.func(function(a,b){if(0===a.fileno){var c,d,e;c=c?c.v:"";c=Sk.inputfun(b.v);return c instanceof Promise?(e=new Sk.misceval.Suspension,e.resume=function(){return new Sk.builtin.str(d)},e.data={type:"Sk.promise",promise:c.then(function(a){return d=a},function(a){d="";return a})},e):new Sk.builtin.str(c)}c="";a.currentLine<a.lineList.length&&(c=a.lineList[a.currentLine],a.currentLine++);return new Sk.builtin.str(c)});`

2) I had the thirth argument in "return Sk.misceval.callsimOrSuspend(b.$d.stdin.readline,b.$d.stdin,a)"

`Sk.builtin.raw_input=function(a){var b=Sk.importModule("sys");a&&Sk.misceval.callsimOrSuspend(b.$d.stdout.write,b.$d.stdout,new Sk.builtin.str(a));return Sk.misceval.callsimOrSuspend(b.$d.stdin.readline,b.$d.stdin,a)}`

**Comment by s-cork** [comment]
I don't think this is an issue on the master branch
closing
