### ISSUE TITLE
proxy objects and events

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#1506]
@s-cork 

I was merging the latest to my Runestone fork and came across your great work with the document.js library.  Of course this resulted in a little bit of cleanup work on my side.

One thing I ran into is that I can't get the following to work, and I'm hoping you might have a workaround or different solution for me.

def bar():
   print("hello")

x = document.getElementByID("foo")
x.addEventListend("click", bar)

Maybe somewhat unsurprisingly bar does not get called when I click on  the foo object.

Any ideas?

Thanks!

Brad

**Comment by s-cork** [comment]
```python
import document

def bar(e):
    print("hello")

x = document.getElementById("runbrowser")
x.addEventListener("click", bar)

```

Some typos fixed but I assume that's not the problem

The error is the missing first argument to the event handler - i.e. the javascript wrapped event
You'll see errors in the console
You might want to add the `uncaughtException` option to your call to `Sk.configure`

**Comment by bnmnetp** [comment]
Of course... Too much Javascript thinking...

**Comment by hmelberg** [comment]
Was "addEventListener" added in 1.3? (I used CDN from jsDeliver to get Skulpt version 1.2. I could import document and use it, but when trying to add a listener I got 'Element' object has no attribute 'AddEventListener')

**Comment by s-cork** [comment]
It's currently on master branch but not part of a release yet (we should probably do that) and not on npm.
