### ISSUE TITLE
The browser crashes when executing the following code

### ISSUE THREAD

**Issue by muzichen** [skulpt/skulpt#1515]
```python
right_signal = 'green' * 30 + 'yellow' * 5 + 'red' * 25

for i in range(60):
    print(right_signal)
    right_signal = right_signal[1:] + [right_signal][0]
```

Tested the editor on skulpt's official website and it crashes too, anyone help to see what's causing this?

**Comment by s-cork** [comment]
have you tested this in normal cpython?
it also crashes, I think you want a different approach
With each iteration you're effectively doubling the length of the string
