### ISSUE TITLE
RHS in Sk.abstr.binary_op_ returns incorrect values

### ISSUE THREAD

**Issue by mariechatfield** [skulpt/skulpt#155]
Currently, when `Sk.abstr.binary_op_(v, w, opname)` is called, it uses `Sk.abstr.boNameToSlotFuncLhs_(v, opname)` to see if object `v` has the correct op. If not, it then attempts to use `Sk.abstr.boNameToSlotFuncRhs_(w, opname)`. If `w` has the correct op, it uses that method instead. 

However, it appears that `Sk.abstr.boNameToSlotFuncRhs_` doesn't properly use the right hand side operation. It just calls the left hand side operation and never inverts it.

```
Sk.abstr.boNameToSlotFuncRhs_ = function(obj, name) {
  if (obj === null) {
    return undefined;
  };
  switch (name) {
    case "Add":      return obj.nb$add          ? obj.nb$add :          obj['__radd__'];
    case "Sub":      return obj.nb$subtract     ? obj.nb$subtract :     obj['__rsub__'];
    case "Mult":     return obj.nb$multiply     ? obj.nb$multiply :     obj['__rmul__'];
    case "Div":      return obj.nb$divide       ? obj.nb$divide :       obj['__rdiv__'];
    case "FloorDiv": return obj.nb$floor_divide ? obj.nb$floor_divide : obj['__rfloordiv__'];
    case "Mod":      return obj.nb$remainder    ? obj.nb$remainder :    obj['__rmod__'];
    case "Pow":      return obj.nb$power        ? obj.nb$power :        obj['__rpow__'];
    case "LShift":   return obj.nb$lshift       ? obj.nb$lshift :       obj['__rlshift__'];
    case "RShift":   return obj.nb$rshift       ? obj.nb$rshift :       obj['__rrshift__'];
    case "BitAnd":   return obj.nb$and          ? obj.nb$and :          obj['__rand__'];
    case "BitXor":   return obj.nb$xor          ? obj.nb$xor :          obj['__rxor__'];
    case "BitOr":    return obj.nb$or           ? obj.nb$or :           obj['__ror__'];
  }
```

For example, assume object `x` has defined method `nb$divide` but object `y` does not.
Then `Sk.abstr.binary_op_(y, x, 'Div')` would return `x.nb$divide(y)`. This is clearly incorrect, as y / x  !== x / y.

I don't believe any test cases currently exist to check this. I discovered it when I was trying to make Skulpt recognize booleans as numbers, because booleans are one of the few Skulpt objects that are used in arithmetic operations that don't have the nb$ operations defined.

**Comment by s-cork** [comment]
This seems fixed since `nb$reflected_divide` and cousins were added at some point.
