### ISSUE TITLE
Compatibility Issues between Latest Skulpt Version and petlja/pygame4skulpt

### ISSUE THREAD

**Issue by TheNiska** [skulpt/skulpt#1554]
I've been trying to integrate the latest version of Skulpt with the petlja/pygame4skulpt for the last month. It seems that I am not able to correctly import all the pygame modules. Additionally, I am not good at JavaScript. At this point, I don't understand what I am doing anymore but my whole project depends heavily on pygame. Please help. There is almost no information on this topic available on the internet.

```
function builtinRead(x) {
    console.log(`Attempting to read module: ${x}`);
    if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined) {
        const s = /src\/builtin\/([^/]+\.py)$/g.exec(x);
        if (s && s.length === 2) {
            const n = s[1];
            if (Sk.customModules[n]) {
                return Sk.customModules[n];
            }

        } else {
            if (Sk.customModules[x]) {
                return Sk.customModules[x];
            }

            const n = Sk.externalLibraries[x];
            if (n) {
                const a  = n.path;
                return Sk.misceval.promiseToSuspension(fetch(a).then(async r => {
                    const o = await r.text();
                    Sk.customModules[x] = o;
                    return o, o
                }));
            }
        }
    }

    throw "File not found: '" + x + "'";
}
```

**Comment by bnmnetp** [comment]
The pygame4skulpt repo uses an outdated mechanism for importing 3rd party libraries into skulpt.

I don't remember all the reasons why we removed that functionality, or what our current suggested workaround is...

**Comment by s-cork** [comment]
What errors are you seeing?

It looks like you never return the file from the builtinFiles if it exists
So i'd expect your code to fail with any python module from the standard library

**Comment by TheNiska** [comment]
Sorry that it took me that much time to respond. I've been busy. It looks like all pygame modules are loaded, but still nothing works.

At first I do this:
`const loc = window.location;
const basePath = loc.protocol + '//' + loc.host + '/static/js/pygame/';

Sk.customModules = {};
Sk.externalLibraries = {
    './pygame.js': {
        path: basePath + '__init__.js',
    },
    'pygame/display.js': {
        path: basePath + 'display.js',
    },
    'pygame/draw.js': {
        path: basePath + 'draw.js',
    },
    'pygame/event.js': {
        path: basePath + 'event.js',
    },
    'pygame/font.js': {
        path: basePath + 'font.js',
    },
    'pygame/image.js': {
        path: basePath + 'image.js',
    },
    'pygame/key.js': {
        path: basePath + 'key.js',
    },
    'pygame/locals.js': {
        path: basePath + 'locals.js',
    },
    'pygame/mixer.js': {
        path: basePath + 'mixer.js',
    },
    'pygame/mouse.js': {
        path: basePath + 'mouse.js',
    },
    'pygame/time.js': {
        path: basePath + 'time.js',
    },
    'pygame/transform.js': {
        path: basePath + 'transform.js',
    },
    'pygame/version.js': {
        path: basePath + 'version.js',
    },
};`

**Comment by TheNiska** [comment]
Sorry that it took me that much time to respond. I've been busy. It looks like all pygame modules are loaded, but still nothing works.

At first I do this:
`const loc = window.location;
const basePath = loc.protocol + '//' + loc.host + '/static/js/pygame/';

Sk.customModules = {};
Sk.externalLibraries = {
'./pygame.js': {
path: basePath + 'init.js',
},
'pygame/display.js': {
path: basePath + 'display.js',
},
'pygame/draw.js': {
path: basePath + 'draw.js',
},
'pygame/event.js': {
path: basePath + 'event.js',
},
'pygame/font.js': {
path: basePath + 'font.js',
},
'pygame/image.js': {
path: basePath + 'image.js',
},
'pygame/key.js': {
path: basePath + 'key.js',
},
'pygame/locals.js': {
path: basePath + 'locals.js',
},
'pygame/mixer.js': {
path: basePath + 'mixer.js',
},
'pygame/mouse.js': {
path: basePath + 'mouse.js',
},
'pygame/time.js': {
path: basePath + 'time.js',
},
'pygame/transform.js': {
path: basePath + 'transform.js',
},
'pygame/version.js': {
path: basePath + 'version.js',
},
};`

This is my builtinRead:
`function builtinRead(x) {
    console.log(`Attempting to read module: ${x}`);
    if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined) {
        const s = /src\/builtin\/([^/]+\.py)$/g.exec(x);
        if (s && s.length === 2) {
            const n = s[1];
            if (Sk.customModules[n]) {
                console.log(`Found custom module in Sk.customModules: ${n}`);
                return Sk.customModules[n];
            }

        } else {
            if (Sk.customModules[x]) {
                console.log(`Found custom module in Sk.customModules: ${x}`);
                return Sk.customModules[x];
            }

            const n = Sk.externalLibraries[x];
            if (n) {
                const a  = n.path;
                console.log(`Fetching external library from: ${a}`);
                return Sk.misceval.promiseToSuspension(fetch(a).then(async r => {
                    const o = await r.text();
                    Sk.customModules[x] = o;
                    console.log(x);
                    Sk.builtinFiles["files"][x] = o;
                    console.log(`Fetched and stored custom module: ${x}`);
                    return o, o
                }));
            }
        }
    }


    throw "File not found: '" + x + "'";
}`

PYGAME CODE____
1) import pygame
2)
3) pygame.init()
4) rect = pygame.Rect(100, 100, 50, 100)
5) window = pygame.display.set_mode((500, 500))
6) window.fill((70, 255, 70))
7) pygame.draw.rect(window, (0, 0, 255), rect)
8) pygame.display.update()
END PYGAME CODE___

When I first time click "run" button after reloading the page I got error: ExternalError: InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0. on line 8

But my next clicks on the button give me one of two errors:
1)ImportError: No module named pygame on line 1
2)ImportError: No module named pygame on line 3

I cannot use older version of skulpt because then I have to use u"string" on any non english strings. But maybe there is a version of skulpt that uses python3 and at the same time works fine with pygame?

**Comment by TheNiska** [comment]
Ok. I fixed some my error and made it work in old version with python 2.x. But new version still doesn't work. This time error is different though:

Attempting to read module: src/builtin/pygame.js
Attempting to read module: src/builtin/pygame/__init__.js
Attempting to read module: src/lib/pygame.js
Attempting to read module: src/lib/pygame/__init__.js
Attempting to read module: ./pygame.js
Fetching external library from: http://127.0.0.1:8000/static/js/pygame/__init__.js
Fetched and stored custom module: ./pygame.js
NameError: name 'pygame' is not defined on line 3

OR

Attempting to read module: src/builtin/pygame.js
Attempting to read module: src/builtin/pygame/__init__.js
Attempting to read module: src/lib/pygame.js
Attempting to read module: src/lib/pygame/__init__.js
Attempting to read module: ./pygame.js
Attempting to read module: src/builtin/display.js
Attempting to read module: src/builtin/display/__init__.js
Attempting to read module: src/lib/display.js
Attempting to read module: src/lib/display/__init__.js
Attempting to read module: ./display.js
Attempting to read module: ./display/__init__.js
Attempting to read module: src/builtin/display.py
Attempting to read module: src/builtin/display/__init__.py
Attempting to read module: src/lib/display.py
Attempting to read module: src/lib/display/__init__.py
Attempting to read module: ./display.py
Attempting to read module: ./display/__init__.py
ImportError: No module named pygame.display on line 3

**Comment by TheNiska** [comment]
Updated builtinRead:

```
function builtinRead(x) {
    console.log(`Attempting to read module: ${x}`);
    if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined) {
        const s = /src\/builtin\/([^/]+\.py)$/g.exec(x);
        if (s && s.length === 2) {
            const n = s[1];
            if (Sk.customModules[n]) {
                console.log(`Found custom module in Sk.customModules: ${n}`);
                return Sk.customModules[n];
            }

        } else {
            if (Sk.customModules[x]) {
                console.log(`Found custom module in Sk.customModules: ${x}`);
                return Sk.customModules[x];
            }

            const n = Sk.externalLibraries[x];
            if (n) {
                const a  = n.path;
                console.log(`Fetching external library from: ${a}`);
                return Sk.misceval.promiseToSuspension(fetch(a).then(async r => {
                    const o = await r.text();
                    Sk.customModules[x] = o;
                    console.log(x);
                    Sk.builtinFiles["files"][x] = o;
                    console.log(`Fetched and stored custom module: ${x}`);
                    return o;
                }));
            }
        }
        throw "File not found: '" + x + "'";
    }

    return Sk.builtinFiles["files"][x];
}
```

**Comment by TheNiska** [comment]
Ok. I think I did it. Still it will be a lot of work in order for it to run properly but initialization and drawing are working.

```
Sk.externalLibraries = {
    './pygame.js': {
        path: basePath + '__init__.js',
    },
    './display.js': {
        path: basePath + 'display.js',
    },
    './draw.js': {
        path: basePath + 'draw.js',
    },
    './event.js': {
        path: basePath + 'event.js',
    },
    './font.js': {
        path: basePath + 'font.js',
    },
    './image.js': {
        path: basePath + 'image.js',
    },
    './key.js': {
        path: basePath + 'key.js',
    },
    './locals.js': {
        path: basePath + 'locals.js',
    },
    './mixer.js': {
        path: basePath + 'mixer.js',
    },
    './mouse.js': {
        path: basePath + 'mouse.js',
    },
    './time.js': {
        path: basePath + 'time.js',
    },
    './transform.js': {
        path: basePath + 'transform.js',
    },
    './version.js': {
        path: basePath + 'version.js',
    },
};
```


```
function builtinRead(x) {
    console.log(`Attempting to read module: ${x}`);
    if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined) {
            if (Sk.customModules[x]) {
                console.log(`Found custom module in Sk.customModules: ${x}`);
                return Sk.customModules[x];
            }

            const n = Sk.externalLibraries[x];
            if (n) {
                const a  = n.path;
                console.log(`Fetching external library from: ${a}`);
                return Sk.misceval.promiseToSuspension(fetch(a).then(async r => {
                    const o = await r.text();
                    Sk.customModules[x] = o;
                    console.log(x);
                    Sk.builtinFiles["files"][x] = o;
                    console.log(`Fetched and stored custom module: ${x}`);
                    return Sk.builtinFiles["files"][x];
                }));
            }

            throw "File not found: '" + x + "'";
    }

    return Sk.builtinFiles["files"][x];
}
```
