### ISSUE TITLE
linear algebra modules

### ISSUE THREAD

**Issue by jmtatsch** [skulpt/skulpt#177]
Hi Guys,

I've tried hard to get some pure python linear algebra modules working with skulpt but had no luck.

These are the ones i tried:
http://users.rcn.com/python/download/python.htm
http://code.activestate.com/recipes/189971-basic-linear-algebra-matrix/

Mine are adapted slightly because operators and types are not available on skulpt, you find them here:

http://pastie.org/8725007
http://pastie.org/8725009

But whenever I import them i get this strange error:

Uncaught TypeError: Cannot call method 'mp$subscript' of undefined skulpt.js:6199
Sk.builtin.type.buildMRO_skulpt.js:6199
Sk.builtin.type.buildMRO_skulpt.js:6201
Sk.builtin.type.buildMROskulpt.js:6229
Sk.builtin.typeskulpt.js:6002
Sk.misceval.applyskulpt.js:7267
Sk.misceval.callsimskulpt.js:7222
Sk.misceval.buildClassskulpt.js:7332
$scope2VM146:118
(anonymous function)VM146:5632
Sk.importModuleInternal_skulpt.js:22279
Sk.builtin.__import__skulpt.js:22341
$scope0VM145:15
(anonymous function)VM145:16
Sk.importModuleInternal_skulpt.js:22279
Sk.importMainWithBodyskulpt.js:22336
runittest.html:36
onclick

Does anyone know what I do wrong?

Cheers,

Julian

**Comment by albertjan** [comment]
Glad we could solve your issue @jmtatsch :trollface:
