### ISSUE TITLE
Rethinking the unit test system

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#211]
The ``./skulpt.py nrt`` command makes it easy to add a new unit test to the skulpt repository of tests, but it causes problems when there are multiple active pull requests.  Different developers will end up getting the same test number causing merge conflicts down the road.

In addition, it is increasingly difficult to know whether / where a unit test exists for a given feature of Python because the test cases are all numbered and are not descriptive of what they are testing.

Testing currently relies on diffing the output from a test run in the skulpt interpreter and the saved output from the "real python" interpreter.  This is fine, but can can cause big problems, especially with respect to floating point numerical values where there can be small differences in the results due to the underlying numerical representation.  Using something like ``unittest.assertAlmostEqual`` would work much better than comparing strings.

The CPython test suite uses descriptive names for the tests, and the unittest module to run tests.  Perhaps it is time to migrate in this direction.   Lets have some discussion about whether this is a good idea, and how we would like to proceed.

**Comment by albertjan** [comment]
@bnmnetp I'd say this has been completed 😄

**Comment by bnmnetp** [comment]
I would say this has taken off quite well.  I think I will close this.
