### ISSUE TITLE
inheriting from a builtin class crashes skulpt

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#213]
```
class Foo(list):
   pass
```

Skulpt crashes with the error:

```
Uncaught TypeError: Cannot call method 'mp$subscript' of undefined
```

I've poked at this a little bit, and the point that it crashes is in ``Sk.builtin.buildMRO_``  
when that function attempts to loop over the bases.  But the builtin classes do not have a ``$d`` attribute.

I need to figure out what that ``$d`` is all about and what should be done in the builtin classes.

**Comment by waywaaard** [comment]
This would be particular useful for our new unit testing approach as they use often custom exceptions. I am not sure about ```$d``` either though I figured up to now that it holds the instance variables (in a dict) of a type, that get copied to the subclass. The ```tp$getattr``` uses this dict for key lookups.

I am going to have a look at this - cause this is really bugging me and hinders me from adding a few other features.

**Comment by waywaaard** [comment]
I am one step closer in order to make those builtins subclassable. Due to order problems, we need create the dict, that holds all funcs, attributes about the builtin classes afterwards (see ```Sk.doOneTimeInitialization```)
I only have to figure a good way of adding all of those functions and attributes automatically

**Comment by bnmnetp** [comment]
I thought you mentioned a branch you were working on.  I checked your fork of skulpt but I don't think the branch is there.  The others are several days old.

**Comment by waywaaard** [comment]
I was just experimenting, those changes are just local. I am going to push them when I have managed to add the attributes and functions

**Comment by eah13** [comment]
@bnmnetp @waywaaard added this to our list of sprints, assuming it's still an open issue

**Comment by waywaaard** [comment]
So, I think we should discuss some possible solution approaches here. I was fiddling around with the issue and ended up writing an algorithm that automatically builds up the ```__mro__``` and ```__dict__``` for built-ins. However, this requires adding all functions as Python functions to the built-ins. I made the required for the new complex type and dict (see https://github.com/waywaaard/skulpt/blob/pr_complex_type/src/dict.js#L491)

**Comment by bnmnetp** [comment]
which would also have the benefit of  allowing us to add kwarg support in some places...  ``d = dict(a=1,b=2)`` if I'm understanding correctly.

**Comment by waywaaard** [comment]
I am not sure, this would require a few more things - I have to look at it again.

**Comment by acbart** [comment]
It seems like this is still an issue? Have there been any updates?

**Comment by rixner** [comment]
#490 improved the situation significantly.  I am not sure if there are remaining issues or what they might be.

**Comment by acbart** [comment]
It does seem to be fixed on the latest version on the site. I thought I had pulled all the latest changes at the start of the summer, but I must have failed to do so. Thanks for letting me know!
