### ISSUE TITLE
How do I display error messages from incorrect code?

### ISSUE THREAD

**Issue by ehmatthes** [skulpt/skulpt#214]
I have implemented a simple online interpreter using the example in the [gist](https://gist.github.com/bnmnetp/4650616), and it executes correct python code properly. However, if I try to run code with an error in it, I don't see the error message. For example, the code `print(x)` should result in a NameError, but I don't see that error.

When I enter `print(x)` on [CodeSkulptor](http://www.codeskulptor.org/#user31_WxYI9XQCaL_0.py), the error message is included in the console.

How can I access the error output?

**Comment by metulburr** [comment]
Is there a way to show it on the page instead of an alert?
