### ISSUE TITLE
How to handle def func(*args **kwargs)

### ISSUE THREAD

**Issue by ebertmi** [skulpt/skulpt#218]
I am currently porting a small subset of matplotlib.pyplot.

Now I've got some prototype running with support for the plot function:
`matplotlib.pyplot.plot(*args, **kwargs)`
But I've got some trouble implementing the keywords like matplotlib. I know i can add keywords with the `co_varnames`. But I would like to have the same signature as matplotlib. 

Currently working example:
![image](https://cloud.githubusercontent.com/assets/1634468/2936869/b1b4b842-d877-11e3-9cbf-8e37f8d4ae8a.png)

At the moment it is pretty hacky, though I got about 16 arguments already working.

**Comment by waywaaard** [comment]
one additional comment: kwargs and args impl. as showed above are not possible for builtins
