### ISSUE TITLE
How to import another module in a module

### ISSUE THREAD

**Issue by ebertmi** [skulpt/skulpt#222]
I want to use one of my numpy types in my matplotlib library. How can I import this particular type in the context of my other library module?

So that I can create this particular type or use the underlying javascript types. That would      help me a lot. I am currently working on implementing the `Line2D` class and want to convert my x/y axis to ndarrays when returning. Though the ndarray will be just a dummy. But so I can implement the scalar operations.

**Comment by muthukrishnan32** [comment]
Hi,

Can you please explain me completely how to work on Import Module's briefly..
