### ISSUE TITLE
string formatting explodes

### ISSUE THREAD

**Issue by davidhyman** [skulpt/skulpt#280]
String formatting has a bad time converting things to strings on its own, throwing:
 Uncaught TypeError: Cannot read property 'substring' of undefined

valid python, broken skulpt:
print '%s' % {'a':1}
print '%s' % []

valid python, working skulpt:
print '%s' % 'a'
print '%s' % 1
print '%s' % True
print '%s' % str({'a':1}) # force conversion
print '%s' % str([]) # force conversion
print "%(thing)s" % {'thing': 'abc'} # named substitutions

haven't tried functions, classes etc.

**Comment by waywaaard** [comment]
Just debugged into this, it seems that the ```nb$remainder``` function checks for named substitutions but does not handle the case of providing a ```dict``` without named subs. Therefore fails calling ```mk = mappingKey.substring(1, mappingKey.length - 1);```

**Comment by waywaaard** [comment]
Could be fixed with an additional case, though I am not sure if this covers every edge:

```python
        //print("Rhs:",rhs, "ctor", rhs.constructor);
        if (rhs.constructor === Sk.builtin.tuple) {
            value = rhs.v[i];
        } else if (rhs.mp$subscript !== undefined && mappingKey !== undefined) {
            // added check for mappingKey
            mk = mappingKey.substring(1, mappingKey.length - 1);
            //print("mk",mk);
            value = rhs.mp$subscript(new Sk.builtin.str(mk));
        } else if (rhs.constructor === Sk.builtin.dict || rhs.constructor === Sk.builtin.list) {
            // new case where only one argument is provided
            value = rhs;
        } else {
            throw new Sk.builtin.AttributeError(rhs.tp$name + " instance has no attribute 'mp$subscript'");
        }
```
