### ISSUE TITLE
package import bugs

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#299]
Given the directory structure:

```
test/
   __init__.py
   test_support.py
```

The following import statement fails:  ``from test import test_support``

However this one works:  ``from test.test_support import run_unittests``

We need to fix this behavior otherwise we are going to have to modify all of the CPython unit tests to import the ``run_unittests`` function.

**Comment by waywaaard** [comment]
Well the implementation is not that bad. I see that my module gets imported but skulpt fails to set the module as a property on the parent module. The parent module does not have ```$d``` to assign new values.

**Comment by waywaaard** [comment]
Modules do have a `$d` property but it is not an `Sk.builtin.dict`.
