### ISSUE TITLE
calling super method gives  'super_$rw$' is not defined error

### ISSUE THREAD

**Issue by ajaishankar** [skulpt/skulpt#31]
<pre>
class A(object):
    def foo(self):
        print "A"

class B(A):
    def foo(self):
        print "B"
        super(B, self).foo()
       
b = B()
b.foo()
</pre>

prints B and gives NameError: 'super_$rw$' is not defined error.

I am trying this in http://interactivepython.org/courselib/static/thinkcspy/GeneralIntro/introduction.html#algorithms, so don't know if it has already been fixed.

**Comment by acbart** [comment]
The alternate syntax does work, but `super` is still not implemented, correct?

**Comment by albertjan** [comment]
@acbart https://github.com/skulpt/skulpt/pull/694

**Comment by acbart** [comment]
Ah, looks like it's on the cusp of happening. I'll be patient, as I do have a workaround to super().
