### ISSUE TITLE
processingJS bridge: height, width, beginShape, endShape, random not implemented

### ISSUE THREAD

**Issue by juliendorra** [skulpt/skulpt#317]
Hi all, thanks to the great (and super quick) job of @bzwheeler the processingJS bridge now implement matrix operations. It allows really cool things like easy spirals or zooms : https://trinket.io/python/52e3c9cf87

My target test file is a small set of functions we use in Processing IDE Python Mode with (french) kids.
Here it is on Trinket : https://trinket.io/processing/836f8e60a8 
At the moment, a lot of what works in Processing IDE Python Mode (or would work in ProcessingJS) doesn't yet work in Skulpt.

I found that: height, width, beginShape, endShape and random are not yet bridged. I took a look at 
and they are not in the [__init__.js file](https://github.com/skulpt/skulpt/blob/master/src/lib/processing/__init__.js)
as per reference :
http://processingjs.org/reference/height/
http://processingjs.org/reference/width/
http://processingjs.org/reference/beginShape_/

**Comment by dsblank** [comment]
I am working on making Skulpt Processing more complete. Should have these added (and most everything else) by this weekend.

**Comment by juliendorra** [comment]
Wow, that's great news @dsblank I'll be sure to give it a try. If you need some examples to test on, don't hesitate to ask.

**Comment by dsblank** [comment]
@juliendorra Yes, testing is needed! All of the items you mentioned have now been added in a PR: https://github.com/skulpt/skulpt/pull/366 

Note that I had to make some design choices: https://github.com/Calysto/calysto/issues/5

We'll need to document these somewhere.

**Comment by tildebyte** [comment]
Do I need some kind of magic to use JavaScript's `sqrt`, or does *everything* have to be wrapped? Trying to e.g. `r = sqrt((x * x) + (y * y))` throws up `uncaught exception: NameError: name 'sqrt' is not defined on line 18`

**Comment by dsblank** [comment]
You're in Python now :) You need:

import math
math.sqrt((x * x) + (y * y))

**Comment by tildebyte** [comment]
headdesk

**Comment by dsblank** [comment]
@juliendorra I just gave an account to @tildebyte on our server, so there is nothing to install. If you would like to test that way, let me know (send preferred ID to doug.blank@gmail.com).

**Comment by tildebyte** [comment]
I'm having a bit of trouble there. I can log in, start a server, and create a new skulpt notebook just fine, but once I open the notebook, it's in a constant state of trying to connect or reconnect to the kernel.

**Comment by dsblank** [comment]
Hmmm... it is working for me. You using the "New" menu on right on
"dashboard" view?

**Comment by tildebyte** [comment]
Sure am. Let me start over and get back to you.

**Comment by dsblank** [comment]
I do see a bunch of 400 errors in the logs...

**Comment by dsblank** [comment]
What browser are you using? There may be issues with IE or with Safari.

**Comment by tildebyte** [comment]
Firefox, but it occurs to me that it might be one of my plugins.

**Comment by tildebyte** [comment]
RE missing `random`:

 ````python
import random
random.randint(0, 255)
````

is equivalent to P5.js `random(255)`

**Comment by dsblank** [comment]
We should add random()... it wasn't on your list :)

**Comment by tildebyte** [comment]
It's in this issue's subject ;)
Either way, it would make sense to wrap things in skulpt which behave differently from P5, n'est-ce pas?

**Comment by dsblank** [comment]
Yes, I agree... we should replicate as much as makes sense from ProcessingJS. I'll add random().

**Comment by dsblank** [comment]
Finding and fixing lots of bugs; here is the start of a test notebook:

http://jupyter.cs.brynmawr.edu/hub/dblank/public/Examples/SkulptPython/Skulpt%20Processing%20Tests.ipynb

There is one difference, but I think the ProcessingJS image is wrong.

**Comment by dsblank** [comment]
I think this issue can be closed. Please open issues on any specific bugs that you find. Thanks!

**Comment by Francyfx** [comment]
Hi,
Hi,I want to use width or heigth instead of environment.width,how to update the source code
