### ISSUE TITLE
.format() is not working

### ISSUE THREAD

**Issue by CAridorc** [skulpt/skulpt#321]
.format is a standard function so I don't understand why it doesn't work: example:

print "The answer is {}".format(42)

does not work.

ERROR = AttributeError: 'str' object has no attribute 'format'

**Comment by waywaaard** [comment]
This method is currently not implemented.

**Comment by gerbal** [comment]
there is a development branch at [gerbal/skulpt](https://github.com/gerbal/skulpt/tree/string-format) which has a partial, broken, implementation.

**Comment by bnmnetp** [comment]
Thanks @gerbal .  I look forward to getting a PR for this one!
