### ISSUE TITLE
Are Python objects saved as Javascript objects?

### ISSUE THREAD

**Issue by phase** [skulpt/skulpt#322]
If I run some Python code to get a String, how could I get the String in JS code?

**Comment by bnmnetp** [comment]
Can you give a small code sample of what you are trying to do?  For example how are you running the Python code?

**Comment by Phasesaber** [comment]
Almost a month later, here's an example.
```python
test = "String"
```
Could I then use that in JS?
```javascript
var test = Sk.getVariableFromPythonCode("test");
```

**Comment by waywaaard** [comment]
There is not function like this, though you can access the ```globals``` via ```Sk.globals``` or the locals in some specific contexts.

**Comment by Phasesaber** [comment]
How would I use the `globals` command?

**Comment by waywaaard** [comment]
```Sk.globals``` is a JavaScript object that holds all variables as properties. So you would try sth. like

```javascript
if(Sk.globals.hasOwnProperty("test")) {
    var test = Sk.globals["test"];
}

**Comment by Phasesaber** [comment]
Looking around in the examples, I found this file: https://github.com/skulpt/skulpt/blob/master/example/calling_from_js.html

It shows getting the value of a variable using `.tp$getattr` from a `Sk.importMainWithBody` object.

What's the difference between these?

**Comment by bnmnetp** [comment]
@Phasesaber I would strongly recommend that you take a look at the HACKING.rst file.  It has lots of useful information in there and may answer many of your questions.

It is still very unclear to what you are trying to accomplish.  Your example is small and easy to understand, but I'm struggling to figure out why someone would want to do that.  Skulpt programs are run as discrete units on the webpage.  Skulpt is not meant to be a replacement for javascript in doing web programming.  So maybe if you could say about more about what you are trying to accomplish we could be more helpful in pointing you in a good direction.
