### ISSUE TITLE
Running Python Code Without Interactive Interpreter

### ISSUE THREAD

**Issue by michaelrepper** [skulpt/skulpt#323]
I have been using Skulpt to run python code in the browser where I do not want the text editing area or the python code to be displayed to the user. I only need to run the python code and that's it.

I'm now doing this by changing ```"<stdin>"``` to ```"<string>"``` at: 

``` eval(Sk.importMainWithBody("<string>",false,prog) ```

and loading the python code into the prog variable from python files via Javascript.

This works, but is there a better way to do it?

**Comment by bnmnetp** [comment]
``Sk.importMainWithBody`` is the function to use.   How you choose to get your python program into a string to pass to that function is totally up to you.

Brad
