### ISSUE TITLE
property() - builtin

### ISSUE THREAD

**Issue by waywaaard** [skulpt/skulpt#326]
I was fiddeling with the property() builtin and tried to implement them in a pure python way. However it seems that the custom __get__ does not get called.

```python
class Property(object):
    "Emulate PyProperty_Type() in Objects/descrobject.c"

    def __init__(self, fget=None, fset=None, fdel=None, doc=None):
        self.fget = fget
        self.fset = fset
        self.fdel = fdel
        if doc is None and fget is not None:
            doc = fget.__doc__
        self.__doc__ = doc

    def __get__(self, obj, objtype=None):
        if obj is None:
            return self
        if self.fget is None:
            raise AttributeError("unreadable attribute")
        return self.fget(obj)

    def __set__(self, obj, value):
        if self.fset is None:
            raise AttributeError("can't set attribute")
        self.fset(obj, value)

    def __delete__(self, obj):
        if self.fdel is None:
            raise AttributeError("can't delete attribute")
        self.fdel(obj)

    def getter(self, fget):
        return type(self)(fget, self.fset, self.fdel, self.__doc__)

    def setter(self, fset):
        return type(self)(self.fget, fset, self.fdel, self.__doc__)

    def deleter(self, fdel):
        return type(self)(self.fget, self.fset, fdel, self.__doc__)

class test():
    def h(self):
        return 4
    h = Property(h, doc='''returns 4''')

t1 = test()
print(t1.h) # should return 4
```

Otherwise it would be pretty straight forward to implement the property() builtin and would allow us to port a few other modules as python modules

**Comment by bnmnetp** [comment]
It looks to me like __get__ and __set__ should be handled in object.js  (see around line 30) or type.js (around line 245).

I'm not totally really up to speed on descriptors, but at first look it seems like they ought to be treated as a special case of __getattr__ ??

**Comment by Jacco** [comment]
I have it working with this code in object.js (in Sk.builtin.object.prototype.GenericGetAttr):

    // otherwise, look in the type for a descr
    if (descr !== undefined && descr !== null && descr.ob$type !== undefined) {
        f = descr.ob$type.tp$descr_get;
        if (!(f) && descr["__get__"])
        {
            f = descr["__get__"];
            return Sk.misceval.callsim(f, descr, this);
        }
    }

Don't know if that is the proper place though

**Comment by Jacco** [comment]
At least it doesn't break any test :P

**Comment by Jacco** [comment]
And with the following additions to compile.js in buildcodeobj:

    //
    // attach the default values we evaluated at the beginning to the code
    // object so that it can get at them to set any arguments that are left
    // unset.
    //
    if (defaults.length > 0) {
        out(scopename, ".$defaults=[", defaults.join(","), "];");
    }

    if (decos.length > 0) {
        out(scopename, ".$decorators=[", decos.join(","), "];");
    }

And at the en of the same function:

    else {
        var res;
        if (decos.length > 0)
        {
            res = this._gr("funcobj", "Sk.misceval.callsim(", scopename, ".$decorators[0], new Sk.builtins['function'](", scopename, ",$gbl", frees, "))"); // scopename, ".$decorators[0](new Sk.builtins['function'](", scopename, ",$gbl", frees, "))";
        } else {
            res = this._gr("funcobj", "new Sk.builtins['function'](", scopename, ",$gbl", frees, ")");
        }
        return res;
    }

A have a single decorator working :-)

@waywaaard, @bnmnetp

**Comment by Jacco** [comment]
This code:

    def deco(fn):
        print fn
        return fn

    class cdeco:
        def __init__(self, fget):
            self.fget = fget

        def __get__(self, obj):
            print "get"
            return self.fget(obj)

    @deco
    def test(x):
        print x

    class testclass:
        def __init__(self, val):
            self._val = val;

        @cdeco
        def val(self):
            return self._val

    test('help')

    y = testclass(123)

    print y.val

Correctly outputs:

     <function test>
     help
     get
     123

**Comment by bnmnetp** [comment]
Holy crap!  That is very exciting!

**Comment by Jacco** [comment]
When doing the same in Sk.builtin.object.prototype.GenericGetAttr the following code:

    import time as _time

    def deco(fn):
        print fn
        return fn

    class cdeco:
        cnt = 0
        def __init__(self, fget=None, fset=None, fdel=None,doc=None):
            self.id = cdeco.cnt
            cdeco.cnt = cdeco.cnt + 1
            print "cdeco.__init__" + str(self.id)
            print "  " + str(fget)
            print "  " + str(fset)
            print "  " + str(fdel)
            self.fget = fget
            self.fset = fset
            self.fdel = fdel

        def __get__(self, obj):
            print "cdeco.__get__" + str(self.id)
            return self.fget(obj)

        def __set__(self, obj, value):
            print "cdeco.__set__" + str(self.id)
            if self.fset is None:
                raise AttributeError("can't set attribute")
            self.fset(obj, value)

        def __delete__(self, obj):
            print "cdeco.__delete__" + str(self.id)        
            if self.fdel is None:
                raise AttributeError("can't delete attribute")
            self.fdel(obj)

        def getter(self, fset):
            print "cdeco.getter" + str(self.id)
            return type(self)(fget, self.fset, self.fdel)

        def setter(self, fset):
            print "cdeco.setter" + str(self.id)
            return type(self)(self.fget, fset, self.fdel)

        def deleter(self, fdel):
            print "cdeco.deleter" + str(self.id)
            return type(self)(self.fget, self.fset, fdel)    

    @deco
    def test(x):
        print x

    class testclass:
        def __init__(self, val):
            self._val = val;

        @cdeco
        def val(self):
            print "testclass.val - getter"
            return self._val

        @val.setter
        def val(self, val):
            print "testclass.val - setter"
            self._val = val;

        @val.deleter
        def val(self):
            print "testclass.val - setter"

    test('help')

    y = testclass(123)

    print y.val

    y.val = 456

    print y.val

    del y.val

Correctly outputs:

    <function test>
    cdeco.__init__0
      <function val>
      None
      None
    cdeco.setter0
    cdeco.__init__1
      <function val>
      <function val>
      None
    cdeco.deleter1
    cdeco.__init__2
      <function val>
      <function val>
      <function val>
    help
    cdeco.__get__2
    testclass.val - getter
    123
    cdeco.__set__2
    testclass.val - setter
    cdeco.__get__2
    testclass.val - getter
    456

Only the deleter is not handled correctly yet. It is not implemented in compile.js. I think the way to go would be to make a dattr in abstract.js the in turn would try to find a method through object.tp$delattr that would call object.GenericDelAttr that would see a descriptor with a __delete__ method which would be returned.

**Comment by Jacco** [comment]
It only support 1 decorator and only on a method.

Shall I go ahead and create a new branch and pull request for this feature?

I am not certain about a few things though:
- how to correctly handle multiple decorators in compile.js
- I don't know if the adjustments to GenericGetAttr/GenericSetAttr are as they should be

After this focus would be to implement internal:
- property
- staticmethod

builtins

**Comment by bnmnetp** [comment]
I have created a ``decorators`` feature branch.  Make your pull request against that branch, then I can immediately accept your PR on the branch.  This will make it available for others to also contribute to getting it all cleaned up.

When we are all happy then we can make a PR to merge the decorators branch to master.

**Comment by Jacco** [comment]
Great :-)
