### ISSUE TITLE
Call to open('filename.txt') with a single parameter fails

### ISSUE THREAD

**Issue by csev** [skulpt/skulpt#33]
If you do not provide 'r' as the second parameter on an open, Skulpt will fail with a 

todo; haven't implemented non-read opens

But the open _should be_ a read open.   The problem is that the line in src/builtins.py that would solve this:

```
if (mode === undefined) mode = "r";
```

Is wrong and should be:

```
if (mode === undefined) mode = new Sk.builtin.str("r");
```

I have fixed this in the old repo here 

http://code.google.com/r/drchuck-skulpt-mods/source/detail?r=85c1f4b4a8757c6f5c4b8ba190311b3dbc9b701e

I will fork this repo, make the fix, and submit a pull request.

This is the first of a number of small fixes that I have already done in the Google Code repo that I will be bringing across to the Github repo.  Comments welcome.

**Comment by venkatvkv** [comment]
Hi Charles,
I am one your students attending The Python class.
I tried doing the Assignment 7.1 online on pr4e.dr-chuck.com.
# Use words.txt as the file name
fname = raw_input("Enter file name: ")
fh = open(fname,'r')
fout = open('words.txt','w')

for line in fh:
    temp = line.upper()
    fout.write(temp)  
fout.close()
I tried fopen with and without 'r', but the error "todo; haven't implemented non-read opens" is still present. 
if you have few mins, plz let me know that am I doing something wrong in opening the file ?
Thanks
Venkat
