### ISSUE TITLE
String %s format ignores fieldwith

### ISSUE THREAD

**Issue by waywaaard** [skulpt/skulpt#331]
Just stumbled across this behavior:

```python
print("%4s%4s%4s" % ("dez", "okt","hex"))

for z in range(59,69):
    print("%4d%4o%4x" % (z, z, z))
print()
```

The strings should be padded with one additional space, however in the ```nb$remainder``` function only the precision is handled. Could be easily fixed with:

```javascript
else if (conversionType === "s") {
            r = new Sk.builtin.str(value);
            if (precision) {
                r.v = r.v.substr(0, precision);
            }

            if(fieldWidth) {
                r.v = handleWidth([" ", r.v]);
            }
            return r.v;
        }
```

**Comment by bnmnetp** [comment]
Thats an easy fix.  I'll apply it, and at the same time I'm going to look into running some of the other string formatting tests from the Python unit test module.
