### ISSUE TITLE
__contains__ not working

### ISSUE THREAD

**Issue by waywaaard** [skulpt/skulpt#338]
See following simple snippet (from test_dict.py):

```python
class a(object):
    d='ddd'
    def __contains__(self, m):
        if self.d: return True
b=a()

print 'd' in b
```

should return ```True```

skulpt returns: ```TypeError: 'a' object is not iterable on line 7```

> According to the docs (https://docs.python.org/2/reference/datamodel.html#object.__contains__) and the membership details (https://docs.python.org/2/reference/expressions.html#membership->test-details):

> For user-defined classes which define the __contains__() method, x in y is true if and only if  y.__contains__(x) is true.

> For user-defined classes which do not define __contains__() but do define __iter__(), x in y is true  if some value z with x == z is produced while iterating over y. If an exception is raised during the iteration, it is as if in raised that exception.

> Lastly, the old-style iteration protocol is tried: if a class defines __getitem__(), x in y is true if and > only if there is a non-negative integer index i such that x == y[i], and all lower integer indices do not  raise IndexError exception. (If any other exception is raised, it is as if in raised that exception).

I would dig into this though I am not really sure what to do, seems that either the automatically mapping is not working and/or more is broken

edit:

also, it is not possible to do this:
```python
{}.__contains__('a')
```

**Comment by waywaaard** [comment]
Does anyone have some pointers on this one? I would like to fix it.

**Comment by waywaaard** [comment]
This update to sequence contains fixes the first bug:

```javascript
Sk.abstr.sequenceContains = function (seq, ob) {
    var it, i;
    var seqtypename;
    if (seq.sq$contains) {
        return seq.sq$contains(ob);
    }

    if(seq.tp$getattr("__contains__")) {
        return Sk.misceval.callsim(seq.__contains__, seq, ob);
    }

    seqtypename = Sk.abstr.typeName(seq);
    if (!seq.tp$iter) {
        throw new Sk.builtin.TypeError("argument of type '" + seqtypename + "' is not iterable");
    }

    for (it = seq.tp$iter(), i = it.tp$iternext(); i !== undefined; i = it.tp$iternext()) {
        if (Sk.misceval.richCompareBool(i, ob, "Eq")) {
            return true;
        }
    }
    return false;
};
```

The second one requires to explicit map the internal functions to magic methods.

**Comment by waywaaard** [comment]
This should be working due to my changes in my big PR. However, it does not work on skulpt.org. Is this version an older one?

I just want to close resolved issues.

**Comment by bnmnetp** [comment]
None of the recent fixes have been pushed to skulpt.org yet.
