### ISSUE TITLE
Cannot have more than one turtle app on a page

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#341]
Ben,

I ran across one more regression with the new turtle.  I have always been able to keep the results of multiple turtle programs visible on the page, so I could go look at the output from one or more programs just by scrolling around.  However in the new world, when I run a second turtle program on the same page the previous turtle output disappears.   

Is there a way to prevent the previous canvases from getting destroyed? 

Thanks,

Brad

**Comment by bzwheeler** [comment]
@bnmnetp - Dang, sorry about that.  Working on a fix now, nearly there just a couple of odds and ends to take care of.  Should I leave the previous canvas animation running?

**Comment by bnmnetp** [comment]
Good question. We have never been able to start a new one until the old one finished. But if it's not too difficult leaving the old one to finish would be great.
