### ISSUE TITLE
AJAX module

### ISSUE THREAD

**Issue by JacquesMarais** [skulpt/skulpt#350]
What about making a module for AJAX?

**Comment by bnmnetp** [comment]
We have a start on a functional urllib module which of course uses AJAX to do its work.   Otherwise I'm not aware of an ajax module for Python.  Do you have an example of how you want to use an AJAX module?

**Comment by JacquesMarais** [comment]
I meant like a module to do AJAX requests more easily, but maybe the urllib can do it. I don't know python modules really.
