### ISSUE TITLE
float builtin does not use __float__...

### ISSUE THREAD

**Issue by waywaaard** [skulpt/skulpt#369]
I am currently implementing the complex number type and just wondered how to do this properly.

In CPython the complex type does implement ```nb_float```, ```nb_int```. However, skulpt does not regard those and therefore we can't also implement our own specific ```__float__``` and ```__int__```

The same for ```__round__```. Would it be sufficient to upgrade the builtins and implement ```__float__``` on complex?

Or do we need a proper mapping of ```nb$float``` to ```__float__```.

Regards

**Comment by waywaaard** [comment]
The current implementation of the builtin types is completely off standard. The builtins ```int``` and ```float``` should call the appropriate magic methods and not do all in the ```constructor```.

**Comment by brianpmarks** [comment]
@waywaaard Thanks for looking into this. We've got some users that are really interested in complex number support. Anything we (at trinket) can do to help out?

**Comment by waywaaard** [comment]
Currently, I am in the testing phase and discovered a few edge cases while parsing complex strings, e. g., ```"-inf+nanj"```. I am looking forward fixing those soon.

**Comment by waywaaard** [comment]
can be closed.
