### ISSUE TITLE
Sk.builtin.sorted defaults are faulty

### ISSUE THREAD

**Issue by waywaaard** [skulpt/skulpt#371]
The ```Sk.builtin.sorted.$defaults``` should use ```Sk.builtin.none.none$``` and not ```Sk.builtin.none```. This may cause some problems later while comparing the ```cmp``` argument via following statement ```cmp instanceof Sk.builtin.none```

**Comment by bnmnetp** [comment]
This brings up an interesting problem.  Using ``Sk.builtin.none.none$`` causes a problem because Sk.builtin.none.none$ is not instantiated at the time the builtin.js file is evaluated.  Sk.builtin.none.none$ is not created until object.js is loaded.

**Comment by bnmnetp** [comment]
Using ``sk.builtin.none.none$`` like this introduces a circular dependency between builtin.js and object.js.

I guess the easy solution is to put ``sorted`` into sorted.js and put sorted.js after object.js in the load order in skulpt.py
