### ISSUE TITLE
Strange behavior with 3D renderer(s)

### ISSUE THREAD

**Issue by tildebyte** [skulpt/skulpt#374]
Copy/pasted from the `calysto` repo, as I want to avoid it disappearing after the `calysto` issue's closing.

me: Hmm...
[This](http://jupyter.cs.brynmawr.edu/hub/benalkov/public/Demos/Graphics.ipynb) sketch should look like [this](https://ello.co/quaestor/post/KrEvkCByAqEx8SldADVHJg) animated GIF.
The code is as close as I can make it. The only differences are the Skulpt/P5js-isms and the code used for the ello post has slightly different parameters, to allow it to loop much more quickly (note, however, that the GIF doesn't loop properly in Firefox >_>).
I'm not getting any warnings or errors.

@dsblank Any idea what the problem is with that example?

me: I just don't even know... TBH, my understanding of the math is pretty minimal. Everything else is pretty straightforward.
AFAICT, it's like it's being drawn in 2D, or something. 1 segment doesn't show up; 2 move up and down; 3 float around a bit, but only in a plane.
The 2D renderers don't work, of course. I've tried `P3D`, `WEBGL`, and `OPENGL`, and they all draw the same way, although they behave slightly differently (`OPENGL` flickers *a lot*).
Edit:
Maybe it has something to do with
````py
def rotateCoords():
    rotateX(PI)  # y up.
    translate(256, -256, 0)
````

I'd try it without, but the reason I use it is because I can't properly visualize (in my head, that is) `0,0` in the upper left corner...

**Comment by dsblank** [comment]
To make @tildebyte 's point clearer, here is what is expected:

https://ello.co/quaestor/post/KrEvkCByAqEx8SldADVHJg

and this is what Skulpt Processing does:

http://jupyter.cs.brynmawr.edu/hub/benalkov/public/Graphics.ipynb

**Comment by tildebyte** [comment]
New URL http://jupyter.cs.brynmawr.edu/user/benalkov/notebooks/Public/Demos/Graphics.ipynb

**Comment by dsblank** [comment]
@tildebyte You still need to "publish" that notebook, and get *that* URL.

**Comment by dsblank** [comment]
Which will give you this:

http://jupyter.cs.brynmawr.edu/hub/benalkov/public/Demos/Graphics.ipynb

**Comment by dsblank** [comment]
@tildebyte Any differences between Skulpt Processing and py.processing we should note (and seriously consider as a bug).

**Comment by tildebyte** [comment]
Sorry for the noise. So, moving things around in my `Public` folder doesn't affect things which have already been published?

**Comment by dsblank** [comment]
If you move a notebook, it will have a different /hub/NAME/public/ URL,
which is different from the editing /user/NAME/tree/Public/ URL.
