### ISSUE TITLE
`getMousePressed()` seems to be missing

### ISSUE THREAD

**Issue by tildebyte** [skulpt/skulpt#376]
`uncaught exception: NameError: name 'getMousePressed' is not defined`

(boilerplate omitted)
````py
def draw():
    lights()
    translate(environment.width / 2 + 30, environment.height / 2, 0)
    rotateX(-PI / 6)
    rotateY(PI / 3 + mouse.y / float(environment.height) * PI)
    box(45)
    if getMousePressed() == 1:
        translate(0, 0, -50)
        box(30)
````

**Comment by dsblank** [comment]
There are a few difference, noted in code, but we need some real docs:

```java
    // NOTE: difference with ProcessingJS
    // frameRate is only a function, not a variable: 
    // use environment.frameRate for value
    // Use mouse.pressed rather than mousePressed
    // Use environment.keyPressed rather than keyPressed
    // Use environment.frameCount 
    // Use environment.online
    // Use environment.focused
    // Use width() or environment.height rather than width
    // use height() or environment.height rather than height
    // Use mouseX() or mouse.x rather than mouseX
    // Use mouseY() or mouse.y rather than mouseY
    // Use pmouseX() or mouse.px rather than pmouseX
     // Use pmouseY() or mouse.py rather than pmouseY
```
So, that should be `mouse.pressed`

**Comment by tildebyte** [comment]
Even simpler:
````py
def draw():
    if mouse.pressed:
        box(30)
````
but now I get something I've seen before, but which I was unable to successfully debug (it just went away after an update):
`uncaught exception: ExternalError: TypeError: a is undefined`

**Comment by bnmnetp** [comment]
In my list of callbacks I have mousePressed, but not getMousePressed.  I was not aware of the getMousePressed callback, or should you be using mousePressed ?

**Comment by dsblank** [comment]
The confusion is that Processing can use the same token to be a value, and a function. `mousePressed` can be a function written by the user. But then we need to provide a method to get the value provided by the variable mousePressed. `getMousePressed` and 'mouse.pressed` do the same thing. I added getMousePressed before I saw the other methods. We can get rid of `getMousePressed` and the other duplicate methods. Or we can look to see how py.processing did it, and match their method.

**Comment by bnmnetp** [comment]
Hmmm,

Right now, I can confirm that mouse.pressed is broken.  I think it is because I was treating it only as a callback and not providing a proper mapping back into processing to check whether it was pressed or not.

On line 1566 I define a list of possible callbacks,  In the case of mousePressed if the user has not defined it then we ought to map back somewhere to get the boolean value.

Does that make sense?

**Comment by dsblank** [comment]
Are you saying that if you define it, it will be a function that gets called when you click, but if you don't it will be a boolean value? That doesn't sound like a good idea.

**Comment by bnmnetp** [comment]
No, what I meant to say was that if you define it mousePressed will be called when a mouse click is pressed.  Otherwise mouse.pressed should return the proper value.  Which after 30 more seconds of look appears to come from ``mod.processing.__mousePressed``

**Comment by dsblank** [comment]
I think `mouse.pressed` should always return the proper value, regardless of whether the user has special code for handling a mouse press in a `mousePress` function. At least that is my understanding of Processing.

**Comment by bnmnetp** [comment]
Yes, I agree.
