### ISSUE TITLE
Skulpt.org is broken in two ways

### ISSUE THREAD

**Issue by dsblank** [skulpt/skulpt#377]
1. You can never run the turtle demo after clicking the `clear` link
1. Running:
```python
>>> x = 1
>>> print x
```
fails, with `NameError: name 'x' is not defined on line 1`

But this works:
```python
>>> x = 1; print x
```

**Comment by waywaaard** [comment]
confirmed
1 case:
After clearing the ```turtle demo``` does not work anymore. 

2. case:
And after the turtle demo has finished and you try to use the ```interactive mode```, it fails with the error message @dsblank reported.

**Comment by bnmnetp** [comment]
Just fixed case 1.  The clear button hid the canvas.  The turtle used to show the canvas but does not any more.  So we need to handle that better.

Case 2:  Fails in the way you report, but only after running something the demo above it.

@albertjan Any idea why this might be happening?  Maybe this has always been the case.

Brad

**Comment by albertjan** [comment]
No it shouldn't be failing and it isn't in my browser:

```python
    Python 2.6(ish) (skulpt, Wed Apr 15 2015 10:10:02 GMT+0200 (W. Europe Daylight Time))
    [Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36] on Win32
    Don't type "help", "copyright", "credits" or "license" unless you've assigned something to them
>>> x = 1
>>> print x
    1
```

@dsblank could you post the message too? So I can see which browser and version you are using,

**Comment by albertjan** [comment]
@dsblank nevermind. I know what the issue is.

**Comment by albertjan** [comment]
It has to do with the `Sk.retainGlobals` setting. Because every statement in the repl is a seperate skulpt program. We need to retain the global variables between runs. This is done by setting the aptly named `retainGlobals` :smile:. But because the first example and the repl share the same skulpt instance. And retainglobals is only set for the repl. 

I think the solution is to put the repl in an iframe and isolating it that way. Or maybe even make it a @trinketapp repl. Which is afaik the same code. But allready runs in an iframe.

**Comment by bnmnetp** [comment]
It seems like there might be a bug with retain globals then, because I checked and Sk.retainGlobals is set to true, but after ``x=1`` there is not an x in Sk.globals.   After running an example from the first instance.

**Comment by albertjan** [comment]
But we don't want to retain globals between runs in the first example.

**Comment by bnmnetp** [comment]
Agreed.  But the sequence of operations is:

1.  Bring up skulpt.org
2.  check Sk.retainGlobals  --- undefiend
3.  run the turtle example
4. check Sk.retainGlobals -- false
5. check Sk.globals  (contains turtle, c and t) -- so it is retained anyway.
6. type in x = 1 to repl
7. check Sk.retainGlobals -- now it is true
8. check Sk.globals (contains turtle, c and t but NOT x)

**Comment by albertjan** [comment]
You're right that does smell like a bug. I will investigate.

**Comment by dsblank** [comment]
Both of these issues are now fixed. Can someone update the skulpt.org website?

**Comment by bnmnetp** [comment]
done
