### ISSUE TITLE
skulpt does not preserve negative zeros

### ISSUE THREAD

**Issue by ebertmi** [skulpt/skulpt#380]
Though javascript uses the IEEE747 number implementation with a positive and negative zero, skulpt does not preserve the sign of a zero. Therefore, a few unit tests are failing.

The main problem is not the `Sk.builtin.nmber()` constructor. Rather more it is located in `compile.js` while handling `Num`. At this specific place the javascript code for creating a number is generated. The generator for numbers uses implicitly the `toString()` method of numbers which does not distinguish the signs. In order to fix this, we would need to use a custom toString method for the number values in order to preserve the signs.

Example:

``` python
f = -0.0
print(f)
```

**Comment by waywaaard** [comment]
Well, there are many places which require changes for adding this behavior.

**Comment by bnmnetp** [comment]
That does seem to be the case with many things.  What are you getting at?

Is this change necessary to complete the PR for complex numbers?

In my view, having complex numbers without support for negative 0 is far better than not having complex numbers.  This will always be a project of continual improvement, and working our way towards CPython.

**Comment by waywaaard** [comment]
It is not necessary, though the test cases are failing. But I am almost finished add the negative number behaviour to skulpt. I have only 1 failing test.

**Comment by waywaaard** [comment]
Added in PR #443 .

**Comment by bnmnetp** [comment]
I tried:

```
f = -0.0
print f
g = f * 10
print g
```

The first print printed a negative 0, but the second reverted back to positive.

**Comment by waywaaard** [comment]
Okay, then I've missed some spots. I am going to have a look into this.

**Comment by albertjan** [comment]
```>>> f = -0.0
>>> print f
-0.0
>>> g = f * 10
>>> print g
-0.0
>>> ```
