### ISSUE TITLE
How to use external fies/modules?

### ISSUE THREAD

**Issue by tildebyte** [skulpt/skulpt#381]
Is it possible to "import" or "include" a .py file from the same directory as a notebook? Or even split things up into multiple cells which can communicate with each other...

So far, it hasn't been too much of a pain to simply paste in external classes, but as I try more complex examples, I'd like to be able to have, for instance, external libs/modules which won't necessarily be installed system-wide (for example the extremely keen [`grapefruit`](https://github.com/xav/grapefruit) color manipulation library, which is super-convenient as it's a single .py file).

It would also be nice to be able to use external *data* files.

All of this kind of leads up to being able to have a folder of files, including the main notebook, which *looks* like a Processing/P5.py sketch:

````
SpinningTop <folder>
   |____data <folder>
   |    |____Less-Angry_Rainbow_hex.csv
   |____getPaletteCSV.py
   |____grapefruit.py
   |____SpinningTop.ipynb
   |____top.py
````

**Comment by bnmnetp** [comment]
You need to provide skulpt a javascript function called builtinRead(fname)  which is used by the import mechanism.

This function can do whatever you want it to as long as it returns a string coresponding to the contents of a file.   I have not looked into Jupyter or Calisto very much, but maybe @dsblank knows how we could bridge this javascript function back to the server to do a file read.

NOTE  This will best be implemented using suspensions  (which we should also refactor the image loading functions to use suspensions as well)

**Comment by bnmnetp** [comment]
Yes, you can call ``jseval`` and pass it a string of  javascript code.
