### ISSUE TITLE
unitttest.assertTrue is faulty

### ISSUE THREAD

**Issue by waywaaard** [skulpt/skulpt#383]
During testing my complex type implementation, this error was driving me crazy. The ```assertTrue``` implementation is wrong, though seems to work for most cases. However, while using the real unittest cases it was failing.

```python
    def assertTrue(self, x, feedback=""):
        res = bool(x) is True
        self.appendResult(res, str(x)+' to be ',True,feedback)
```
This is a proper impl. as stated in https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertTrue

my unittest case:
```python
import unittest

from random import random
from math import atan2, isnan, copysign
import operator

INF = float("inf")
NAN = float("nan")
# These tests ensure that complex math does the right thing

class ComplexTest(unittest.TestCase):
    def test_boolcontext(self):
        for i in range(100):
            self.assertTrue(complex(random() + 1e-6, random() + 1e-6))
        self.assertTrue(not complex(0.0, 0.0))




def test_main():
      unittest.main()

if __name__ == "__main__":
    test_main()
```

**Comment by bnmnetp** [comment]
Sorry it caused you wasted time.  Unfortunately that probably won't be the last edge case that is wrong in the unittest framework.

Do you plan to submit the fixed assertTrue with your PR?  If not, I will update the unittest library today.

Brad

**Comment by waywaaard** [comment]
I've fixed it, but it may take some time. There are still some errors in my implementation.
