### ISSUE TITLE
NotImplemented not implemented

### ISSUE THREAD

**Issue by waywaaard** [skulpt/skulpt#384]
I can't find the ```NotImplemented``` that is required for the ```richcompare``` functions. Maybe we should add this.

**Comment by bnmnetp** [comment]
Sorry, I have no idea what you are asking for.  the NotImplemented exeption is in errors.js but I don't think that is what you are asking for.

**Comment by waywaaard** [comment]
No there is a constant ```NotImplemented```: https://docs.python.org/2/library/constants.html#NotImplemented
