### ISSUE TITLE
Performance issues with suspensions

### ISSUE THREAD

**Issue by rixner** [skulpt/skulpt#403]
I spent some time looking into the slowdowns I have seen with suspensions.  I am assuming that others can reproduce my findings.  I used the following simple program (there is nothing special about this program, the issue is very common for me):

```
import time

start = time.time()

DIM = 1200

grid = [[0 for x in range(DIM)] for y in range(DIM)]

for x in range(DIM):
    for y in range(DIM):
        grid[x][y] += 2

print "done"

end = time.time()
print "elapsed:", end - start
```

If you run this program on the current head (1b6d815) and on the commit before suspensions were added (dc03fba) you should see a performance difference.  On my machine, it took 2.4 seconds prior to accepting suspensions and 3.34 seconds now.  Just now, I used `git bisect` to try to hunt down the problem (I had not done that before) and it says that cce01be is the problem commit.

Can anyone else confirm or refute that they are seeing the same behavior?

**Comment by LeszekSwirski** [comment]
Try setting the `yieldLimit` option to `null`.

**Comment by rixner** [comment]
So, it seems like the default ```yieldLimit``` is infinity, right?  So, it was never actually yielding.  Does this imply that the check against the yield limit is that expensive?  If one were to actually want to be able to yield, this seems like a pretty high price to pay.  I had assumed that I should not see much of an overhead when the limit was high.  Or am I misunderstanding something?

**Comment by LeszekSwirski** [comment]
Yes, the checks really are that expensive. I believe this is due to checking the value on a global object, I recall in some experiments that checking it on a local was much cheaper, but this would have required larger changes to the code gen. The hard timeout check is similarly expensive.

The reasoning behind this default value is that if `yieldLimit` is infinity, the process never yields (matching default behaviour), but can be set to yield by the executing code using `sys.setYieldLimit()`. However, if `yieldLimit` is `null`, then the yield checks are not generated at all in the python code, so the yield limit cannot be set in code. I chose this default behaviour to avoid unexpected behaviour when calling `sys.setYieldLimit()`.

**Comment by rixner** [comment]
With ```yieldLimit``` set to ```null```, I get 2.7 seconds.  So, there is still a 10% penalty.  If I set both ```yieldLimit``` and ```execLimit``` to ```null```, I get 1.97 seconds.  So, yes, both checks are expensive.  I think it's a combination of the call to ```new Date()``` and access to the global object.

I presume the 10% penalty (which is still high), comes from the many ```instanceof``` checks on ```$ret```?

**Comment by LeszekSwirski** [comment]
Does this penalty disappear if `canSuspend` is set to `false`? I'm trying to figure out if this is an actual Suspension regression or something else.

**Comment by bnmnetp** [comment]
I'm certain the performance penalty for new Date() on the execLimit was introduced long before Suspensions.   It seems like there ought to be a faster way to get the current time than creating a new object.

I may be wrong, but I don't think that anyone has given any real attention to performance optimizations in Skulpt, so there is probably lots of low hanging fruit.

**Comment by LeszekSwirski** [comment]
Sorry, I meant the 10% penalty when `yieldLimit` is null but `execLimit` isn't.

I did introduce a couple of performance optimisations in the past, in particular #293, so I'd be disappointed if there was a regression even if Suspensions are disabled.

**Comment by LeszekSwirski** [comment]
We could switch `new Date()` to `Date.now()`: http://jsperf.com/new-date-vs-date-now-vs-performance-now/29

**Comment by rixner** [comment]
With ```yieldLimit: null``` and ```canSuspend``` set to ```false```, I still get around 2.7 seconds.

**Comment by LeszekSwirski** [comment]
That sounds like a non-suspension regression then, I believe that when `canSuspend` is set to `false`, no suspension checks are generated. Have you tried a git bisect with these parameters?

**Comment by rixner** [comment]
I still see code relating to suspensions, so either I did something incorrectly or setting ```canSuspend``` to ```false``` in the call to ```Sk.importMain``` does not disable all suspension code generation.  For instance, the following code still appears everywhere:

```
/* --- function return or resume suspension --- */
if ($ret instanceof Sk.misceval.Suspension) {
    return $saveSuspension($ret, './grid.py', 15, 6);
}
```

**Comment by LeszekSwirski** [comment]
That sounds like a bug. I'll check it out.

**Comment by LeszekSwirski** [comment]
I've submitted 3 performance improvements (#404, #404, #405). On my machine, I get the following timings:

Before:
*  Suspensions disabled: 5.45s
*  Suspensions enabled: 5.47s

After:
*  Suspensions disabled: 3.52s
*  Suspensions enabled: 3.78s

I'm still not sure where the slow-down in the suspensions is coming from, but things should at least be faster for now when they're disabled (as well as in general). Also, I'm seeing a lot of variation in these results -- these numbers are averages from 5 runs, but I'm seeing more that 10% variation between runs.

**Comment by rixner** [comment]
With the latest head (0a5473e), I get 2.4 seconds on the same machine I used for the other numbers, back to the pre-suspensions performance (dc03fba).  I do see variance across runs, but not as high as you are reporting...

**Comment by LeszekSwirski** [comment]
I was actually hoping for a larger improvement than that. What sort of system (OS, browser, CPU) are you running this on? My timings are all from Win8.1 x64, Chrome 43, i7-3770K

**Comment by Jacco** [comment]
Maybe suspensions can be timed using performance.timing.now()
