### ISSUE TITLE
turtle.clone() method 

### ISSUE THREAD

**Issue by dz0** [skulpt/skulpt#409]
Hi, 

it is convenient in game programming -- to make one object, and then clone it... 
Maybe, wouldn't be hard to implement?
https://docs.python.org/3.4/library/turtle.html#turtle.clone

**Comment by eah13** [comment]
Thanks for the request. You're very right that cloning will be convenient in turtle games programming.  I'm recording a video right now and hadn't thought to try it.

For posterity, here's the link to the Python 2 version of the above
https://docs.python.org/2/library/turtle.html#turtle.clone
