### ISSUE TITLE
Bitwise operators

### ISSUE THREAD

**Issue by eah13** [skulpt/skulpt#425]
I have a spidey sense that this may be tough to implement but no real knowledge to back that up.

Reports from a user the bit shifting isn't working. Actually, now that she mentions it I recall a student in my UNC class discovering this as well.  https://trinket.io/python/60df47d267 This example is in the context of a fancy fizz buzz solution.  

I imagine most if not all other bitwise operators will need work as well.

I could see wider applicability for trying to bridge intermediate student into an understanding of binary data.

**Comment by indrora** [comment]
woohoo! My bug!

Further minimal example:

```
print True << 1, False << 1, False -1 
```

Expected results: 2 0 -1

Skulpt/Trinket results: 2 1 1

**Comment by waywaaard** [comment]
I had a small look at ```False - 1```. Bool does not inherit from number and therefore, does not have any of the internal operator methods. In ```Sk.abstr.binary_op_``` the LHS-check fails for above mentioned reasons. Then it tries the RHS and switches the arguments and this produces the wrong result as it calculates for this example ```1 - 0```

**Comment by bnmnetp** [comment]
This is fixed by PR #490 currently under review!
