### ISSUE TITLE
Enter/return returns error in interpreter

### ISSUE THREAD

**Issue by blahreport** [skulpt/skulpt#427]
When pressing "Enter" on the keyboard or keypad in the interpreter I expect the following result

\>>>
\>>>

Instead an error is returned

\>>>

        ImportError: No module named repl at <unknown>
        1 : 
\>>>

**Comment by eah13** [comment]
Confirmed.  See #447

**Comment by eah13** [comment]
Depending on your needs, we have a console at http://trinket.io/console than this one, which I think it a little more of a developer tool.
