### ISSUE TITLE
Unpacking doesn't check lengths

### ISSUE THREAD

**Issue by rixner** [skulpt/skulpt#430]
Currently, things are just blindly unpacked.  For example, the following statements do not match the behavior of Python:

```
lst = [1, 2, 3]
a, b = lst
a, b, c, d = lst
a, b = 3
```

I think the issue is in ```Compiler.prototype.ctuplelistorset```.  On a store, I think this should probably inject code that checks the length of the ```data``` argument to see if it matches the number of items on the left hand side.

**Comment by Jacco** [comment]
Even the simplestg problem seems hard to solve in this codebase. Anyway one way of solving it is implemtent sequenceLength in abstract.js. And do the following in compile.js:

    Compiler.prototype.ctuplelistorset = function(e, data, tuporlist) {
        var i;
        var items;
        goog.asserts.assert(tuporlist === "tuple" || tuporlist === "list" || tuporlist === "set");
        if (e.ctx === Store) {
            out("if (Sk.abstr.sequenceLength(" + data +") != " + e.elts.length + ") { throw new Sk.builtin.ValueError('too many values to unpack'); } ");
            for (i = 0; i < e.elts.length; ++i) {
                this.vexpr(e.elts[i], "Sk.abstr.objectGetItem(" + data + "," + i + ")");
            }
        }
        else if (e.ctx === Load || tuporlist === "set") { //because set's can't be assigned to.
            items = [];
            for (i = 0; i < e.elts.length; ++i) {
                items.push(this._gr("elem", this.vexpr(e.elts[i])));
            }
            return this._gr("load" + tuporlist, "new Sk.builtins['", tuporlist, "']([", items, "])");
        }
    };

But it needs some discussion because some sequences might not have the ability to give there length? So it might be better to start iterating using Sk.abstract.iter. If there are too few give "need more than xxx values to unpack" if there are too few give "too many values to unpack".

**Comment by rixner** [comment]
It's also the case that ```data``` might not be a sequence at run-time, so the check has to be a little more complicated than that.  I thought about it for a little bit and then decided to file an issue, because the solution is not obvious.  And you are correct, that you don't necessarily know the length even if it is a "sequence", because ```data``` could be a generator:

```
g = (x for x in range(3))
a, b, c = g
```

I haven't looked at the CPython source to see how they handle unpacking...

**Comment by albertjan** [comment]
:wave: Yeah I wrote that, allthough I don't think CPython does much differently there, since most of compiler.js is a pretty slavish port of the c version.

**Comment by albertjan** [comment]
Well it appears I wasn't as slavish in porting this as I thought :smile:. And I only added set literals. I thought it was this part but it was the list and dict comprehensions part.

CPython does appear to do something special for unpacking. I think it's a good idea to look at that before we change the function. It's a easier to get all the python intricacies right if you look at how they did it.

```c
static int
compiler_list(struct compiler *c, expr_ty e)
{
    int n = asdl_seq_LEN(e->v.List.elts);
    if (e->v.List.ctx == Store) {
        ADDOP_I(c, UNPACK_SEQUENCE, n);
    }
    VISIT_SEQ(c, expr, e->v.List.elts);
    if (e->v.List.ctx == Load) {
        ADDOP_I(c, BUILD_LIST, n);
    }
    return 1;
}

static int
compiler_tuple(struct compiler *c, expr_ty e)
{
    int n = asdl_seq_LEN(e->v.Tuple.elts);
    if (e->v.Tuple.ctx == Store) {
        ADDOP_I(c, UNPACK_SEQUENCE, n);
    }
    VISIT_SEQ(c, expr, e->v.Tuple.elts);
    if (e->v.Tuple.ctx == Load) {
        ADDOP_I(c, BUILD_TUPLE, n);
    }
    return 1;
}
```

There is no way to unpack a set is there?

**Comment by rixner** [comment]
I was about to answer that sets can't be unpacked, but figured I'd try it first.  I am surprised:

```
>>> s = set([1, 2])
>>> a, b = s
>>> a
1
>>> b
2
>>> 
```

It seems that any iterable can be unpacked.

**Comment by Jacco** [comment]
Some checking goes on here in ceval.c

        PREDICTED_WITH_ARG(UNPACK_SEQUENCE);
        TARGET(UNPACK_SEQUENCE) {
            PyObject *seq = POP(), *item, **items;
            if (PyTuple_CheckExact(seq) &&
                PyTuple_GET_SIZE(seq) == oparg) {
                items = ((PyTupleObject *)seq)->ob_item;
                while (oparg--) {
                    item = items[oparg];
                    Py_INCREF(item);
                    PUSH(item);
                }
            } else if (PyList_CheckExact(seq) &&
                       PyList_GET_SIZE(seq) == oparg) {
                items = ((PyListObject *)seq)->ob_item;
                while (oparg--) {
                    item = items[oparg];
                    Py_INCREF(item);
                    PUSH(item);
                }
            } else if (unpack_iterable(seq, oparg, -1,
                                       stack_pointer + oparg)) {
                STACKADJ(oparg);
            } else {
                /* unpack_iterable() raised an exception */
                Py_DECREF(seq);
                goto error;
            }
            Py_DECREF(seq);
            DISPATCH();
        }

**Comment by Jacco** [comment]
The exceptions are thrown in ceval.c:

static int
unpack_iterable(PyObject *v, int argcnt, PyObject **sp)

**Comment by rixner** [comment]
I have also discovered that unpacking in Skulpt does not work with user defined classes that have ```__getitem__``` defined, because the compiler inserts a call to ```Sk.abstr.objectGetItem``` with a javascript number as the index.  It will then properly call ```__getitem__```, but the index is unusable in the Python code because it is not a Python number.  Example code that "should" work even with the current infrastructure, but does not:

```
class Seq:
    def __getitem__(self, i):
        if i >=0 and i < 3:
            return i
        raise IndexError

a, b, c = Seq()
print a, b, c
```

The compiler should really be passing Python numbers as indices, not javascript ones.  It all works because ```Sk.misceval.isIndex``` and ```Sk.misceval.asIndex``` are too forgiving and allow both Python and Javascript types to work.  So, in the builtins, like ```list```, it uses ```asIndex``` to convert a Python index into a Javascript number, which is basically a no-op in this case.  ```isIndex``` and ```asIndex``` should probably just be made to only accept Python values and then we can fix everything that breaks because of that...

I'm just adding this here to document what I've found so it doesn't get lost.

**Comment by rixner** [comment]
I now have a solution that I believe does what CPython does.  However, #469 needs to be resolved to make the case above work (with the ```Seq``` class).  I will make a pull request after some more testing rather than wait for that to be resolved.
