### ISSUE TITLE
Floats can erroneously be used as indices

### ISSUE THREAD

**Issue by rixner** [skulpt/skulpt#440]
Since we have only a single number type, when you check if something can be used as an index, it returns true for all numbers, when it should only be true for integers.  This has consequences in several places.  Here are some examples:

```
num = 1.2
lst = [1, 2, 3]
print lst[num]
print round(123.456, num)
```

**Comment by waywaaard** [comment]
If we can get the inheritance for built-ins working, we could implement the numeric tower of python. As you have already stated the problem lies within the check for  ```tp$index``` in ```Sk.misceval.isIndex```. 

```javascript
Sk.misceval.isIndex = function (o) {
    if (o === null || o.constructor === Sk.builtin.lng || o.tp$index ||
        o === true || o === false) {
        return true;
    }

    return Sk.builtin.checkInt(o);
};
goog.exportSymbol("Sk.misceval.isIndex", Sk.misceval.isIndex);
```

This applies to any number of skulpt currently.

**Comment by rixner** [comment]
Yes, I saw that this is the problem.  I don't particularly like that ```if``` statement regardless, because it is mixing checks for Javascript and Python types.  Looking into things further, I think the entire problem will be fixed if we just remove that ```if``` statement entirely, as I believe ```Sk.builtin.checkInt``` returns true for everything that can be treated as an index and false for everything that cannot.

I agree, though, that it would be nice to have numbers handled correctly, which would be facilitated by inheritance, rather than lumping ints and floats together as one type.

**Comment by Jacco** [comment]
The tp$index is implemented by Sk.builtin.nmber but I don't understand what its role is in respect to Sk.builtin.float.

**Comment by bnmnetp** [comment]
I guess only in Javascript could   ``o === true || o === false`` not always be true.

**Comment by LeszekSwirski** [comment]
@bnmnetp I like to bash Javascript as much as the next guy, but in this case, as a dynamically typed language, it's actually the only sensible thing it could do (other than throwing an exception stating that it's an invalid comparison).

**Comment by waywaaard** [comment]
@Jacco ```tp$index``` map to ```__index__``` special method that allows any classes to implement an index. But I am not sure if there should be a specific order in calling ```__index__```, ```__trunc__``` and ```__int__``` for that. We should have a look at the cpython implementation.

**Comment by rixner** [comment]
@waywaaard I looked at Python and ran some tests, and only ```__index__``` is called.  I believe I have a solution and will make a pull request once I have some tests written.

**Comment by rixner** [comment]
Okay, maybe I won't be making a pull request that quickly.  Trying to use the CPython index tests shows that slices are broken.  Our ```indices``` method is not a proper method of slice objects, so it can't be called from Python.  But, we use it internally in sequences.
