### ISSUE TITLE
dir doesn't handle class hierarchies correctly

### ISSUE THREAD

**Issue by rixner** [skulpt/skulpt#449]
In trying to resolve #440, I am trying to run the CPython index tests.  They use subclassing in the tests.  In our unittest module, we use ```dir``` to find all of the methods, and it is missing a bunch of methods.  The problem is illustrated here with a shorter program:

```
class Base:
    def __init__(self):
        print "init base"
        methods = []
        for name in dir(self):
            methods.append(name)

        print "methods:", methods

    def method1(self):
        pass

class Sub(Base):
    def method2(self):
        pass

sub = Sub()
```

In CPython this prints:

```
init base
methods: ['__doc__', '__init__', '__module__', 'method1', 'method2']
```

In Skulpt, this prints:

```
init base
methods: ['__module__', 'method2']
```

Obviously, ```dir``` doesn't see the base class methods. I thought this was handled by the code that walks through ```tp$mro```.  Is anyone more familiar with how subclassing currently works able to see a quick/easy fix to this?

**Comment by Jacco** [comment]
I think there is a bug in Sk.builtin.dir.

It checks for the MRO on the instance instead of its type.

If an instance is passed ob$type should be used to access the MRO
