### ISSUE TITLE
some Turtle errors not surfacing

### ISSUE THREAD

**Issue by eah13** [skulpt/skulpt#455]
Minimal example (also [here](https://trinket.io/library/trinkets/257774ef0e)):

```python
import turtle

tina = turtle.Turtle()
tina.shape("turtle")

def bad_function():
  # no x and y args - should throw error
  print "fails silently"

tina.onclick(bad_function)
```

More code from a trinket user showing this in action is [here](https://trinket.io/library/trinkets/8d1dfab54a)

The errors end up in the Javascript console.  I think I remember @bzwheeler saying this has something to do with how turtle uses suspensions?  But very hazy on that.

**Comment by bnmnetp** [comment]
This seems to be a general problem with Suspensions.  @meredydd, @LeszekSwirski  I feel like we have had this discussion before, and there is a trick to catching exceptions inside a Suspension.  Maybe it would be better to look into a method for having such an exception propagated up and out somehow?
