### ISSUE TITLE
skulpt bower package not listed anymore.

### ISSUE THREAD

**Issue by albertjan** [skulpt/skulpt#457]
Title says it all. I could add it easily enough but I though it might be better if @bnmnetp has the credentials for it.  

I think It's also a good idea to do a beta release for the latest master. add `-build{buildnr}` to the tag

**Comment by bnmnetp** [comment]
When I do a bower lookup it returns 

```
skulpt git://github.com/skulpt/skulpt-dist.git
```

bower install skulpt successfully installs the latest version from the dist repo in a `bower_components` subdir.

What am I missing?

**Comment by albertjan** [comment]
it has returned :smile: http://bower.io/search/?q=skulpt this returned nothing before. Do you feel we want to tag every commit to the master with a `-build{buildnr}` tag so people can install beta versions of skulpt if they want to? @bzwheeler I know you guys use it, do you have ideas about it?

**Comment by bnmnetp** [comment]
Well,I'm curious to know what others think but to me it seems like a lot of work to tag every commit.  To me, deploying to bower feels like a promise that things are good.  I know from time to time we commit some things that have unexpected consequences.  

If people are actively using the development version of skulpt then I think they can clone the repo and build.

**Comment by albertjan** [comment]
@bnmnetp I can let @travis-ci handle that for us automagically. And he only pushes to the skulpt-dist repo when the build succeeds. It's something akin to a nightly build.
