### ISSUE TITLE
sort(reverse=False) acts as if it is sort(reverse=True)

### ISSUE THREAD

**Issue by csev** [skulpt/skulpt#459]
Run the following code in Skulpt:

x = ['a', 'x', 'm']
x.sort()
print x
x.sort(reverse=True)
print x
x.sort(reverse=False)
print x

The output will be:

['a', 'm', 'x']
['x', 'm', 'a']
['x', 'm', 'a']

The first two are correct - the last one is incorrect.  I am guessing this is an easy fix.  :)

**Comment by albertjan** [comment]
How is it possible! Wow I'll get to it. :smile: there should be a unit test for this. I can't believe this I wrote the timsort stuff two years ago.

**Comment by albertjan** [comment]
There you go :smile: all better now.

**Comment by rixner** [comment]
It seems as if ```sorted``` has a similar problem.

**Comment by albertjan** [comment]
Should I reopen this issue?

**Comment by rixner** [comment]
Yes, I'm going to reopen it.
