### ISSUE TITLE
Need workaround for missing trimLeft() and trimRight() in IE

### ISSUE THREAD

**Issue by csev** [skulpt/skulpt#460]
Skulpt uses trimLeft() and trimRight() in its runtime.  In particular using the python split() function uses trimLeft() and fails on IE as a result.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/TrimRight
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/TrimLeft

This StackOverflow (sort of) covers the issue:

http://stackoverflow.com/questions/2308134/trim-in-javascript-not-working-in-ie

The code I added to my own scripts that workaround this without changing Skulpt are:

```js
if(typeof String.prototype.trimLeft !== 'function') {
    String.prototype.trimLeft = function() {
        return this.replace(/^\s+/,"");
    }
}

if(typeof String.prototype.trimRight !== 'function') {
    String.prototype.trimRight = function() {
        return this.replace(/\s+$/,"");
    }
}
```

I think it would be best if Skulpt came up with a simplar workaround or something else so split() works on IE.

**Comment by albertjan** [comment]
We should run the tests on browsers too. I'll open a new issue about that.

Second thing we should __not__ have used string functions that are not standard and will as it appears never become standard.
