### ISSUE TITLE
Inplace operator does not fall back to normal one

### ISSUE THREAD

**Issue by Jacco** [skulpt/skulpt#465]
Test case:

``` python
class Foo1:
    def __add__(self, other):
        if isinstance(other, Foo2):
            print "OK"

class Foo2:
    def __init__(self):
        pass

x = Foo1()
y = Foo2()

# this goes OK
z = x + y     

# but this gives error
x += y
```

Maybe this is resolved in @waywaaard s complex PR?

**Comment by waywaaard** [comment]
No, I have not fixed this. But it seems that we are going to rework the dunder method handling.

**Comment by bnmnetp** [comment]
Still not working in 0.10.0 but with @mchat's changes this now seems like it could be implemented by adding nb$add and nb$inplace_add implementations to object.

**Comment by waywaaard** [comment]
Any progress here?
