### ISSUE TITLE
itertools permutations

### ISSUE THREAD

**Issue by eah13** [skulpt/skulpt#468]
Planning on working on this with a tight turnaround- hoping to get this deployed for a user by Weds evening ET for an event Thurs AM GMT.  Thought I'd drop an issue in case anyone has an interest in permutations and may be able to get to this before I can (which may be Weds PM).

I found some JS that returns all permutations of any array.  Should be very doable to implement using something like the below, though tests may be tough because I'm not sure the ordering will be the same as Python's.  Haven't dug into the C implementation yet to check- running will probably be easier.

``` javascript
function permutator(inputArr) {
  var results = [];

  function permute(arr, memo) {
    var cur, memo = memo || [];

    for (var i = 0; i < arr.length; i++) {
      cur = arr.splice(i, 1);
      if (arr.length === 0) {
        results.push(memo.concat(cur));
      }
      permute(arr.slice(), memo.concat(cur));
      arr.splice(i, 0, cur[0]);
    }

    return results;
  }

  return permute(inputArr);
}
```

May be time to stub out some of the rest of itertools as well- haven't looked too deeply at it yet.

**Comment by LeszekSwirski** [comment]
Remember to post attribution for that code snippet from StackOverflow, the license requires that you do.

**Comment by eah13** [comment]
Thanks, you're right.  http://stackoverflow.com/a/9960925

**Comment by viebel** [comment]
Is this code was included in Sklupt somehow?
