### ISSUE TITLE
turtle Screen.setup lost its keyword arguments

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#483]
setup should take keyword arguments for width and height.  I believe it did in the past as I'm having reports from teachers that student code that worked in the fall no longer works.

**Comment by eah13** [comment]
This is a pretty clean-cut bug but any chance you have access to that code for testing?

**Comment by bnmnetp** [comment]
Here:

```
import turtle
t = turtle.Turtle()
wn = turtle.Screen()
wn.setup(width=400,height=400)
```

will fail.   `wn.setup(400,400)` will work fine.

Brad
