### ISSUE TITLE
examples in processing home page do not work anymore

### ISSUE THREAD

**Issue by esperanc** [skulpt/skulpt#498]
None of the two examples in 
http://www.skulpt.org/static/proctest.html 
work anymore. They issue an alert box with message 
`TypeError: int() argument must be a string or a number, not '<invalid type>' on line 1`

**Comment by bnmnetp** [comment]
Tracked it down to this line:
```
 mod.WHITESPACE = Sk.builtin.assk$(" \t\n\r\f\u00A0", Sk.builtin.nmber.str);
```

This is not a valid use of ``assk$``

PR coming up.
