### ISSUE TITLE
Build is broken d8 on windows

### ISSUE THREAD

**Issue by waywaaard** [skulpt/skulpt#500]
Latest changes to ```skulpt.py``` have broken the build command on windows:

On platform ```win32``` skulpt.py assumes that the ```d8.exe``` resides in ```support\d8\x32\```. But this is not the case. 

Regards

**Comment by bnmnetp** [comment]
Grrr.  It looks like it is easy enough to work around this in skulpt.py

I checked and travis-ci does not appear to support an automatic windows build.  Does anyone know of another automated build system that integrates with github that would allow us to spin up a virtual windows box and run our tests?

**Comment by albertjan** [comment]
@bnmnetp sure I can try and setup @appveyor for that :+1: good idea.
