### ISSUE TITLE
Modulo doesn't cause an exception in the case of division by zero

### ISSUE THREAD

**Issue by acbart** [skulpt/skulpt#513]
> 5 % 0
    NaN
    > 1 + (5 % 0)
    NaN

In regular python, modulo by zero raises `ZeroDivisionError: integer division or modulo by zero`. However, in Skulpt, it happily computes it to be NaN (an Integer value), which can then be treated like any other integer.

**Comment by waywaaard** [comment]
Correct, there is no check for this case. We should use builtin division (addition) method for the remainder and not javascript modulo.

**Comment by waywaaard** [comment]
This can be closed
