### ISSUE TITLE
Integer division

### ISSUE THREAD

**Issue by ahuhn** [skulpt/skulpt#519]
3//2.0 should be 1.0 in python2 and python3, but it is currently coming out as 1.5 in both.

The fix involves 3 lines of code, but there are a ton of test cases that think 3//2.0 should be 1.5.  Could I get a second pair of eyes?  Thoughts?

It might also have other effects in the code if anyone assumed that they would get true division instead of floor division with //.

```
diff --git a/src/int.js b/src/int.js
index 96b6524..7b07ab5 100644
--- a/src/int.js
+++ b/src/int.js
@@ -332,12 +332,12 @@ Sk.builtin.int_.prototype.nb$floor_divide = function (other) {
 
     if (other instanceof Sk.builtin.lng) {
         thisAsLong = new Sk.builtin.lng(this.v);
-        return thisAsLong.nb$divide(other);
+        return thisAsLong.nb$floor_divide(other);
     }
 
     if (other instanceof Sk.builtin.float_) {
         thisAsFloat = new Sk.builtin.float_(this.v);
-        return thisAsFloat.nb$divide(other);
+        return thisAsFloat.nb$floor_divide(other);
     }
 
     return Sk.builtin.NotImplemented.NotImplemented$;
diff --git a/src/long.js b/src/long.js
index 2447d37..f09c810 100644
--- a/src/long.js
+++ b/src/long.js
@@ -301,7 +301,7 @@ Sk.builtin.lng.prototype.nb$floor_divide = function (other) {
 
     //    Standard, long result mode
     if (other instanceof Sk.builtin.lng) {
-        return other.nb$divide(this);
+        return other.nb$floor_divide(this);
     }
```

**Comment by waywaaard** [comment]
I can confirm the bug. The right behavior would be as @ahuhn described.

Can you please open an PR, then we could better comment on the individual code lines.

**Comment by ahuhn** [comment]
@waywaaard The pull request is at https://github.com/skulpt/skulpt/pull/520.

Thanks for looking into this.

**Comment by waywaaard** [comment]
If you switch the arguments skulpt produces the correct result: `3.0 // 2`
So we could check the arguments and call the right function?

**Comment by ahuhn** [comment]
Right.  I think I fixed it with the pull request.  The issue is in Sk.builtin.int_.prototype.nb$divide and Sk.builtin.int_.prototype.nb$floor_divide .  The parser looks like it should send things properly to nb$divide and nb$floor_divide properly, based on / and //, but it was sending almost everything from nb$divide to nb$floor_divide and expecting nb$floor_divide to figure out the rest of the details.

https://github.com/skulpt/skulpt/pull/520/files is my current fix.

**Comment by waywaaard** [comment]
can be closed

**Comment by ahuhn** [comment]
Yes.  Thanks for your help!
