### ISSUE TITLE
Help with suspensions

### ISSUE THREAD

**Issue by tompreston** [skulpt/skulpt#537]
Hi, not sure if this is the right place to post about this. Maybe someone can point me in the right direction?

I'm trying to write some python functions which do some asynchronous calls (ajax to grab some value from a server). I'd like the Python to wait until the asynchronous call completes and then continue as normal. It sounds like promises/suspensions are the way to do this.

Here's a mock-up of my module which exposes a class (I can't provide an exact copy right now):

    var $builtinmodule = function(name) {
        var mod = {};
        mod.Foo = Sk.misceval.buildClass(mod, function ($gbl, $loc) {
            $loc.__init__ = new Sk.builtin.func(function (self) {
                self.async_handler = new AsyncHandler();
            });
            $loc.get = new Sk.builtin.func(function (self) {
                return self.async_handler.get();
            });
        }, 'Foo', []);
        return mod;
    };

It looks like this in Python:

    import mymodule
    foo = mymodule.Foo()
    print(foo.get())

I hope to have `foo.get()` wait for the server to respond with some value and then continue. The problem is, I'm not sure how to work in suspensions and promises with this as the only docs I can find:

    Example: --------------------------------------------------------------------

    Skulpt provides utility functions for calling Python code that might suspend,
    and returning its result as a Javascript Promise. (For browsers that do not
    support Promises natively, Skulpt embeds the "es6-promises" poly-fill.)

    Here is some Javascript code that calls a Python function that might suspend,
    then logs its return value to the console:

        Sk.misceval.callsimAsync(null, pyFunction).then(function success(r) {
            console.log("Function returned: " + r.v);

        }, function failure(e) {
            console.log("Function threw an exception: " + e);
        });

What is `pyFunction`?

**Comment by bnmnetp** [comment]
Tom,

You may want to take a look at image.js in src/lib  I think the way I used suspensions in there is similar to what you want to do.

Once you are done it would be great to put what you have learned into the urllib module.  See src/lib/urllib/request/__init__.js

Brad

**Comment by tompreston** [comment]
I figured it out. Here's how it's done:

    var $builtinmodule = function(name) {
        var mod = {};
        mod.Foo = Sk.misceval.buildClass(mod, function ($gbl, $loc) {
            $loc.__init__ = new Sk.builtin.func(function (self) {
                self.async_handler = new AsyncHandler();
            });

            // This is the Python get method which may suspend the Python program.
            // It returns an Sk.misceval.Suspension
            $loc.get = new Sk.builtin.func(function (self) {
                var susp = new Sk.misceval.Suspension();
                // susp.resume is called on the Promise's resolve() - you must return a Skulpt type
                susp.resume = function (result) {
                    if (susp.data["error"]) {
                        throw new Sk.builtin.IOError(susp.data["error"].message);
                    } else {
                        return new Sk.builtin.int_(result);
                    }
                }
                // This is where you point to the blocking call
                // self.async_handler.get() returns a Promise
                susp.data = {
                    type: "Sk.promise",
                    promise: self.async_handler.get()
                };
                return susp;
            });

        }, 'Foo', []);
        return mod;
    };


For reference here is the `get` method inside AsyncHandler:

    var AsyncHandler = function() {};

    AsyncHandler.prototype.get = function() {
        return new Promise(function (resolve, reject) {
            $.get(some_url, function (result) {
                resolve(result.value);
            }).error(function (result) {
                reject(result);
            });
        });
    };

I hope that helps someone.
