### ISSUE TITLE
Broken link on readme

### ISSUE THREAD

**Issue by dawsonbotsford** [skulpt/skulpt#539]
The link titled "some turtle graphics examples" is broken

Line 5 of readme:
"
Try out [some turtle graphics examples](http://interactivepython.org/courselib/static/thinkcspy/PythonTurtle/helloturtle.html) to see Skulpt in action.
"

**Comment by albertjan** [comment]
Thanks! @bnmnetp should I change that to: http://interactivepython.org/runestone/static/thinkcspy/toc.html#python-turtle-graphics
