### ISSUE TITLE
Importing simple python file into project

### ISSUE THREAD

**Issue by Daltron** [skulpt/skulpt#554]
I am using the example on the Sculpt website (https://gist.github.com/bnmnetp/4650616). What I am wanting to do is import a simple Python class I can use, in this case Person.py 

I have already looked at #381 and am aware of the builtinRead(fileName) function but am not sure where to call it? 

If somebody could show me a step by step example, it would be greatly appreciated.

**Comment by waywaaard** [comment]
It's a late response, but what you can do the following:

```javascript
var myCustomFiles = {'Person.py', 'print "hello"\nprint "test"'};

function builtinRead(x) {
    if (myCustomFiles[x] !== undefined) {
        return myCustomfiles[x];
    }

    if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined)
            throw "File not found: '" + x + "'";
    return Sk.builtinFiles["files"][x];
}
```

**Comment by alexwenbj** [comment]
@ebertmi Hi,Michael,I custom my skulpt as you show:
`

var myCustomFiles = {'Person.py': 'print "hello"'};
--
  | window.builtinRead = builtinRead;
  | function builtinRead(x) {
  | if (myCustomFiles[x] !== undefined) {
  | return myCustomfiles[x];
  | }
  | if (Sk.builtinFiles === undefined \|\| Sk.builtinFiles["files"][x] === undefined)
  | throw "File not found: '" + x + "'";
  | return Sk.builtinFiles["files"][x];
  | }
`
but when I run the Python code:
`f = open("Person.py")`
It show me an error:
ExternalError: ReferenceError: myCustomfiles is not defined on line 1
Would you please tell me what is the problem?Thank you in advance.
