### ISSUE TITLE
Package.json and npm changes

### ISSUE THREAD

**Issue by matheuspoleza** [skulpt/skulpt#558]
There some things that we can change with `npm`. They are:
### 1 - Dependencies x dev-dependencies
- [ ]  The dependencies that is in package.json are not `dependencies` of the project. Its use only for development. So, no make sence. 
  ![selection_376](https://cloud.githubusercontent.com/assets/8049914/14316589/37ba6978-fbda-11e5-937c-52c7841742d3.png)
### 2 - Don't need a global install of `jscs jshint jsdoc`
- [ ] Change it to only `npm install`
  ![selection_378](https://cloud.githubusercontent.com/assets/8049914/14316747/1f3746a4-fbdb-11e5-898b-1e8f9fcfd732.png)
### 3 - It can use more npm scripts
- [ ] Why `./skulpt.py dist` is not a npm script? We can centralize all in package.json scripts and run `npm build` or something like that.

**Comment by albertjan** [comment]
Sounds like a plan if you ask me 😄 when I added this I didn't completely understand how npm worked.
