### ISSUE TITLE
`skulpt.py dist` does not generate skulpt.min.js

### ISSUE THREAD

**Issue by TastyCatFood** [skulpt/skulpt#565]
Followed the instruction and failed.

test() is returning a non-zero value.
test() does not provide info on which test is failing.

When if block after test is commented out.
        
        . Compressing...
        sh: 1: java: not found
        closure-compiler failed.

after `sudo apt-get install default-jre `, I succeeded in generating the file.
Happened on ubuntu LTS14

**Comment by bnmnetp** [comment]
Sometimes the test that fails is at the top of the run and has scrolled off the screen.  Most likely you do not have one of the javascript linters installed.

**Comment by TastyCatFood** [comment]
`which` command prints:

    d@d-s5530jp:~$ which jscs
    /usr/bin/jscs
    d@d-s5530jp:~$ which jshint
    /usr/bin/jshint
    d@d-s5530jp:~$ which jsdoc
    /usr/bin/jsdoc
 
I compiled the repo as is without making any modification.  

Thought I should report:
+  Compile time requirements may not be identified definitively  
+  `test()` provides information less than ideal under some conditions

Nothing that important though, anyone can read python and tests can be skipped or modified. Just an extra work.
