### ISSUE TITLE
something in import broke

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#583]
OK, So this was working great until I discovered today that broke sometime in the last several months.

```
from unittest.gui import TestCaseGui
```
This used to work just fine, now I get the error:  ``ImportError: No module named unittest.gui.TestCaseGui``

Anyone with any ideas on when or how this broke it would be much appreciated.

Brad

**Comment by waywaaard** [comment]
I know there was a Problem with that but I thought I fixed it. The import tests are running for those dotted paths. 

I am currently on holidays, so I can't have a look at it until next week.

**Comment by bnmnetp** [comment]
@waywaaard   I can't find anywhere in unittests where we systematically  test import statements of different varieties.   But, just trying things out, in the following, the first four lines work and the last 3 fail.  Hopefully you can take a look at what broke.   I think I mentioned elsewhere that it was commit 2e989e50206753beb13bd69890be60dbc7797bcc

```
import urllib
import urllib.request
import unittest
from unittest import TestCase
from urllib.request import urlopen
from urllib.request import Response
from unittest.gui import TestCaseGui
```

**Comment by waywaaard** [comment]
Okay, I think I know what the problem is. The newly introduced code tries to determine if a module is not present in the other module and then tries to load the module from the file. But, if we load an element from a module inside a module it breaks.
