### ISSUE TITLE
Possibility of Using Alternative Servers

### ISSUE THREAD

**Issue by aminrasekh** [skulpt/skulpt#585]
Is it possible to use a different server than Google in Skulp? For example, a personal AWS EC2 instance with a running WSGI. Skulpt uses Google services for the server side. Unfortunately, such services to users in certain regions of the world is blocked by Google.
There exist, nevertheless, millions of kids and teens in those regions whose access to Skulpt and learning coding can make a difference for them. 
This matter has come to my attention after few kids reached out to me that they cannot access Skulpt and any platform based on that like Trinket (Error 403) and I want to help them.

**Comment by waywaaard** [comment]
Skulpt is not a server-based tool. You can upload/deploy the library/webapp where you want to.

**Comment by eah13** [comment]
@aminrasekh you might check to see if the children's school internet is filtered. Sometimes all it takes to fix this is getting the domain(s) whitelisted by an IT admin. To my knowledge neither Skulpt or trinket is filtered at the country level.  We see plenty of traffic from China, for instance.

**Comment by aminrasekh** [comment]
Thanks much @waywaaard . My impression was that there is a web server running (persumably provided by Google) that interpret the python scripts entered in Skulpt. Then, where does this interpretation take place in Skulpt? I doubt if it uses a local interpreter.

**Comment by aminrasekh** [comment]
@eah13 . Thanks a lot. I asked few of them and a couple replied they cannot not access from anywhere (school and home). They live in Iran where certain Google services are blocked by Google there. That's why I suspected that is the problem and thought that I can spin up an EC2 cluster to replace the presumably Google web server would solve their problem. One of them actually shared the the screenshot with me:
![423728850_90252](https://cloud.githubusercontent.com/assets/7544189/16029796/b5526c9a-31b9-11e6-95e1-710a8955c62e.jpg)

**Comment by rixner** [comment]
@aminrasekh, the whole point of Skulpt is that it interprets the Python right in your browser.  Once you have a Skulpt-based site open in your web browser, it does not need to communicate with any server to run Python code.  I can't speak to whether or why Skulpt.org or Trinket or any other Skulpt-based site is blocked.  But, as @waywaaard said, you can just deploy Skulpt on your own anywhere.  Since the Python interpretation takes place in the user's browser, you just need a place to host static content.

**Comment by aminrasekh** [comment]
@rixner Than you so much. It was very informative and now I well understood how Skulpt works.
So I went ahead and found another project that is based on Skulpt:
http://interactivepython.org/runestone/static/thinkcspy/index.html
Already got confirmation from the kids that it is available and works for them. So we incorporate Skulpt-based learning modules in a website that is not blocked for them and they should be good to go. 
Thanks everyone!
