### ISSUE TITLE
Name conflicts with suspensions

### ISSUE THREAD

**Issue by rixner** [skulpt/skulpt#591]
Currently, there are several internal variable names that are being used that don't have $'s in them.  This leads to name conflicts when you have Python variables of the same name.  This is a problem in particular with ```$saveSuspension```.  Take, for example, the following program:

```
def f():
    child = 1
    filename = "abc"
    lineno = 2
    colno = 3
    normal = 5

    print child, filename, lineno, colno, normal

f()
```

If you use "skulpt.py run" to run this program, it will print the correct values.  If you suspend, though, using "skulpt.py rundebug" you get the wrong results.  I don't know how many other names are problematic, but I don't think these four (child, filename, lineno, and colno) are the only problems.  The solution is probably "easy", in that all these internal names just need to be prefixed with a $ to become $child, $filename, etc...  There are just potentially a lot of places which need to be fixed.

**Comment by meredydd** [comment]
Another candidate: `isSuspension` should become `$isSuspension`.
