### ISSUE TITLE
import PyPDF2 

### ISSUE THREAD

**Issue by chunyenHuang** [skulpt/skulpt#596]
Hello Skulpt team,
I want to run [PyPDF2](https://github.com/mstamy2/PyPDF2) with Skulpt on the frontend. 
Skulpt can find the module in src/lib but it shows  
`TypeError: Cannot read property 'length' of undefined`
or error code 
`ParseError: bad token`

I am new to Python, I am really sorry if this is a stupid question. Please guide me!

**Comment by waywaaard** [comment]
Skulpt is a reimplementation of Python/CPython in JavaScript. It still misses a couple of features and standard modules/libs and therefore skulpt is not capable of supporting such libaries.

**Comment by chunyenHuang** [comment]
Thanks for answering my question!
