### ISSUE TITLE
is it possible to use any python library or any python module with skulpt ?

### ISSUE THREAD

**Issue by yspanchal** [skulpt/skulpt#60]
Hi, 
Is it possible to use any python library or module with skulpt ?

For example sys module...

Import sys
Print sys.version

Something like this.

**Comment by gg4u** [comment]
interested in networkx. any support? it'd be very powerful. and tensorflow support.

**Comment by waywaaard** [comment]
@gg4u To be honest, this is not possible with skulpt and I guess will never be. Despite the performance issues, skulpt does not (and maybe will never)  provide full Python-support. You can try and add it, but there will be many errors.

Especially, that skulpt does not support the `__all__ = [...]` exports.

**Comment by Felucho** [comment]
Any recent news about Python library in Skulpt? Thanks
