### ISSUE TITLE
Python Import Module

### ISSUE THREAD

**Issue by dihego** [skulpt/skulpt#601]
Hello,

I am in the attempt to import python module Exscript. So far all modules have been working out for me except this one. 
The module is available in my system and I can execute the same script thru CLI but not thru skulpt. 

Any thoughts...

**Comment by waywaaard** [comment]
Hi,

skulpt is a Python Interpreter written in JavaScript and purely web-based. Therefore, a lot of complex standard libs/modules are missing. 

This is the difference between your local python installation and skulpt and why exscript does not work.
