### ISSUE TITLE
Scaling canvas/turtle size 

### ISSUE THREAD

**Issue by anderoonies** [skulpt/skulpt#617]
Is it possible to scale the turtle?
`Sk.TurtleGraphics.width = 100; Sk.TurtleGraphics.height = 100;`
changes the dimensions of the canvas, but the movements and turtle don't scale.

**Comment by waywaaard** [comment]
Have you tried: https://docs.python.org/2/library/turtle.html#turtle.screensize
and https://docs.python.org/2/library/turtle.html#turtle.setworldcoordinates

I think, though I am not 100% sure, that there is no scaling parameter of the turtle.

**Comment by anderoonies** [comment]
those are helpful, thanks
i might redefine the move methods to be scaled by the canvas size.

**Comment by anderoonies** [comment]
Our workaround was to add an abstraction layer over the underlying commands that performs the scale
