### ISSUE TITLE
lshift of 0 should not become long

### ISSUE THREAD

**Issue by OPiMedia** [skulpt/skulpt#620]
```Python
type(0 << 1)  # is <type 'long'>, but must be <type 'int'>
```

Bug found by Sergey Korytnik, with CodeSkulptor
[http://www.codeskulptor.org/#user41_7649LLA6bW_1.py](http://www.codeskulptor.org/#user41_7649LLA6bW_1.py)

EDIT: In fact there are the same error with `a << 0`.
And _maybe_ the general test `tmp <= this.v` is completely wrong!
I don't understand why "overflow" in JavaScript may decide when the promotion to `long` is correct in Python.

**Comment by albertjan** [comment]
This has been fixed. Thanks @OPiMedia for pointing it out.
