### ISSUE TITLE
No prompt displayed for input and raw_input

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#623]
I just got a bug report on this from users of my books.   I don't know when this happened, but it looks like a few things have changed.  Sk.inputfun looks like it is no longer setable  but more importantly, the prompt for input and raw_input has disappeared.

I need to get this back asap.  @albertjan it looks like you were the last person working on input and raw input.  Any advice on how to get this working again??

**Comment by waywaaard** [comment]
You need to set the `inputfun` inside the `Sk.configure()` call. If it is not set it defaults to the browser prompt. https://github.com/skulpt/skulpt/blob/master/src/env.js#L184

**Comment by bnmnetp** [comment]
Right, but the default browser prompt is no longer showing the text of the prompt.

**Comment by albertjan** [comment]
checking :smile:

**Comment by waywaaard** [comment]
Though, it should. See https://github.com/skulpt/skulpt/blob/master/src/file.js#L130

**Comment by albertjan** [comment]
@bnmnetp When I did the refactor to emulate stdin and stdout, I rerouted the prompt to write to stdout . I'll see if I can make this a setting.

**Comment by bnmnetp** [comment]
Looking at line 129 in file.js

```
        var prompt = prompt ? prompt.v : "";
        x = Sk.inputfun(prompt);
```

I think prompt is guaranteed to be "" all the time as there is no prompt parameter or variable set in the readline function.

**Comment by waywaaard** [comment]
No, actually this line can be removed.

In  `builtin.js` we have now:

```javascript
Sk.builtin.raw_input = function (prompt) {
    var sys = Sk.importModule("sys");
    if (prompt) {
        Sk.misceval.callsimOrSuspend(sys["$d"]["stdout"]["write"], sys["$d"]["stdout"], new Sk.builtin.str(prompt));
    }
    return Sk.misceval.callsimOrSuspend(sys["$d"]["stdin"]["readline"], sys["$d"]["stdin"]);
};
```

**Comment by albertjan** [comment]
Yes you are right that was copied from our earlier implementation. I will attempt to correct this asap. @waywaaard that has changed in skulpts master. The calls are chained there.

**Comment by waywaaard** [comment]
Even if they are chained, it should not make any difference. Still, should output the prompt on stdout.

**Comment by albertjan** [comment]
Well no because we write the prompt to stdout, and the inputfun takes a string argument. that isn't written too.

**Comment by bnmnetp** [comment]
The prompt is being displayed on stdout but that is in the browser main window, which is grayed out when the prompt dialog appears.  This is really confusing for beginning students as their attention is on the input dialog, not the main window.

It seems to me that calling Sk.inputfun in file.readline is actually a bit too late.  We used to check right at the beginning of raw_input I thought.

**Comment by albertjan** [comment]
@bnmnetp got it, working on a solution for this, I never thought about the `query` function. If you emulate a tty in a browser, it works as it should 😄.

**Comment by bnmnetp** [comment]
Thanks @albertjan

**Comment by babybigfox** [comment]
@bnmnetp @waywaaard @albertjan @sgraham @orionz Has this change been pushed to skulpt-dist yet?

**Comment by albertjan** [comment]
@babybigfox please don't randomly tag people, everybody gets enough email already, no need to bother people that haven't signed up to this. 

Every successful build on master, will result in a push to skulpt-dist. As you can see here: https://github.com/skulpt/skulpt-dist/commit/6429b6e11bcb982d34b9facc46ace59a9b6c2270 it's been pushed.

You'll have to specify your input function takes a prompt though in you `Sk.configure` call, you'll have to set `inputfunTakesPrompt` to true.

**Comment by babybigfox** [comment]
Sorry about tagging all those people. I have copied the skulpt.min.js and skulpt-stdlib.js new files to my server and they are still not displaying the prompt. I am new to JavaScript and Github. Can you give me some code that does what you said: "You'll have to specify your input function takes a prompt though in you Sk.configure call, you'll have to set inputfunTakesPrompt to true." in the format of skulpt.min.js and skulpt-stdlib.js. Thanks so much for helping I really appreciate it!


________________________________

**Comment by albertjan** [comment]
Somethink like this:

```js
Sk.configure({
  inputfun: function(str) {
    return window.prompt(str); 
  },
  inputfunTakesPrompt: true
});
```

You'll probably want to specify a `outf` and a `read` there aswel but thats in the examples on the homepage.

**Comment by babybigfox** [comment]
I have copied your code to the js, but the dialog box is still not showing? Please can you help?


My editor I am making with Skulpt and CodeMirror is at this url: http://ckdata.neocities.org/python-coding-area.html


Here is the code for that page:


<!DOCTYPE html>
<html>

<head>

    <script src="jquery.min.js" type="text/javascript">
    </script>
    <script src="skulpt-lib.min.js" type="text/javascript">
    </script>
    <script src="skulpt-stdlib.js" type="text/javascript">
    </script>
    <script src="editor-py.js" type="text/javascript">
    </script>
    <script src="codemirror.js" type="text/javascript">
    </script>
    <script src="python.js" type="text/javascript">
    </script>
    <link href="codemirror.css" rel="stylesheet" type="text/css">
    <title>Python Coding Area</title>
</head>

<body>
    <textarea id="textbox" name="textbox"># Put your Python code in this box, and when you are ready hit the "Run" button.</textarea>
    <br>
    <button onclick="runit()" type="button">Run</button>
    <pre id="dynamicframe"></pre>
    <div id="canvas"></div>
</body>

</html>

and here are some links to js / css files I used:
http://ckdata.neocities.org/jquery.min.js
http://ckdata.neocities.org/skulpt-lib.min.js
http://ckdata.neocities.org/skulpt-stdlib.js
http://ckdata.neocities.org/editor-py.js
http://ckdata.neocities.org/codemirror.js
http://ckdata.neocities.org/python.js
http://ckdata.neocities.org/codemirror.css

What would I need to change in any of these files to make input() work?

Thanks again
________________________________
