### ISSUE TITLE
Cannot use time module ("performance" not defined)

### ISSUE THREAD

**Issue by qxcv** [skulpt/skulpt#625]
I've received a few second-hand reports of a Skulpt-based application failing with `ExternalError: ReferenceError: Can't find variable: performance on line 50`. This doesn't occur on new versions of Firefox (e.g. 48) or Chrome (e.g. 51), but it sounds like it does occur on some older (unknown) versions of Safari, and possibly also some versions of Internet Explorer.

I suspect the problem is that those browsers don't support `window.performance`, and Skulpt is dying when it tries to use it. In `time.js`, there are a few checks along the lines of

``` js
if (performance && performance.now) {
}
```

which should probably be

``` js
if (window.performance && window.performance.now) {
}
```

**Comment by albertjan** [comment]
I think we should check wether or not performance is available. According to http://caniuse.com/#feat=nav-timing give or take 90% of browsers support it. So if they don't support it adding `window.` doesn't help.

**Comment by qxcv** [comment]
That's why I suggested the  `if (window.performance && ...) {...}` check. If `performance` is not supported then `window.performance` should (?) evaluate to `undefined`, so the code that follows will never be executed. Is there some reason why that idiom won't work here?

**Comment by albertjan** [comment]
Right sorry it was still quite early 😄.

**Comment by waywaaard** [comment]
I just want to not that your check will fail, if any test case uses this function. Better check if performance is available on the `this` object. We are using v8 to run the tests etc. and there is no window object.
