### ISSUE TITLE
Building Skulpt

### ISSUE THREAD

**Issue by SimonTsehaye** [skulpt/skulpt#626]
Hi!
I am trying to build ./skulpt.py dist for the first time. I followed all instructions but i got an error in cmd as follows:
```
C:\>skulpt_1\skulpt.py dist
Traceback (most recent call last):
  File "C:\skulpt_1\skulpt.py", line 53, in <module>
    PRODUCT_NAME    = bowerProperty("name")
  File "C:\skulpt_1\skulpt.py", line 40, in bowerProperty
    file = open(bowerFileName())
  File "C:\skulpt_1\skulpt.py", line 33, in bowerFileName
    file = open(".bowerrc")
IOError: [Errno 2] No such file or directory: '.bowerrc
```'
How could I fix this?

**Comment by albertjan** [comment]
Hi :) you should run it _in_ the directory. Try:

```
cd skulpt_1
./skulpt.py dist
```

Make sure you have java installed and in your `PATH`

**Comment by SimonTsehaye** [comment]
Thanks a lot @albertjan !!! It's fixed now i just need to update my python interpreter to use gitpython for the dist command:) thanks:)

**Comment by SimonTsehaye** [comment]
Hi @albertjan 
I ran into another problem now after installing gitpython. I got this new error:
```
c:\skulpt>.\skulpt.py dist
Traceback (most recent call last):
  File "C:\skulpt\skulpt.py", line 1371, in <module>
    main()
  File "C:\skulpt\skulpt.py", line 1292, in main
    dist(options)
  File "C:\skulpt\skulpt.py", line 696, in dist
    if not isClean():
  File "C:\skulpt\skulpt.py", line 150, in isClean
    repo = Repo(".")
  File "C:\Python27\lib\site-packages\git\repo\base.py", line 171, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: c:\skulpt
```
Does this have to do with wrong installation of my system packages such as gitpython or...?

**Comment by albertjan** [comment]
is git in your path and is `c:\skulpt` a git repository? I think it does a 'git status' on your repository. It tries to look for a `.git` dir in the skulpt directory

**Comment by SimonTsehaye** [comment]
I installed gitpython using pip and was successful; and c:\skulpt is just a skulpt dir. I double checked git in my path and it is there. Is there a way to correct the git status that it is doing in the skulpt directory or it is best if i re-install my packages and try again? ... @albertjan
