### ISSUE TITLE
How to add error to output

### ISSUE THREAD

**Issue by metulburr** [skulpt/skulpt#633]
i know about adding this as an alert

```
        try{
            return Sk.importMainWithBody("<stdin>", false, prog, true);
        }
        catch(e){
            alert(e.toString())
        }
```

but i want it to display where the output is printed instead within the page. How can I do this?

**Comment by bnmnetp** [comment]
Sure.  The error information is right there in e.toString()   What you do with it is a "simple matter of coding" ™️   I don't know anything about your application, but what I would do is have a ``div`` in my html with an id that I could figure out or was known in advance, and then use Javascript to add and  format the error message inside the ``div``.

**Comment by metulburr** [comment]
I kind of hacked my way at it. I dont know javascript so i just put something together from googling. I did end up getting it to work. 

```
        try{
            return Sk.importMainWithBody("<stdin>", false, prog, true);
        }
        catch(e){
            var error_text = document.createTextNode(e.toString());
            var spanHeader = document.createElement('span');
            spanHeader.style.color = "red";
            spanHeader.appendChild(error_text);
            var divHeader = document.getElementById('output');
            divHeader.appendChild(spanHeader);
        }

```
