### ISSUE TITLE
input() dialog box not showing message

### ISSUE THREAD

**Issue by babybigfox** [skulpt/skulpt#639]
I am using the skulpt versions below:
http://www.skulpt.org/static/skulpt.min.js & http://www.skulpt.org/static/skulpt-stdlib.js

And when I add input("Hi there!") to the textarea and hit run, the dialog box does not display a message above the text box.

Can you give me links to skulpt.min.js & skulpt-stdlib.js that work with input().

Thanks

**Comment by bnmnetp** [comment]
You should not use those versions of skulpt.  Please clone the repository and run the ``skulpt.py dist`` command to build your own.

**Comment by babybigfox** [comment]
I don't know how to use GitHub command line, only the website. Is it possible to do on the website?

**Comment by amr66** [comment]
don't know what happend to babybigfox, but i found out, input() works, if i use the versions from http://www.skulpt.org/static/dist/skulpt-latest.zip. Downloaded from github https://codeload.github.com/skulpt/skulpt-dist/zip/master, input() throws an type error. Unfortunately i can not build it on my own, as i am under windows and building dist fails - due to system/path problems.

**Comment by eah13** [comment]
Hmm. As a workaround, you can likely find another [skulpt-dist tag](https://github.com/skulpt/skulpt-dist/releases) where input() does work while we track this down.  It's working fine on trinket still but we override the default so haven't noticed any problems here

**Comment by babybigfox** [comment]
@amr66 @eah13 the dialog box comes up but the text inside the two brackets in the function does not appear above the text box as it should do. Can you give me links to skulpt.min.js and skulpt-stdlib.js that work with input()? Thanks

**Comment by albertjan** [comment]
can you paste your `Sk.configure` here?

**Comment by amr66** [comment]
in my runit() function this is used:

    Sk.configure({output:outf, read:builtinRead});

and buildinRead is:

    function builtinRead(x) {
        if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined)
            throw "File not found: '" + x + "'";
        return Sk.builtinFiles["files"][x];
    }

**Comment by albertjan** [comment]
@amr66 are you and @babybigfox working on the same thing? or do you both have the same problem 😕

**Comment by amr66** [comment]
no, i think we have a similar problem.

**Comment by albertjan** [comment]
So get the latest version from the [skulpt-dist](https://github.com/skulpt/skulpt-dist) repo, there was an issue with the input fun. And your `Sk.configure` should look something like this: 

```js
Sk.configure({
    inputfun: function (prompt) {
        return window.prompt(prompt);
    },
    inputfunTakesPrompt: true,
    output: outf,
    read: builtinRead
});
```

**Comment by amr66** [comment]
It works! No error and i have a "promt title" in the window! Thanks!
I try to run the interactive example, too. But there i have a complete different function for running code and a different Sk.configue (there are two!). Can i easiely adapt it there? Tried, but still have a type error:
   
    ExternalError: TypeError: a is undefined on line 1
    1>: evaluationresult = input("hi")
    2 : if not evaluationresult == None: print repr(evaluationresult)

**Comment by amr66** [comment]
Thanks to @albertjan i figured out, how to get input() in repl.js, which is the basis for the interactive python example on skulpt.org:

    Sk.configure({
         inputfun: function (prompt) {
             return window.prompt(prompt);
         },
         inputfunTakesPrompt: true,
         output: function(str) {
            //strip out line-feeds
            if (str.replace(/\n/g, "") !== "") {
                repl.print(str);
            }
         },
         read: function (x) {
             if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined) {
                 throw "File not found: '" + x + "'";
             }
             return Sk.builtinFiles["files"][x];
        },
	retainglobals: true
    });

**Comment by albertjan** [comment]
Ah yeah but make sure you only use `retainglobals` for the repl.

**Comment by albertjan** [comment]
@babybigfox I hope this helps for you too, let us know 😄

**Comment by amr66** [comment]
Yes, only in repl.js, i just inserted it there - works like a charm! Thanks!!

**Comment by babybigfox** [comment]
@amr66 @bnmnetp @eah13 @albertjan So the version that now works is updated here: http://www.skulpt.org/static/dist/skulpt-latest.zip?

**Comment by albertjan** [comment]
Nope :) but you can download it here: https://github.com/skulpt/skulpt-dist/archive/master.zip

**Comment by amr66** [comment]
shouldn't this issue be closed?

**Comment by albertjan** [comment]
Lets wait for @babybigfox to get back to us.

**Comment by babybigfox** [comment]
@bnmnetp @amr66 @eah13 @albertjan This is still not working for me. Can one of you make a demo repository with all the html and js code needed to use this updated version of skulpt, including an example? That would be of great help, thanks

**Comment by amr66** [comment]
you can find it here: https://github.com/amr66/skulpt_example
Hope it helps!

**Comment by albertjan** [comment]
@amr66 thats awesome 😄 @babybigfox I hope that helps.

**Comment by babybigfox** [comment]
@amr66 that's great and it works (yay!), would it be possible for you to update that repro so that on the 'skulpt.html' example, there is CodeMirror in it, like in the interactive mode? That would be great, thanks :)

**Comment by albertjan** [comment]
@babybigfox code mirror is not that difficult to get working. Have you tried it yourself?

**Comment by babybigfox** [comment]
@albertjan Yes I have and if I use this updated version with it the input box doesn't work (again), I would just like someone who knows what they are doing to help, that's all

**Comment by bnmnetp** [comment]
@babybigfox You would be hard pressed to find someone who knows more about skulpt than @albertjan .  Perhaps its time for you to dig in and learn the hard stuff yourself.

**Comment by babybigfox** [comment]
@bnmnetp I know that @albertjan knows alot, but I also know that @amr66 knows alot about CodeMirror too, I was just asking. I have tried to learn it myself but the documentation on skulpt is not very comprehensive. I have asked stackoverflow to help but they don't give a damn about skulpt or codemirror.

**Comment by albertjan** [comment]
@babybigfox It never hurts to ask, but if you ask why something doesn't work, and we can see what you've tried it's much easier to help you. You'll see you'll get a lot more help when you do that instead of asking "can you please do this or that for me". This goes for stackoverflow too. 😄

**Comment by babybigfox** [comment]
@albertjan oh ok, so what do you recommend that will teach me the ins and outs of skulpt and codemirror

**Comment by albertjan** [comment]
Set out to do something for example add codemirror to the example you have.
Try to get it to work by googling and reading stuff. When you run into
something you cant find the answer to you can ask here or on stackoverflow.
You'll be able to ask a much narrower question then. :).

**Comment by amr66** [comment]
Ups, why do you think i know anything about codemirror, @babybigfox? Last week i didn't know anything about skulpt. Seeing its possibilities for my own teaching gets me going. Codemirror would be fine, and there are sources to put this together, if i only have the time to do it... and i would share, do you too? You are invited!

**Comment by babybigfox** [comment]
I have left a comment on skulpt_example in the issues section
