### ISSUE TITLE
repl.js and interactive example error

### ISSUE THREAD

**Issue by amr66** [skulpt/skulpt#640]
while trying to use the interaktive (repl.js-based) example from skulpt.org, i encountered an error with the python syntax assiging with += operator. If i do 
    
    a=1
    a+=1

it fails:

    ParseError: bad input on line 1
    1>: evaluationresult = a+=1
    2 : if not evaluationresult == None: print repr(evaluationresult)

because this is possible in editor, i htink this can be really an error in repl.js?

**Comment by albertjan** [comment]
ah yeah :) thats because of the "regex" I don't know if you're really good with regex you should be able to add that to here: https://github.com/skulpt/skulpt/blob/master/repl/repl.js#L24

basically we need to diff between stuff that returns things and stuff that makes new things

**Comment by amr66** [comment]
uuiii, ok....
may be this is correct? (works, with little testing):

    assignment = /^((\s*\(\s*(\s*((\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w* \s*\)\s*))\s*)|(\s*\(\s*(\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w*\s*\)\s*))\s*,)*\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w*\s*\)\s*))\s*\)\s*))\s*,)*\s*((\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w*\s*\)\s*))\s*)|(\s*\(\s*(\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w*\s*\)\s*))\s*,)*\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w*\s*\)\s*))\s*\)\s*))\s*\)\s*)|(\s*\s*(\s*((\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w*\s*\)\s*))\s*)|(\s*\(\s*(\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w*\s*\)\s*))\s*,)*\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w*\s*\)\s*))\s*\)\s*))\s*,)*\s*((\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w*\s*\)\s*))\s*)|(\s*\(\s*(\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w*\s*\)\s*))\s*,)*\s*((\s*[_a-zA-Z]\w*\s*)|(\s*\(\s*(\s*[_a-zA-Z]\w*\s*,)*\s*[_a-zA-Z]\w*\s*\)\s*))\s*\)\s*))\s*\s*))[+-/\*]?=/;

so i added just [+-/\*]? in front of "="

    ))[+-/\*]?=/ 

don't know if this has side effects...

**Comment by waywaaard** [comment]
If we change this, then we should add all of them. Feel free to open a PR.

@albertjan Do we have any tests for the regex?

**Comment by amr66** [comment]
i don't know how to deal with the double ones: // >> << **

**Comment by albertjan** [comment]
@waywaaard no we don't 😁 To be honest it wasn't me who made the original regex it was @eltjo-k. The regex force is not that strong with me. 

if this addition works lets add this first we can always move forward in small steps.

**Comment by amr66** [comment]
started a PR, but i think there are some more versions of repl.js, i changed the one in repl directory, but i found another in doc/static - actually this is the version i used in my project... Change them too or is there another mechanism?

**Comment by albertjan** [comment]
@amr66 see comment on your PR 😄

**Comment by amr66** [comment]
the one in docs in not a simple doublet, but the assignment part is the same of course.

**Comment by amr66** [comment]
closing this one - thanks for helping!
