### ISSUE TITLE
Skulpt.min.js missing from docs folder

### ISSUE THREAD

**Issue by upMKuhn** [skulpt/skulpt#648]
Hi I just downloaded skulpt and tried to run the examples, but the skulpt.js file is missing from the static folder. Can someone commit the file or update the examples to use the hosted version from skulpt.org next time someone makes a commit?

Thanks,
Martin

**Comment by albertjan** [comment]
https://github.com/skulpt/skulpt-dist/releases you can download the released version of skulpt here. Those files are created during the build they are an artefact of the code and therefore not in the repository. Here is the current master: https://github.com/skulpt/skulpt-dist/archive/master.zip
