### ISSUE TITLE
How to include user submited modules?

### ISSUE THREAD

**Issue by Darker** [skulpt/skulpt#651]
Hello.
I wanted to allow user to submit files from their computer as modules. The reason for this is that I'm trying to run Python AI competition without obligating users to reveal their code.

What I tried was to create my own file dictionary:
```
var FILES = {};
```

When user submitted a file, I'd parse it and add to dictionary:
```
FILES[theFile.name] = Sk.importMainWithBody("<stdin>", false, FILE_TEXT);
```
I found no documentation for skulpt, so I just guessed `importMainWithBody` converts python to js. After that, I've changed the function for reading files:
```
function builtinRead(x) {
	// Uploaded overrides built it
	if(typeof FILES[x]!="undefined")
	    return FILES[x];
	// built in modules
    if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined)
        throw "File not found: '" + x + "'";
    return Sk.builtinFiles["files"][x];
}
```
This didn't work at all, the `importMainWithBody` complained about missing modules. When I moved the compilation process to `builtinRead` it didn't work either, it simply acted like the files didn't exist:
```
function builtinRead(x) {
	// Uploaded overrides built it
	if(typeof FILES[x]!="undefined")
	    return return Sk.importMainWithBody("<stdin>", false, FILES[x]);
```
How can I do this?

**Comment by albertjan** [comment]
`FILES[theFile.name] = Sk.importMainWithBody("<stdin>", false, FILE_TEXT);`

turn that line into:

`FILES[theFile.name] = FILE_TEXT;`

that should help you on your way.

I don't know if skulpt is gonna be fast enough for AI stuff. 😄
