### ISSUE TITLE
Console log messages in turtle.js

### ISSUE THREAD

**Issue by masterkni666** [skulpt/skulpt#652]
In the clone function, there are console messages that print out arrays.
   I am unsure if this is intended but it creates a lot clutter.         

            console.log(this._undoBuffer);
            newTurtleInstance.instance._undoBuffer = this._undoBuffer;
            console.log(newTurtleInstance.instance._undoBuffer);

**Comment by albertjan** [comment]
I'd merge a PR that removes those 😄.
