### ISSUE TITLE
Display error messages

### ISSUE THREAD

**Issue by aminrasekh** [skulpt/skulpt#655]
Does Skulpt return and display programming error messages?
I purposefully altered a demo codes in the Skulpt's front page to see if it does and I do not see the error messages displayed anywhere.

**Comment by waywaaard** [comment]
It does, but you have to write your own displaying logic in order to show it to the user. Here is simple example:

```javascript
var code = "print(\"hi\")\n"
var pr = Sk.misceval.asyncToPromise(function() {
  return Sk.importMainWithBody("<stdin>", false, code, true);
});

pr.then(function () {
  console.log("Finished running the programm");
}, function (err) {
  console.info('errorHandler', err);
  // do something with the Python/Skulpt errror here
  var msg = err.toString();
});
```

In order to display an stracktrace you need some more logic (copied a snippet from my code):

```javascript
    let ret = err.toString(); // Simple output message

    // Create stacktrace message
    if (err.traceback) {
      for (let i = 0; i < err.traceback.length; i++) {
        ret += "\n  at " + err.traceback[i].filename + " line " + err.traceback[i].lineno;
        if ("colno" in err.traceback[i]) {
          ret += " column " + err.traceback[i].colno;
        }
      }
    }
```

**Comment by waywaaard** [comment]
@aminrasekh Can we close this issue?

**Comment by aminrasekh** [comment]
Yes, yes. Thanks a lot @waywaaard ! It helped us get it work. Skulpt is the core of an open education platform we have for kids and teenagers. Thank you so much folks for doing this!
Before I close the issue, may I suggest this feature is also presented somewhere in the Skulpt homepage? So everyone will know of its availability.
