### ISSUE TITLE
Default arguments do not work with external libraries

### ISSUE THREAD

**Issue by ahyattdev** [skulpt/skulpt#667]
This is the `__init__.js` of `mymodule`, which is loaded through the external libraries feature. 
```
var $builtinmodule = function (name) {
    
    'use strict';
    
    var mod = {};
    
    mod.cotest = new Sk.builtin.func(function(just, a, b, c) {
        console.log(a, b, c);
    });
    
    mod.cotest.co_varnames = ['a', 'b', 'c'];
    mod.cotest.co_numargs = 4;
    mod.cotest.$defaults = [3, 2, 1];
    
    return mod;
};
```
At runtime, `undefined undefined undefined` is printed to the JS console. `3 2 1` should be printed.

**Comment by waywaaard** [comment]
I think, your function arguments `just, a, b, c` must match with the the `co_varnames` and the `$defaults`.
And you should use Skulpt/Python Values for the defaults:

```javascript
mod.cotest..$defaults = [Sk.builtin.none.none$, new Sk.builtin.int_(1), new Sk.builtin.int_(2), new Sk.builtin.int_(3)];
mod.cotest.co_numargs = 4;
mod.cotest..co_varnames = ['just', 'a', 'b', 'c'];
```

**Comment by ahyattdev** [comment]
@waywaaard `just` is the required argument. Only `a`, `b`, and `c` should have default values. 

```
Sk.builtin.sorted = function sorted (iterable, cmp, key, reverse) { ... }

// Sk.builtin.sorted
Sk.builtin.sorted.co_varnames = ["cmp", "key", "reverse"];
Sk.builtin.sorted.co_numargs = 4;
Sk.builtin.sorted.$defaults = [Sk.builtin.none.none$, Sk.builtin.none.none$, Sk.builtin.bool.false$];
```

This is how default arguments are used for `sorted`

**Comment by waywaaard** [comment]
I posted the output that is generated by skulpt itself:
```python
def cotest(just, a=1, b=2, c=3):
    return just*a*b*c
```

Produces the following function definition (without the body):
```javascript
                    $scope129.co_name = new Sk.builtins['str']('cotest');
                    $scope129.$defaults = [new Sk.builtin.int_(1), new Sk.builtin.int_(2), new Sk.builtin.int_(3)];
                    $scope129.co_varnames = ['just', 'a', 'b', 'c'];
                    var $funcobj134 = new Sk.builtins['function']($scope129,$gbl);
                    $loc.cotest = $funcobj134;
```

**Comment by albertjan** [comment]
@ahyattdev what @waywaaard said is exactly correct you only specify the defaults for arguments that have defaults in the order of the arguments. If there are arguments that don't have defaults they always go first. 

You should be able to find out whats going by compiling an example and adding a `debugger` statement. 😄
