### ISSUE TITLE
How do you make a function of a class a property from JavaScript?

### ISSUE THREAD

**Issue by ahyattdev** [skulpt/skulpt#668]
This is the kind of thing I want to use in JS for a module I am making. 

```
class Foo(object):
    def __init__(self):
        pass

    @property
    def bar(self):
        return 42
```

It should be access by `mymod.Foo().bar`

```
$loc.bar = new Sk.builtin.func(
    function (self) {
        return 42;
    }
);
// How to make this a property?
```

**Comment by albertjan** [comment]
I would suggest looking at what skulpt produces for your example. That will give you an idea of what to do. 

Also you'll need to return a skulpt type from your function: `return Sk.ffi.remapToPy(42);`

**Comment by ahyattdev** [comment]
What is the best way to see what the Python "compiles" to?

**Comment by albertjan** [comment]
Add a `debugger` statement to your code. Your browser's development environment will stop in the skulpt code and you can inspect what it looks like. Like this:

```py
class Foo(object):
    def __init__(self):
        debugger
        pass

    @property
    def bar(self):
        return 42
```

And you can also run this: `./skulpt.py run prop.py` where your code is in prop.py. The resulting code will be written to the standard out.

**Comment by ahyattdev** [comment]
This is what `@property` does at runtime:
```
                        //
                        // line 8:
                        //     @property
                        //     ^
                        //
                        $currLineNo = 8;
                        $currColNo = 4;
                        var $loadname127 = $loc.property !== undefined ? $loc.property : Sk.misceval.loadname('property', $gbl);
                        ;$scope128.co_name = new Sk.builtins['str']('bar');
                        $scope128.$decorators = [$loadname127];
                        $scope128.co_varnames = ['self'];
                        $ret = Sk.misceval.callsimOrSuspend($scope128.$decorators[0], new Sk.builtins['function']($scope128,$gbl));
                        if ($ret && $ret.$isSuspension) {
                            $ret = Sk.misceval.retryOptionalSuspensionOrThrow($ret);
                        }
                        var $funcobj130 = $ret;
                        $loc.bar = $funcobj130;

```
`$loadname127` turned out to be `Sk.builtins.property`. 
```
        $loc.bar = new Sk.builtin.func(
            function (self) {
                return Sk.ffi.remapToPy(42);
            }
        );
        $loc.bar.$decorators = [Sk.builtins.property];
```
I tried setting that decorator, but it has no effect.

**Comment by albertjan** [comment]
you forgot: $ret = Sk.misceval.callsimOrSuspend($scope128.$decorators[0], new Sk.builtins['function']($scope128,$gbl));

**Comment by petroleyum** [comment]
I was wanting to do this same thing and this post got me started in the right direction so I'll add what I did to make a property work here in case someone else is wondering the same thing.

If you are already building a class in javascript and you are adding a method you would do what @ahyattdev did in the original post:
`$loc.bar = new Sk.builtin.func(function (self) {return 42;});`
(except that 42 should be wrapped in a python number type)

But for properties the function needs to instead take the form:
`$loc.bar = Sk.misceval.callsimOrSuspend(Sk.builtins.property, getter, setter);`
where `getter` and `setter` are also Sk functions.

A complete example with the setter and getter function looks something like this:
```
var getter = new Sk.builtins['function'](function(self){
        console.log('inside getter function');
        // return something from self, or some value like this int:
        return Sk.builtin.assk$(123, Sk.builtin.nmber.int$);
        }
        //,$loc  // internally skulpt has a $loc or $gbl argument here. We don't seem to need it
);

var setter = new Sk.builtins['function'](function(self, val){
        console.log('inside setter function');
        console.log(val);
        // Do something with val and self
        }
);
$loc.bar = Sk.misceval.callsimOrSuspend(Sk.builtins.property, getter, setter);
```
(note that `Sk.builtins.property` comes from `/src/property.py`, which is useful to look at for this)

I haven't extensively tested this, and I'm not sure if this is the recommended format, but it has been working for me so far. It also may be possible/better to return a suspension from the getter and setter to allow for debugging types of things.

**Comment by zyctinker** [comment]
> I was wanting to do this same thing and this post got me started in the right direction so I'll add what I did to make a property work here in case someone else is wondering the same thing.
> 
> If you are already building a class in javascript and you are adding a method you would do what @ahyattdev did in the original post:
> `$loc.bar = new Sk.builtin.func(function (self) {return 42;});`
> (except that 42 should be wrapped in a python number type)
> 
> But for properties the function needs to instead take the form:
> `$loc.bar = Sk.misceval.callsimOrSuspend(Sk.builtins.property, getter, setter);`
> where `getter` and `setter` are also Sk functions.
> 
> A complete example with the setter and getter function looks something like this:
> 
> ```
> var getter = new Sk.builtins['function'](function(self){
>         console.log('inside getter function');
>         // return something from self, or some value like this int:
>         return Sk.builtin.assk$(123, Sk.builtin.nmber.int$);
>     }
> );
> 
> var setter = new Sk.builtins['function'](function(self, val){
>         console.log('inside setter function');
>         console.log(val);
>         // Do something with val and self
>     }
> );
> $loc.bar = Sk.misceval.callsimOrSuspend(Sk.builtins.property, getter, setter);
> ```
> (note that `Sk.builtins.property` comes from `/src/property.py`, which is useful to look at for this)
> 
> I haven't extensively tested this, and I'm not sure if this is the recommended format, but it has been working for me so far. It also may be possible/better to return a suspension from the getter and setter to allow for debugging types of things.

One more questions, what should I do if I want add a staticmethod property for a method of a class?
Thx

**Comment by ahyattdev** [comment]
Thanks you all for the responses. Closing as I have not needed this for a long time.
