### ISSUE TITLE
How do I use modules?

### ISSUE THREAD

**Issue by jmbaron** [skulpt/skulpt#675]
I want numpy to be available. How do I implement it?

**Comment by waywaaard** [comment]
Partial implementation can be found here:
https://github.com/waywaaard/skulpt_numpy
https://github.com/waywaaard/skulpt_matplotlib

You can use those modules with the external module configuration.

**Comment by jmbaron** [comment]
I get an error when using the following code

```
 Sk.externalLibraries = {
            numpy : {
                path: 'https://github.com/waywaaard/skulpt_numpy'
            }
        };
```

Here's the error

`ImportError: Invalid file extension specified for numpy on line 1`

**Comment by waywaaard** [comment]
`Sk.externalLibaries` expects to be pointed to a specific file. Download/Clone the repository and configure your skulpt to use the the files under dist.
