### ISSUE TITLE
A request that put skulpt in our own server

### ISSUE THREAD

**Issue by MatrixLeadInternship** [skulpt/skulpt#681]
Hello,

We recently built a website and we want to use https CDNs to call the skulpt.min.js and skulpt-stdlib.js but failed (the same problem as one of the other issue mentioned). Therefore can we put necessary files in our own server so that we can use `<script src='https://website/skulpt.min.js></script> ` to call those files?

Best regards

**Comment by eah13** [comment]
Sure! That's how most of us are using Skulpt.

You can build the files yourself or get them from https://github.com/skulpt/skulpt-dist and upload them to the CDN or server of your choice.  Yay for open source & open licenses.
