### ISSUE TITLE
`with` statement throws an error

### ISSUE THREAD

**Issue by finaiized** [skulpt/skulpt#682]
I've been trying to use `with` such as in the below example:

```
with open('file.csv') as csv:
  print(csv)
```

This gives me the following error:
```
Uncaught (in promise) TypeError: Cannot read property 'constructor' of undefined
    at SymbolTable.visitExpr (skulpt.min.js:905)
    at SymbolTable.visitStmt (skulpt.min.js:904)
    at Object.Sk.symboltable (skulpt.min.js:916)
    at Object.Sk.compile (skulpt.min.js:1005)
    at Object.Sk.importModuleInternal_ (skulpt.min.js:1015)
    at demo.html:284
    at skulpt.min.js:271
    at Promise (<anonymous>)
    at Object.Sk.misceval.asyncToPromise (skulpt.min.js:270)
    at demo.html:283
```
I am dynamically evaluating the Python code using the same code as given on the Skulpt homepage. I am using the version of Skulpt on master (compiled with `npm run build`). Note that it works when I separate it out into the equivalent statements, e.g.

```
a = open('file.csv')
print(a)
a.close()
```

I can't tell if this is just unsupported or if I'm doing something wrong. Any help is appreciated!

**Comment by waywaaard** [comment]
The with keyword is currently unsupported, but there is a good chance that @merrydd is going to implement it

**Comment by eah13** [comment]
#696 should fix this when merged
