### ISSUE TITLE
Skulpt CDNs works in Safari but not work in Chrome

### ISSUE THREAD

**Issue by MatrixLeadInternship** [skulpt/skulpt#690]
Hello,

I used the CDNs of Skulpt.min.js [https://raw.githubusercontent.com/skulpt/skulpt-dist/0.11.0/skulpt.js](url) that one of you gave me several days ago to run a python in javascript function with plunker. Here's the plunker link:[https://plnkr.co/edit/93BU7m0A5qGJlosD8QQX?p=preview](url)

Then I found this function worked with Safari but when I tried it with Chrome, the console said that Sk is not defined. 

Is there any problem with my codes?

Thanks in advance!

**Comment by albertjan** [comment]
@MatrixLeadInternship you shouldn't use github as a cdn, because it really isn't it also doesn't provide the correct headers and that's probably what causes chrome not to interpret the javascript. If you want to run these in production somewhere you'll have to upload it somewhere. 👍 Good luck.

**Comment by j-f1** [comment]
You can also try RawGit: https://cdn.rawgit.com/skulpt/skulpt-dist/0.11.0/skulpt.js

**Comment by albertjan** [comment]
Oh hehe I didn't know about that one. But yeah that would definitely work. We should add a link to those on the website!

**Comment by j-f1** [comment]
@albertjan Is the website open-source?

**Comment by MatrixLeadInternship** [comment]
Thanks a lot! That works

**Comment by albertjan** [comment]
@j-f1 yeah it is it's in this repository under `doc/static`
