### ISSUE TITLE
errors are misleading  sometimes - fallback to "native" python (or pypyjs)

### ISSUE THREAD

**Issue by dz0** [skulpt/skulpt#699]
I don't remember the actual case right now... I deal with turtle mostly... 
and sometimes it reports totaly wrong (probably because of skulpt implementation way)
Would it be possible to have button - "Check with naitive Python" or so?

**Comment by albertjan** [comment]
@dz0 That seems to me very difficult to realise since we don't have native python in the browser :). I  would however encourage you to report any oddities and discrepancies in a ticket so we can fix them or throw not implemented errors.

**Comment by dz0** [comment]
But if you use py3 serverside, maybe possible to check syntax at least serverside.

**Comment by rixner** [comment]
There is nothing running on any server.  That is the whole point of Skulpt.  It is served statically and run entirely in the browser.  As @albertjan said, if you find incorrect/misleading errors, please report the specific problems so that they can be fixed.

**Comment by dz0** [comment]
Silly me! Sorry, I confused skulpt with Trinket..
