### ISSUE TITLE
spoofing re.compile

### ISSUE THREAD

**Issue by PaulReiber** [skulpt/skulpt#705]
Had a short chat with Elliott Hauser, who recommended I share this idea with the community.

The support for "re" is somewhat broken right now - specifically re.compile doesn't exist.

Elliot's solution, which I think is a great idea, would be to spoof re.compile - i.e. delivering no runtime performance optimization whatsoever, but it wouldn't break code that calls .compile either.

Please feel free to contact me if you have questions about the idea.

**Comment by eah13** [comment]
+1. Actual compilation may be a possibility as well but short of that, supporting the re API with correct output and no errors seems like a win.

**Comment by j-f1** [comment]
You could also have a wrapper around the JS `RegExp` object that you return from `re.compile`.

**Comment by rixner** [comment]
```re``` is not broken.  It's implementation is incomplete.  That's not the same thing.

**Comment by PaulReiber** [comment]
The noun phrase of the sentence was **support for "re"** 

My apologies that I wasn't clearer - I'm speaking of support for the standard python "re" being broken, not the incomplete skupt implementation of "re" being broken.

**Comment by rixner** [comment]
I did not misunderstand you.  By your logic, pretty much all of Skulpt is "broken", as very little is 100% complete.  While that might be a laudable goal, it is not a practical expectation given the nature of the project.

Regardless, it is not clear what your objective is here.  Are you asking if we would be receptive to you implementing such a thing?  Are you hoping someone else will do it?  Something else?

**Comment by PaulReiber** [comment]
Scott Rixner - I am certain you have indeed misunderstood.  You would not
have asked me follow-on questions, nor extrapolated my intentions, if you
had understood.

PLEASE Scott - please personally do nothing about this issue, if you are so
inclined.   If you do not feel compelled to help, please do nothing at
all.  Thank you.

 - - -

Dear willingly helpful Skulpt developers/maintainers:

I was asked by Elliot, who's maintaining the Skulpt fork "trinket.io", to
post this improvement idea here on the Skulpt github project.

The idea is very straightforward - instead of failing when encountering a
call to re.compile (a method very commonly used in python code using "re")
the method could be spoofed or maybe actually implemented.

Elliot's words seem pertinent to reiterate here: "supporting the re API
with correct output and no errors seems like a win."

Please consider extending Skulpt's "re" implementation to continue to
function, rather than failing, when encountering a call to re.compile

Thank you!   I will be happy to put any implementations of the above
through some real-world testing if that would be helpful.

Kind regards,
-Paul R

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by rixner** [comment]
@PaulReiber I am not sure why you are so upset by my comments.  Skulpt is the result of a lot of hard work by a lot of people.  I simply took issue with the word "broken", and nothing else.  You seem to be taking my comments as some sort of personal attack, which they most definitely are not.

In general, features get implemented as and when there is a demand for them.  Usually, they get implemented by the person or persons who want that feature.  If none of the current contributors is interested in this feature, you are always welcome to create a pull request with such an implementation.

I will remain silent on this issue hereafter, as requested.

**Comment by eah13** [comment]
@PaulReiber many thanks for your contribution to the community! End user input on what features are most useful in the wild is always welcome.

This will be working its way up Trinket's list but if anyone else would like to take a stab in the meantime, go for it.  Should be relatively straightforward and a good learning opportunity.

**Comment by PaulReiber** [comment]
Hi Elliott,

Thanks for your kind follow-up.  I'm hopeful that this will indeed someday
be implemented.

@ScottRixner I took your Coursera class a couple years back to bone up on
Python.  You're good.  You're smart. You're respected in the community.

However, right here, right now, you were flat-out wrong in how you dealt
with this matter.  Please, just admit it.
-> I proposed an idea
-> Elliot +1'd the idea
-> Jed mentioned details of how it might be implemented
-> Then you derailed the discussion with your personal opinion about the
word "broken".

Seeing a negative comment from someone whose opinions matter quite a lot in
the community is disheartening.
It's especially disheartening since nit-picking like that is not
constructive or helpful to the resolution of the issue itself.
Some developers could easily have mistaken your words to imply that the
idea being discussed doesn't have merit.

Lastly, in your follow-up you made an incorrect assumption, which needs to
be corrected:  I was never upset by your comments.

Dismayed, yes. Additionally motivated, yes.  But not upset.

Kind regards,
-Paul R

**Comment by bnmnetp** [comment]
I would suggest that we move on. In the 7 years that I've been maintainer for skulpt we've been very lucky in the Skulpt community that we haven't had much of this kind of negative back and forth.

@PaulReiber, @rixner and his students have contributed tons to this project over the years,  Good, high quality code, and thoughtful reviews of others. In fact, git blame shows that Rixner has implemented the majority of whats in re.js right now.  My memory is that DrChuck wrote the first very slim version, and we've improved it over the years.

I will say, that as the maintainer of this and the RunestoneInteractive project I have to bite my tongue more often than not when a newcomer makes an issue in a snarky or critical way, and lets face it we all have good and bad days when we hear things farther up or down the scale of snark.  Saying something is 'broken' is definitely a hot-button for me.  I don't think that demanding admissions of wrongness is a productive direction to take the conversation.

I'm +1 on the idea of getting a better version of re.compile added to the stdlib.  So lets focus on how we might make that happen and put the rest to rest.

**Comment by PaulReiber** [comment]
There was zero snark intended in my post.  I don't work that way - never have, never will.  My mission in life is helping people, and when I undertake things like this it's with that mission in mind.

If it happened to me... I wonder how many dozens of other people were similarly lumped into the snarky/critical category.  I'm +1 for slightly thicker skins here, and "embracing the suck".  Words like broken, borked, fubar... they're just words, don't let them own you.

Anyways...  thank you for the +1 

Do you think Skulpt needs an actual re-compiling-implementation of .compile for performance reasons, or would just spoofing re.compile for API completeness be the right strategy?

**Comment by eah13** [comment]
> Do you think Skulpt needs an actual re-compiling-implementation of .compile for performance reasons, or would just spoofing re.compile for API completeness be the right strategy?

This was the main topic for discussion on this issue in my mind and no one (yet) has raised an objection, so am assuming this is the right approach. I was able to quickly get some of the major `RegexObject` methods working last nite and will add some tests and open a PR. Hopefully tonite. 

We're still missing `re.sub` as a function and I didnt get to that method in this first pass. I just stripped out the JS of the implemented functions so re's functions and my new methods could share that logic, with `RegexObject` passing in the relevant parameters from `self` on each call. No perf boost, just syntax support.

Aside: Brad's right that we should keep github discussions cordial and focused on code. If anyone has any lingering confusion or concerns, let's take that offline. Elliott@trinket.io. Regardless, let's keep it positive and assume good intentions!

**Comment by bnmnetp** [comment]
Thanks Elliott, I look forward to seeing the PR.  

I think wrapping the RegExp object is a perfectly fine way to go and keeps things consistent with the current implementation.  Beginners, especially, are not likely to wade into any syntax differences between JS and Python. (I hope) -- 

When done, I'll encourage David to update his [Regex Tutorial](http://evc-cit.info/comsc020/python-regex-tutorial/#) to include the new functionality.
