### ISSUE TITLE
execLimit not triggering on large xrange loops

### ISSUE THREAD

**Issue by AWice** [skulpt/skulpt#711]
With `Sk.configure.execLimit = 200`, writing code like

```python
for x in xrange(1000):
    for y in xrange(1000):
        z = 2
```
times out as expected, and
```python
while True:
    z = 2
```
also times out.

But code like
```python
for x in xrange(1000000):
    z = 2
```
doesn't seem to timeout before 1 second.  Is there something I am missing?

**Comment by albertjan** [comment]
Thanks for your bug report, the problem is that `xrange` is the same as `range` in skulpt a javascript function that is called outside of the statemachine that skulpt generates to run python code. Only if you loop through the state machine will the `execLimit` be checked.
