### ISSUE TITLE
time.mktime is broken when run on certain days

### ISSUE THREAD

**Issue by daviesian** [skulpt/skulpt#713]
The [implementation of `time.mktime`](https://github.com/skulpt/skulpt/blob/master/src/lib/time.js#L196) uses a rather odd mechanism to generate a JS `Date` object from a time tuple. First it calls `new Date()` which generates a `Date` representing the **current** time, then it progressively sets the year, month, day, etc. on that object.

That would be fine, except [the specification](http://www.ecma-international.org/ecma-262/6.0/#sec-date.prototype.setmonth) for [`Date.setMonth()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMonth) says that if `date` (`dayValue`) is not specified (which it isn't), then the current day is used. If the current day is greater than the number of days in the required month, this causes the month to increment, which is absolutely not what we want.

This only happens if `mktime` is run on certain days - e.g. if the current day is `31` and we call `mktime` on a time tuple for September (which only has 30 days), the timestamp returned is in October.

NB: This also affects `time.strftime()` and hence `datetime.datetime.strftime()`.

There is a trivial fix - use [the standard `Date` constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) directly:
```
var d = new Date(year, month, day, hour, minute, second);
```

**Comment by ebertmi** [comment]
nice catch
