### ISSUE TITLE
Implementing Skulpt server-side.

### ISSUE THREAD

**Issue by murtyjones** [skulpt/skulpt#715]
I'm looking to provide a backend service that allows a user to execute python code remotely. Obviously this is a huge security risk, and as a result I'm looking at using an emulator like Skulpt instead of trying to sandbox a fully powered Python.

Just curious if anyone has seen Skulpt used outside of a client context or if there are any examples of this floating around.

**Comment by bnmnetp** [comment]
Check out pythontutor.com . -- It uses regular python in a sandboxed environment by using a whitelist of modules, and other strategies to keep things secure.

I'm not aware of skulpt being used outside of the browser as a back end.

**Comment by ebertmi** [comment]
This depends on the use case, bute Skulpt has multiple references to browser objects like window for e.g. drawing turtles. Additionally, I do not understand the advantage of running it server side, when it can be run on the client without the need for roundtrip times.

Maybe you can shed some light on your specific use case. Skulpt has only limited support for the Python language and its module, which might not be suited for executing a broad range of code remotely.

**Comment by murtyjones** [comment]
Thanks for the input. Sounds like Skulpt may not be ideal for implementing what I'm envisioning. I'll go ahead and close this out.

**Comment by albertjan** [comment]
Oh I do think @meredydd runs skulpt on his servers to parse the code. But I would go for docker to run python securely on a server.

**Comment by meredydd** [comment]
(Background - I run [Anvil](https://anvil.works), a service for building full-stack Web apps in Python. This means we run user-supplied Python code both in the browser and on our servers.) 

Actually, all our parsing (for autocompletion etc)  runs in the browser as part of the IDE. All our server side code runs in PyPy or CPython.

We use a layered approach (sandboxing/docker inside VMs), which is what I'd recommend to you as well.

You might also want to look into the PyPy sandbox. None of the Cayton "sandboxing" systems are at all safe, but PyPy's sandbox is pretty darn robust. If you use that and enable seccomp in the sandbox subprocess, I'd say that's an excellent starting point for you. (I'd still put it all in a VM on its own to segregate it from your systems, but that's really belt and braces.) 

Hope that's helpful :)

**Comment by ebertmi** [comment]
I am also running any programming language in a secure sandbox based on lxc and cgroup limits and BTRFS for filesystem limits.

You can have a look at https://github.com/ebertmi/sourcebox-sandbox

**Comment by murtyjones** [comment]
Those are helpful suggestions. Thank you!

**Comment by murtyjones** [comment]
Here's the approach I'm taking (Docker + [sandboxed PyPy](http://doc.pypy.org/en/latest/sandbox.html)), for any looking for similar functionality: https://github.com/murtyjones/docker-pypy-sandbox
