### ISSUE TITLE
"from turtle import *" doesn't work

### ISSUE THREAD

**Issue by saulcosta18** [skulpt/skulpt#716]
The following code will break on the Skulpt demo page (and in developer implementations):

```python
from turtle import *

bob = Turtle()
bob.forward(50)
done()
```

It looks like [this issue was fixed years ago](https://github.com/skulpt/skulpt/issues/287), so maybe a regression has been introduced?

**Comment by albertjan** [comment]
Hey @saulcosta18 which version did you try?

**Comment by saulcosta18** [comment]
@albertjan sorry, looks like it's working now. Was trying a few different versions and must have had an old one cached.

**Comment by albertjan** [comment]
No worries glad you got it to work.
