### ISSUE TITLE
Networking modules

### ISSUE THREAD

**Issue by 100buHtiG** [skulpt/skulpt#727]
I was wondering if modules like ftplib, paramiko( or another ssh module if it's easier), telnetlib would be possible to implement?

**Comment by j-f1** [comment]
Unfortunately, browser JavaScript is only capable of single HTTP requests (`XMLHTTPRequest`) or `WebSocket` connections. There’s no access to a raw network interface, so it isn’t possible to do SSH, FTP or telnet without a server-side component.

**Comment by 100buHtiG** [comment]
Okay. Thank you for the quick reply.  Is it at all possible to implement AES or RSA encryption standards?

**Comment by j-f1** [comment]
Probably, as long as there’s a JS implementation. However, the implementation might be too large to include in Skulpt by default.

**Comment by albertjan** [comment]
Yeah that would require a separate project. 👍
