### ISSUE TITLE
python 2/3 unicode string issue.

### ISSUE THREAD

**Issue by albertjan** [skulpt/skulpt#731]
Via: https://news.ycombinator.com/reply?id=15592896&goto=item%3Fid%3D15591947%2315592896

Isn't the biggest difference between Python 2 and 3 and handling of Unicode? That's what motivated the break in compatibility in the first place.
But in Skulpt the strings don't quite work like any of the Python versions.
Python 2 has a combined str/bytes type and a separate Unicode string type:
```
  >>> type("hello") is type(u"你好")
  False
  >>> len(u"你好")
  2
  >>> len("你好")
  6
```
...whereas in Python 3 the str type is Unicode and the "bytes" type is a completely separate thing:
```
  >>> type("hello") is type(u"你好")
  True
  >>> len(u"你好")
  2
  >>> len("你好")
  2
```
Skulpt actually seems to work more like Python 3, except that 1) there is no way at all to work with bytes (that I can find), e.g. no encode/decode methods, and it 2) requires the "u" prefix if literals contain non-ASCII characters, even though the type of the resulting string is the same as without the prefix:
```
  >>> type("hello") is type(u"你好")
  True
  >>> len(u"你好")
  2
  >>> len("你好")
  SyntaxError: invalid string (possibly contains a unicode character) on line 1
```

**Comment by wizofaus** [comment]
So is there a plan to add support for a "Bytes" type to Skulpt?

**Comment by gxhc520** [comment]
竟然还没解决。。。

**Comment by albertjan** [comment]
bytes has been implemented on master @s-cork I assume this works now?

**Comment by s-cork** [comment]
what's the question?

**Comment by gxhc520** [comment]
@s-cork 
 
>>> type("hello") is type(u"你好")
  True
  >>> len(u"你好")
  2
  >>> len("你好")
  SyntaxError: invalid string (possibly contains a unicode character) on line 1

print and len does not work well with unicode charater.
how to solve it?

**Comment by s-cork** [comment]
yes - this was fixed with the bytes prs and unicode support...
just double checked and on master 
```python
>>> len("你好")
2
```

**Comment by gxhc520** [comment]
@s-cork but it not work in web editor

**Comment by gxhc520** [comment]
`print(len("你好"))`

in console of browser:
`SyntaxError: invalid string (possibly contains a unicode character) on line 7`

**Comment by s-cork** [comment]
That's true - but the web editor is not running the latest version of skulpt. If you're using the latest version in your own project it should work.

@albertjan @bnmnetp is there a way to auto update the web editor at skulpt.org to run the latest version?
