### ISSUE TITLE
how to write a file with skulpt, just like trinket does?

### ISSUE THREAD

**Issue by macomzzl** [skulpt/skulpt#741]
I wonder how I can write a file (like a txt file) with skulpt? I have wondered for a long time, could anyone give me a example?

**Comment by ebertmi** [comment]
@macomzzl This is possible. However, it requires some custom logic to handle the file creation, deletion and modifications in the browser. You need to implement those operations based on the different modes yourself.

You need to configure skulpt with an `fileopen `method. You can see an example impl. here:

* https://github.com/ebertmi/webbox/blob/master/common/models/project/skulptRunner.js#L245
* https://github.com/ebertmi/webbox/blob/master/common/models/project/skulptRunner.js#L82
* https://github.com/ebertmi/webbox/blob/master/common/models/project/skulptRunner.js#L65

Additionally, you need to add the fileopen callback in the file impl. like this:

* https://github.com/ebertmi/skulpt/blob/epy_build/src/file.js#L7

**Comment by alexwenbj** [comment]
@ebertmi Hi,Is there a file library like numpy/pygal which can be assemblied easily with Sk.externalLibraries?Thank you.
