### ISSUE TITLE
Can skulpt safely run untrusted code?

### ISSUE THREAD

**Issue by x13machine** [skulpt/skulpt#745]
It also needs to stop the script if it takes too long to run. I was thinking I could use web workers for that.

**Comment by albertjan** [comment]
I don't know of any ways to execute javascript without it going through the api: `jseval`.

https://github.com/skulpt/skulpt/blob/master/src/builtin.js#L864-L866

If you want to run un trusted code you should remove this probably. But a seasoned pen tester will probably be able to find some way into javascript from skulpt.

**Comment by x13machine** [comment]
Maybe I could have an iframe run a webworker which would run skulpt. I know there's a way to make webworkers at least somewhat safe.

**Comment by albertjan** [comment]
An Iframe would be sufficient I would say. Since most of the skulpt code will be interruptible using suspensions. I’ll dig up an example of that somewhere this week.

________________________________

**Comment by x13machine** [comment]
Is there a setTimeout equivalent in skulpt?
Is there a way to get numpy and scipy working with skulpt?

**Comment by x13machine** [comment]
Also how would I disable tests when I run the build script?
