### ISSUE TITLE
Request to add codetheblocks.com to list of "Skulpt in the Wild" projects

### ISSUE THREAD

**Issue by chhabrakadabra** [skulpt/skulpt#762]
This request is based on your comment on [your homepage](skulpt.org):

> If you have a project that uses skulpt and would like me to link to it here, let me know on our github page.

I'm hoping you wouldn't mind adding my project [codetheblocks.com](https://codetheblocks.com) to this list.

Hope you like it :)

**Comment by albertjan** [comment]
Looks cool, open a PR and I'll merge it the site is in the `doc/` directory
