### ISSUE TITLE
Cannot move 2 objects at the same time(turtle,python)

### ISSUE THREAD

**Issue by orelxz100** [skulpt/skulpt#769]
so im gonna give you my code and my problem is that i cant move venus and mercury at the same time:

import turtle

wn = turtle.Screen()
wn.bgcolor("black")

mercury = turtle.Turtle()
mercury.shape("circle")
mercury.color("white")
mercury.shapesize(0.5,0.5)
mercury.speed(0)

def move1():
    global mercury
    for x in range(1,360):
        mercury.forward(1)
        mercury.left(1)

def move2():
    global venus
    for x in range(1,360):
        venus.forward(1)
        venus.left(1)

sun = turtle.Turtle()
sun.penup()
sun.shape("circle")
sun.color("orange")
sun.shapesize(2,2)
sun.setposition(0,55)

venus = turtle.Turtle()
venus.penup()
venus.shape("circle")
venus.color("red")
venus.shapesize(1,1)
venus.setposition(100,0)
venus.speed(2)

while True:
    move1(),move2()

**Comment by bnmnetp** [comment]
Hi,

You can't make turtles run at the same time in "regular" python either without a lot of extra work.  So I'm guessing this is a request for "help with homework" rather than a bug report.  This is not the place to get help learning to program in python.

**Comment by orelxz100** [comment]
Emm well i know python,but not turtle.i asked this because i wanted to make a simulation of the solar system just because i was bored and i wanted to learn a bit more about turtle.and thank you for the answer
