### ISSUE TITLE
Anonymous turtle throws type error

### ISSUE THREAD

**Issue by libremente** [skulpt/skulpt#772]
This looks like a duplicate of https://github.com/skulpt/skulpt/issues/631 which should be fixed by https://github.com/skulpt/skulpt/pull/632 but still throws an error for me.
The code:
```python
from turtle import *
forward(10)
```
returns:
`ExternalError: TypeError: a is undefined on line 3` in Skulpt `0.11.1` installed from npm.
I checked in Skulpt.org and no output is displayed. In trinket it works as expected.

Using the OOP approach does work.
Any clues why?
@albertjan 
Thanks a lot!

**Comment by albertjan** [comment]
Can you try and get the latest version from https://github.com/skulpt/skulpt-dist/? I'm afraid we're long overdue with a release, when the new release it out we'll also try an do a propper npm release.

**Comment by albertjan** [comment]
I just tried this on master, and it works. I'm closing this because it is fixed on master.
