### ISSUE TITLE
Python 3 version?

### ISSUE THREAD

**Issue by oliver-ni** [skulpt/skulpt#777]
Would it be possible to make a python 3 version?

**Comment by lewdon** [comment]
Py3 also needed

**Comment by bnmnetp** [comment]
Python 3 has been an ongoing conversation for us for some time. We can already support some things, such as print as a function and // division. 

What part(s) of Python 3 are most important to you?

**Comment by dsblank** [comment]
You might be interested in looking at https://github.com/iodide-project/pyodide which is Python3 and numpy, pandas, and more, compiled (transpiled, actually) to javascript. It is based on https://github.com/dgym/cpython-emscripten 

Pyodide is being created for use in https://github.com/iodide-project/iodide a notebook-like system. Looks like they have a python demo about ready: https://github.com/iodide-project/pyodide-demo

**Comment by bnmnetp** [comment]
@mcparadip if you set `Sk.python3 = true` It will give you real python3 printing behavior.

**Comment by mcparadip** [comment]
@bnmnetp My mistake. Seems undocumented though, can I send a PR documenting this?

**Comment by mcparadip** [comment]
@dsblank Is there a prebuilt version of pyodide available to use, or will I have to build it myself?

**Comment by dsblank** [comment]
Dunno... I'm just on the look for the Final Solution

**Comment by albertjan** [comment]
@dsblank I've been working on implementing the python3 grammar in skulpt, and I've succesfully compiled a program with it. But as you can imagine it's not a small feat to rework the entire compiler, it will happen I'm pretty sure of that. @trinketapp @bnmnetp @rixner @meredydd  and me are all comitted to skulpt. Watch this space :)

**Comment by dsblank** [comment]
@albertjan I certainly wish you all luck! (Of course, it is a large, moving target. Even when you're done, you won't be done...in order to keep it current with the latest version of Python. If there were a way to automatically, and continuously, convert the Python sources to JavaScript, there will still be work done to make it operate like Skulpt does now. It is a tough problem, I know.)

**Comment by j-f1** [comment]
@albertjan If you want to create a separate parser for Python written in JavaScript, the maintainers of [the Prettier Python plugin](https://github.com/prettier/plugin-python) might be interested in helping.

**Comment by acbart** [comment]
@albertjan any progress on this? It'd be quite amazing to have a proper Python 3 parser for Skulpt.

**Comment by acbart** [comment]
@albertjan sorry to repeat the question, but has there been advancement? I've had a few undergrads playing around with ANTLR this semester, and we have the ability to get Python parse trees as JS objects - I wanted to make sure I wasn't just retreading old ground before I do the heavy work to turn PSTs into ASTs. It'd be really great to get features like static typing into Skulpt.

**Comment by albertjan** [comment]
@acbart you're forcing me to show my hand before I'm finished here 😄 I have to quickly reach out to someone. But rest assured we're a lot further down the python3 route then we were when we last talked.

**Comment by acbart** [comment]
How very exciting! I look forward to hearing more when you are ready. We are reaching the summer, and I'm starting to scope out what improvements I want to make during this time period - fortunately, I have at least a week before anything will really occur.

**Comment by rixner** [comment]
@albertjan if would be nice if you did let us know what you have.  I also intend to be working on Python3 this summer and it would be nice if we could be working on different things, rather than all replicating the same work...

**Comment by AwokeKnowing** [comment]
Hi guys, @albertjan  @rixner with "python3 in the browser" seeming the point of skulpt, what is the status and roadmap?

**Comment by albertjan** [comment]
@AwokeKnowing We're working on it, this is no small feat. But we currently have a python3 version available. You can use that by calling: 

```
Sk.configure({
    .... other settings
    __future__: Sk.python3
});
```

**Comment by mikeckennedy** [comment]
Hi @albertjan I agree with @AwokeKnowing that if you have it that far along, you might want to amend this statement from the readme (the very first line):

**_Skulpt is a Javascript implementation of Python 2.x._**

If, on the other hand, `__future__: Sk.python3` doesn't really get you there, knowing what's missing would be cool.

**Comment by albertjan** [comment]
@mikeckennedy we're only a small team but we should definitely update the readme especially since we recently merged #905 we've updated the grammar of skulpt to python 3. (don't hesitate to send a PR :grin:)

And to answer your second comment, I don't really what we were missing. Some things that are on my mind are 
- async functions
- f strings

But to python developers stuff in the stdlib is probably more pressing.

I think we should close this ticket @skulpt/committers  we should supersede it with an issue where we can identify the caveats.

**Comment by mikeckennedy** [comment]
Hi @albertjan 

That sounds great. I think async functions and JavaScript callbacks would be interesting but certainly I'd be OK to not have support for async/await. It'd be much better to have basic Python 3 support (range, print(1,2, end='-'), type of things).

f-strings would be great.

Thanks for the update.

**Comment by albertjan** [comment]
@mikeckennedy I don't fully understand what you mean with: 

> (range, print(1,2, end='-'), type of things)

- range is not an iterator in skulpt that is a caveat
- `print(1,2, end='-')` works 😄 (I did just find out `print` doesn't return `None` there's always a bug)

**Comment by mikeckennedy** [comment]
Oh sorry, I think I was thinking of xrange missing or something weird like this. Bad example. Just having Python 3 core language syntax would be great. Sounds like that's basically there.

**Comment by albertjan** [comment]
This is about as advanced as we get now: 😄 

<img width="417" alt="image" src="https://user-images.githubusercontent.com/301791/63096390-b7565000-bf65-11e9-9476-ea63440aece3.png">

**Comment by albertjan** [comment]
Love your podcast btw 🙏

**Comment by mikeckennedy** [comment]
Looks like a great test to me @albertjan, thanks for the kind words on the podcast. We haven't done an episode on Skuplt at all or Python on JS in a long time... Maybe you guys should come on the show.

**Comment by albertjan** [comment]
Absolutely! Shall I send you an email? How do we set it up? 😄

**Comment by mikeckennedy** [comment]
Sounds good, just shoot me an email (found here: https://talkpython.fm/home/about ). Thanks!

**Comment by albertjan** [comment]
I'm going to close this as we've officially crossed the py3 barrier. Although much is still missing but this ticket no longer serves a purpose. 😄
