### ISSUE TITLE
`No module named sys`

### ISSUE THREAD

**Issue by alex-milanov** [skulpt/skulpt#780]
This the error I am getting when trying to run the npm module via browserify with the following code:
```py
print "Hello World!"
```
I've also tried building the latest version from the repo - same error.
Also tried modifying the contents of `skulpt-stdlib.js` to be applied to Sk by passing it to an exported function:
```js
module.exports = function(Sk) {
  Sk.builtinFiles = {
  // ...
  };
  return Sk;
}
```
Same error.

The only solution I found so far was by using directly the snapshoted skulpt.js from https://github.com/vkaravir/node-js-python from 7 years ago.

**Comment by ludwiktrammer** [comment]
I'm experiencing the same issue. Was anyone able to work around this?

**Comment by ludwiktrammer** [comment]
Ok, it turns out that Skulpt by default cannot read its own built-in files. I find this peculiar, but it seems that this is by design (?). You need to implement a function to read the files, or just copy the one that is used in the example on Skulpt's homepage:

```
function builtinRead(x) {
    if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined)
        throw "File not found: '" + x + "'";
    return Sk.builtinFiles["files"][x];
}
```

And then configure Skulpt to use it:

```
Sk.configure({
    // ...
    read: builtinRead,
});
```

**Comment by albertjan** [comment]
@ludwiktrammer Yeah you're right. Sorry about that. It is something I've looked at in the past. After the proposed read changes are done I'll address this. 😄 Sorry it took a while to figure out. I think most of the example's do contain a `builtinRead` function though.
