### ISSUE TITLE
[Turtle] Load images

### ISSUE THREAD

**Issue by libremente** [skulpt/skulpt#790]
Hi all,

I am trying to understand how to properly load images inside screen (bgpic/addshape) using Skulpt. Which is the proper way to do it? I see in: https://trinket.io/python/cc436dea14 that the trinket guys did it. 
Thank you!

**Comment by albertjan** [comment]
So those are changes to trinkets own fork of skulpt and turtle. If you have a look over at their fork of skulpt esp. https://github.com/trinketapp/skulpt/blob/master/src/lib/turtle.js

**Comment by albertjan** [comment]
I'll have a chat to see if we can create a PR to merge those changes back into the main repo.

**Comment by bnmnetp** [comment]
That would be awesome @albertjan !

**Comment by libremente** [comment]
That's great @albertjan. Thank you for your interest!

**Comment by libremente** [comment]
@albertjan do you have any update regarding this issue? Thank you!

**Comment by wizofaus** [comment]
Also interested, as I was trying to work out how to download images using urllib.request then register them as turtle images (with no luck so far).

**Comment by wizofaus** [comment]
Unfortunately I think it will require better support for raw byte arrays for that to be possible - currently urllib.request uses responseText, which isn't appropriate for binary files.  But it's not clear what the alternative could be given skulpt strings don't seem to able to hold raw bytes that I can see.

**Comment by wizofaus** [comment]
I've actually looked at the github trinket fork and the code to manage loading of bitmap shape files is not fully part of the source - elsewhere they assign a custom "assets" function to Sk.TurtleGraphics that searches their own managed set of image assets to get the URL, and then in turtle.js they've modified the addshape/register_shape function to be able to use an Image object to load from said url (it still supports vectors).   That would still be a useful addition to merge back in even if means your hosting environment has to provide the function to map asset name to URL.

**Comment by libremente** [comment]
Hi @wizofaus , did you manage to do some further work regarding this issue? Thanks!

**Comment by wizofaus** [comment]
No, sorry, but worth talking to the trinket authors I'd say.

**Comment by libremente** [comment]
Hi @albertjan , any update regarding this issue? Thank you! :+1:

**Comment by albertjan** [comment]
@libremente @wizofaus it's done! Cheers!
