### ISSUE TITLE
Inconsistent behavior with class variables

### ISSUE THREAD

**Issue by anderoonies** [skulpt/skulpt#791]
I'm running the following Python code in Skulpt:
```py
class MyClass(object):
    meta = []

    def __init__(self):
        MyClass.meta += [self]
```
sometimes it runs correctly, sometimes it throws `AttributeError: 'str' object has no attribute '[object Object]'` on line 5.
does anyone know what the configuration is that's making this possible sometimes (but not always)?

**Comment by bnmnetp** [comment]
Hmm, where are you getting your version of skulpt?  I've just run this code

```
class MyClass(object):
    meta = []

    def __init__(self):
        MyClass.meta += [self]

x = MyClass()

y = MyClass()
print(MyClass.meta)
```

A bunch of times and I can't get it to fail.

**Comment by anderoonies** [comment]
not sure the version, our shop doesn't use a package manager for a few things, Skulpt being one of them.
the same version is running in both situations, though, with only one of them throwing the error.

**Comment by anderoonies** [comment]
closing this out—some code was overwriting the global Skulpt
