### ISSUE TITLE
Attribute __class__ does not exist

### ISSUE THREAD

**Issue by acbart** [skulpt/skulpt#792]
This one surprised me. Even though most classes have an internal (skulpt-side) attribute named `__class__`, they don't have one on the Python facing side. Therefore, you can trigger the following:

```python
>>> "".__class__
AttributeError: 'str' object has no attribute '__class__' on line 1
```

Even though in regular Python this would do:

```python
>>> "".__class__
<class 'str'>
```

It seems like it'd be a fairly trivial fix to expose this in all the builtins? I wasn't sure the best way to do so.

**Comment by s-cork** [comment]
fixed
