### ISSUE TITLE
how to import customize python file

### ISSUE THREAD

**Issue by Lincoln-xzc** [skulpt/skulpt#793]
I would like to import my own python module, could anyone tell me how to import it?

**Comment by bnmnetp** [comment]
Hi,

The skulpt.org page shows you how to publish and configure skulpt for 3rd party modules. You would need to follow those directions for your own module.

**Comment by Lincoln-xzc** [comment]
Thank you for your relply. Actually, I have read that page. Instead of having a .js file of the third-party module, I only have a .py file, how can I import that one ? Any help?

**Comment by bnmnetp** [comment]
If you have complete control over your environment you could always drop it into the src/lib folder of skulpt and build your own skulpt-stdlib.js
