### ISSUE TITLE
Code Shrew - new example of Skulpt in the wild

### ISSUE THREAD

**Issue by ludwiktrammer** [skulpt/skulpt#795]
I would just like to report on a new Skulpt-based site in the wild. I created Code Shrew as a project for Educational Technology graduate class at Georgia Tech. It's a platform for learning and practicing basic concepts of programming by creating drawings and animations using computer code.

It can be found here: https://shrew.app/
There is a 2-minute welcome video on the homepage that describes the basics.

More information is available in the "About" section: https://shrew.app/about/

We also wrote a paper: https://arxiv.org/abs/1808.01100

And yesterday The Register published an article about Code Shrew (completely unprompted, BTW): https://www.theregister.co.uk/2018/08/07/code_shrew_python/ (Skulpt is mentioned in the text).

Feel free to add Code Shrew to the "Skulpt in the Wild" section on the Skulpt's website, if you want. As a side note, there are some links there which don't work anymore, so should be probably updated or removed.

**Comment by albertjan** [comment]
Oh wow! Nice work! I'll definitely check it out.
