### ISSUE TITLE
Include external libraries with absolute url 

### ISSUE THREAD

**Issue by vbourgeois** [skulpt/skulpt#803]
Hello

I'm trying to include external libraries with absolute url to github repo (thanks to raw github content), but it is not working...

Here is the code : 

```
Sk.externalLibraries = {
  numpy : {
    path: 'https://raw.githubusercontent.com/ebertmi/skulpt_numpy/master/dist/numpy/__init__.js',
    dependencies: ['https://raw.githubusercontent.com/ebertmi/skulpt_numpy/master/deps/math.js'],
  },
  'numpy.random' : {
    path: 'https://raw.githubusercontent.com/ebertmi/skulpt_numpy/master/dist/numpy/random/__init__.js',
    dependencies: ['https://raw.githubusercontent.com/ebertmi/skulpt_numpy/master/deps/math.js'],
  },
  matplotlib : {
    path: 'https://raw.githubusercontent.com/ebertmi/skulpt_matplotlib/master/matplotlib/__init__.js',
  },
  'matplotlib.pyplot' : {
    path: 'https://raw.githubusercontent.com/ebertmi/skulpt_matplotlib/master/matplotlib/pyplot/__init__.js',
    dependencies: [
      'https://raw.githubusercontent.com/ebertmi/skulpt_matplotlib/master/deps/d3.min.js',
      'https://raw.githubusercontent.com/ebertmi/skulpt_matplotlib/master/deps/jquery.js',
    ],
  },
  'turtle': {
    path: 'https://raw.githubusercontent.com/trinketapp/turtle/master/__init__.js',
  }
}

```

Am i missing something ? Can I link external libraries like this or do I need to host them myself and use relative url ? The documentation is not really clear about it.

Thank you for your help.

**Comment by albertjan** [comment]
I've never tried this, I'd have to investigate. I am pretty sure that the dependencies don't work in modern browser because they get added as script tags with and will therefore require the content to be served with a content-type that specifies it's a script rather then plain text which is what github raw content does. For the code that is interpreted or evalled by skulpt. I'll have a look at the source.

**Comment by albertjan** [comment]
Well .... after looking at the code my memory isn't as good as I thought it would be. According to the code: https://github.com/skulpt/skulpt/blob/master/src/import.js#L11-L41 it should just work. Do you have a public url where this runs so I can have a look?

**Comment by vbourgeois** [comment]
I was using sources from `skulpt-dist` (that doesn't seem up to date), now I just moved to the sources of `skulpt` that I compiled myself, and it is working perfectly well! 

Thank you for your help.

**Comment by albertjan** [comment]
@vbourgeois master of skulpt-dist is always upto date with skulpt master, the latest tag over at skulpt-dist is a while ago. 😄

**Comment by vbourgeois** [comment]
`skulpt.min.js` is from 2 years ago and `skulpt.js` from 8 days ago :sweat_smile:

**Comment by albertjan** [comment]
ah really, jeez apparently we don't build a minified version on a master branch build. I'll have to fix that.

**Comment by vbourgeois** [comment]
Do you plan to have an up to date NPM package? It would be perfect!
