### ISSUE TITLE
how to extend turtle.textinput() and turtle.numinput()

### ISSUE THREAD

**Issue by Lincoln-xzc** [skulpt/skulpt#804]
I got an async problem when I try to extend turtle.textinput and turtle.numinput. any help?

**Comment by mindhacker0** [comment]
how did u solve this problem,i got this error: 'module' object has no attribute 'textinput' on line x.

**Comment by Golotus** [comment]
I got same problem.   have you solved this problem？ @Lincoln-xzc

**Comment by mindhacker0** [comment]
I solved it successfully，just rewrite 'turtle.js' library file to add that two function and return it in read hook.it not support yet. @Golotus

**Comment by Golotus** [comment]
> I solved it successfully，just rewrite 'turtle.js' library file to add that two function and return it in read hook.it not support yet. @Golotus

I'm so sorry to reply to you now, I solved the problem in the same way. thanks a lot.
