### ISSUE TITLE
Question: best way to implement testing?

### ISSUE THREAD

**Issue by vsoch** [skulpt/skulpt#806]
Hey skulpt!

What would be the best way for skupt to support an online code tester, e.g., give the user a problem, a space to work on it, and then validate their function returns the right answer?

**Comment by albertjan** [comment]
This is too broad a question, I can't answer this without more information and more time 😄

**Comment by vsoch** [comment]
Is there any reason you can't ask for more information, and take more time?

**Comment by bnmnetp** [comment]
Do you mean something like this?  https://runestone.academy/runestone/static/overview/overview.html#hidden-unit-tests-with-graphical-status

**Comment by vsoch** [comment]
Yes! Exactly!

**Comment by bnmnetp** [comment]
https://github.com/RunestoneInteractive/RunestoneComponents

**Comment by vsoch** [comment]
Holy crap, this is amazing! It's like sphinx went to graduate school. Thank you <3

**Comment by bnmnetp** [comment]
You're welcome. 😄 Comments like that make me very happy,  a good way to close out Friday afternoon.
