### ISSUE TITLE
`raise e, None` and `raise e, None, None` mishandle already-instantiated exception 

### ISSUE THREAD

**Issue by mentalisttraceur** [skulpt/skulpt#821]
# Problem
`raise Exception('message'), None` and `raise Exception('message'), None, None` error out, but I would expect them to work exactly like `raise Exception('message')` because that is how it has always worked in Python 2 (documented as such way back in 2.0, and I think it worked like this even in the 1.x days).
# Reproducing Example
(Using the ["demo" at skulpt.org](http://www.skulpt.org))
```
try:
    raise Exception
except Exception as e:
    print(e)

try:
    raise Exception('message')
except Exception as e:
    print(e)

try:
    raise Exception, None
except Exception as e:
    print(e)

try:
    raise Exception('message'), None
except Exception as e:
    print(e)

try:
    raise Exception, None, None
except Exception as e:
    print(e)

try:
    raise Exception('message'), None, None
except Exception as e:
    print(e)
```
# Expected Output
```
Exception:  on line 11
Exception: message on line 16
Exception: null on line 21
Exception: message on line 26
Exception: null on line 31
Exception: message on line 36
```
# Actual Output
```
Exception:  on line 11
Exception: message on line 16
Exception: null on line 21
ExternalError: TypeError: $call31 is not a function on line 26
Exception:  on line 31
ExternalError: TypeError: $call44 is not a function on line 36
```

**Comment by mentalisttraceur** [comment]
Thanks for fixing this! But I would've appreciated an explicit comment along the lines of "this is fixed" instead of just an close without comment. Without comment I couldn't tell if it was being closed in a dismissive "won't fix" way, or by mistake, and I had to go test if it was fixed just to confirm. Glad to see it fixed though!

**Comment by s-cork** [comment]
Apologies. I ran your code in the latest version of skulpt in py2 mode and it ran. (I think it's been fixed for a while now).
