### ISSUE TITLE
Anonymous turtle not working

### ISSUE THREAD

**Issue by cgibin** [skulpt/skulpt#822]
Hello, this code:
`from turtle import *`
`forward(100)`
throws "TypeError: Cannot read property 'apply' of undefined"
Im using skulpt.min.js and skulpt-stdlib.js from https://github.com/skulpt/skulpt-dist
Demo on skulpt.org also fails with this code, but Trinket version works fine

**Comment by libremente** [comment]
Hi @cgibin, check this issue: https://github.com/skulpt/skulpt/issues/772.
It should be fixed on master now, did you try to checkout master?

**Comment by cgibin** [comment]
Yes, thanks, already got it to work. The problem is that I found another weird thing in master, but this is a separate issue. Must to say, the different versions of Skulpt(site/rep) is a constant source of confusion
