### ISSUE TITLE
`finally` does not work

### ISSUE THREAD

**Issue by mentalisttraceur** [skulpt/skulpt#823]
Two closely related issues, one with try-except-(else-)finally and one in try-finally, tested with the last release downloaded on the [Skulpt homepage](http://skulpt.org).

I think this repository has more recent code but I haven't had the spare time and mental cycles to figure out if it's fixed in the unreleased changes, or if there are other "releases" tucked away somewhere that I haven't noticed.

# First Problem: a `try`-`finally` by itself seems to not parse

```python
try:
    print('try')
finally:
    print('finally')
```

Superficially seems to fail the same way it does on other syntax errors I've tried.

# Second Problem: `finally` block contents ignored

```python
try:
    print('try')
except:
    print('except')
finally:
    print('finally')
````

Expected output:
```
try
except
finally
```

Actual output:
```
try
except
```

**Comment by albertjan** [comment]
It has been fixed:

```JavaScript debugger enabled
Python 2.6(ish) (skulpt, Wed Mar 06 2019 15:48:30 GMT+0000 (GMT))
[v8: 3.25.30] on a system
Don't type "help", "copyright", "credits" or "license" unless you've assigned something to them
>>> try:
...     print "try" 
... except:
...     print "except"
... finally:
... 	print "finally"
... 
try
finally
>>> try:            
... 	print "try"
... finally:
... 	print "finally"
... 
try
finally
>>> ```

you can download the latest version here: https://github.com/skulpt/skulpt-dist 

the minified version hasn't been updated recently however.

**Comment by mentalisttraceur** [comment]
@albertjan Thank you. It's not really clear to me how to use the `skulpt.js` from that link, because it looks for a `deps.js`, which the download I got from the main Skulpt website did not require. Are there instructions somewhere?

**Comment by albertjan** [comment]
You can ignore deps.js, it will work without it.
