### ISSUE TITLE
Calling ./m or ./skulpt.py generates empty dist directory

### ISSUE THREAD

**Issue by underthegui** [skulpt/skulpt#851]
Calling ./m or ./skulpt.py runs all unit tests then generates empty /dist directory

Ran it a few times, tried removing directory completely then running again. 

Building works when recreate the code base through `npm run build`

Anyone having the same issue?

Edit* it looks like calling `npm run build` runs `python skulpt.py dist`, so I'm guessing it has to do with the nuance between ./[file][command] vs python [file][command], will continue investigating.

Edit2* Looks like the builds are failing:

> 
> npm ERR! Linux 4.15.0-47-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> npm ERR! skulpt@1.0.0 build: `python skulpt.py dist`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the skulpt@1.0.0 build script 'python skulpt.py dist'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the skulpt package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     python skulpt.py dist
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs skulpt
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls skulpt
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /var/www/testtest/htdocs/wp-content/plugins/test/public/skulpt/npm-debug.log
> 

 Can anyone point me in the right direction?

**Comment by bnmnetp** [comment]
If it runs all the tests successfully then it is mostly likely you are missing jshint .  Did you run the npm install command prior to the build?  If not make sure you do that and that you can run jshint.

**Comment by albertjan** [comment]
Do you have python installed?

**Comment by underthegui** [comment]
Hey guys, looks like I have the issue fixed, although I'm embarrassed to say, I'm not 100% certain what exactly fixed it. For anyone that may stumble on this thread in the future, here are some of the steps I took.

- first to address the questions above, yes, I did run npm install and did have python installed, but just in case, I ran it again?
- I also had 18.04 linux dist so there were issues with skulpt requiring libreadline.so.6, since this dist only has libreadline.so.7, (and would not allow me to install 6) I had to create a symbolic link:  `sudo ln -s libreadline.so.7.0 libreadline.so.6`
- update your linux: sudo apt-get update && sudo apt-get upgrade. I got some warnings here for dependency issues with mariadb but it shouldn't affect skulpt
- after running again, it seems to compile the code, but with an error compiling the jsdoc.

hope this helps.

**Comment by albertjan** [comment]
Hah cool. Sorry if my comment was unhelpful. 😄

**Comment by rixner** [comment]
Just so this is documented somewhere, I also use Ubuntu and have dealt with the annoying ```libreadline.so.6``` issue.  This [page](https://utcc.utoronto.ca/~cks/space/blog/linux/Ubuntu1804ReadlineMess) has a slightly better fix than simply simlinking 6 to 7 (which may cause some problems, but I'm not sure).  I suspect this was a large part of the problem here.
