### ISSUE TITLE
ReferenceError: Sk is not defined

### ISSUE THREAD

**Issue by Dante-Morrison** [skulpt/skulpt#852]
so i'm working on a simple python demo site with a few buddies and using skulpt i always get this particular error and there doesn't seem to be a way around it. it is the title described and i'm working on it with repl.it so you can test it right now if you wish. https://repl.it/@Dante_Morrison/the-best-website-of-awesomeness
i dont entirely know if the error is with repl or with the code but at the moment this is just a test from the website. am i doing something wrong? please help

**Comment by bnmnetp** [comment]
I tried your repl.it and I think the problem is with the environment.  You will notice that jQuery and $ are also not defined.  I don’t see anything wrong with your example, but I haven’t studied it carefully.  Why not just put it in file locally and use python -m http.server to test it?
