### ISSUE TITLE
import and file read

### ISSUE THREAD

**Issue by Dustyposa** [skulpt/skulpt#854]
Sorry. I have to take up part of your time.
I want to import another file.py or read a file, can I use browser dom to complete it? If can't do it, how can I do?
Have any example to realize it?
And I know a feature By [#827](https://github.com/skulpt/skulpt/pull/827) Sk can use Sk.inBrowser  to acheive read a file by dom's id. But I have no way to achieve it.
This feature has any example?

**Comment by albertjan** [comment]
Hi! We should change this, this functionality should live in the read function. But for now you should have something like this in your document:

```<div id="filename">Hello from the dom</div>``` or 
```<textarea id="filename">Hello from a textarea</textarea>```

```f = open('filename')
content = f.read()
assert content == "Hello from the dom"
```

let me know if this works

**Comment by Dustyposa** [comment]
> Hi! We should change this, this functionality should live in the read function. But for now you should have something like this in your document:

oh thanks!my miss, it is working.
Actually， I used to ```with open("file.txt") as f:
    print(f.read())``` . 
This way won't work.
This is not support the feature?

And I use `<div id={"file.py"}>a = "Hello from the dom"</div>` , but I can't import it.
If want to import module, is must use ```python
var keywds = Sk.importModule("keyword", false, false);

mod.namedtuple = function (name, fields) {
......
```?

**Comment by albertjan** [comment]
Yeah I see why you'd want that, you'd have to implement a read function for that because the import doesn't use the python file api.

```
Sk.configure({
    ..., //your props
    read: function(filename) {
        if (filename === "file.py") {
             return "a = \'Hello from import\'";
        }

        throw new Error("not found");
    }
});
```

Now you should be able to import file:


```
from file import a
print a
```

**Comment by Dustyposa** [comment]
Oh, thank you very much. I solved it.
I love skulpt. Skulpt is really useful.
