### ISSUE TITLE
Efficiency Question Re: Sk.importModuleInternal_  and Generating a Module without Running

### ISSUE THREAD

**Issue by underthegui** [skulpt/skulpt#856]
Something that might be of interest is how to generate a module using the methods in import.js without running the module right away... to be called at a later time to run. Would this help optimize the efficiency as we aren't translating each time we want to run the function? 

For example:

```
code = Sk.importModuleInternal_(...);
setInterval(function(){
   Sk.misceval.callsim(code);
}, 1000);
```

I believe should be more efficient than if we were to translate each time:

```
setInterval(function(){
   Sk.misceval.callsim(Sk.importModuleInternal_(...));
}, 1000);
```

I've tried fiddling with the above with minor successes. Still trying to dissect the details of import.js functions. Maybe a thread we can leave open for discussion.

**Comment by albertjan** [comment]
Yeah that would be more efficient, even though compiling is pretty quick. Skulpt doesn't support that now though. But @meredydd did some work on that a while ago here: https://github.com/skulpt/skulpt/pull/609 you might be able to revive that.

**Comment by albertjan** [comment]
Oh one more thing nobody stopping you from saving a reference to the function from the global skulpt scope.

```
def test():
    print "test"
```

```
Sk.importMainWithBody()
```

```
var func = Sk.global['test'];

Sk.misceval.callsim(func);
Sk.misceval.callsim(func);
Sk.misceval.callsim(func);
```
