### ISSUE TITLE
Error "unreachable code after return statement"

### ISSUE THREAD

**Issue by T1mbo96** [skulpt/skulpt#858]
Hello, 

I embedded Skulpt in a project for my university degree with the python3 extension and everything worked as expected and described.

But since like two weeks ago I always get the error "unreachable code after return statement" 8times in the console in the skulpt.min.js file when I run the minimal example from the skulpt website (I get the 'correct' python2 output though). Also the python3 extension isn't working correctly anymore (e.g. print(10, 20) will print "(10, 20)" but not "10 20" anymore).

I tried it with the cdn or the updated files of this one repository that holds the stdlib and min files. Both don't work.

Does anyone experience the same or knows why it behaves like this recently?

**Comment by albertjan** [comment]
@T1mbo96 did you update skulpt recently? If so you have to change the way you configure skulpt like this:
```
Sk.configure({
    ..., // your config
    __future__: Sk.python3
});
```

**Comment by albertjan** [comment]
But I'm interested to see the `"unreachable code after return statement"` can I see that error happening somewhere?

**Comment by T1mbo96** [comment]
@albertjan Thank you very much for your response! The change of the configuration of the python3 version helped and it works like before now, but the error stays.

You can check it with the following URL; I embedded the minimal example from the website + the python3 configuration for you. If you check the console in browser dev-tools (at least I) you can see the error message.

[http://python-tutorial.informatik.uni-wuerzburg.de/Test/](url)

**Comment by albertjan** [comment]
I hate to be that guy but, "It works on my machine" :smile:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/301791/56978552-ac6edf80-6b6f-11e9-9141-61a1714b1b1a.png">

What browser are you using? And what version?

**Comment by bnmnetp** [comment]
Yep, I tried it on both Chrome and Safari on my MacBook and did not see anything but success.

**Comment by T1mbo96** [comment]
Well, thanks for trying. I downloaded chrome and tried it and it worked. 

But still getting the error in Firefox. It's the newest version of Firefox.

It's not too much of a problem since everything is working besides that error gets printed.

**Comment by albertjan** [comment]
Ohh I thought this came from the runtime! But it's actually Firefox noticing there is unreachable code in skulpt. Which doesn't really surprise me! I'll have to checkout FF we should have a look at these cases. They are likely bugs in skulpt.

**Comment by T1mbo96** [comment]
Oh, Yeah sorry that i couldn‘t articulate myself properly and couldnt describe the Problem correctly the First Time! But thanks for your response and help!

**Comment by albertjan** [comment]
I looked into these errors they are from the compiled code. The compiler adds a throw statement at the end of each block `/*   389 */                     throw new Sk.builtin.SystemError('internal error: unterminated block');
` for example. This is to catch if the compiler is doing something wonky and not returning from a block. These are never supposed to happen if they were reachable the compiler would do the wrong thing. :smile: 

It's safe to ignore these warnings
