### ISSUE TITLE
About the import 

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#863]
When I import a module as below:
`import xml.etree.ElementTree`
it will try to search the files:
```
src/builtin/xml.js
src/builtin/xml/__init__.js
src/lib/xml.js
src/lib/xml/__init__.js
./xml.js

src/builtin/etree.js
src/builtin/etree/__init__.js
src/lib/etree.js
src/lib/etree/__init__.js
./etree.js

src/builtin/ElementTree.js
src/builtin/ElementTree/__init__.js
src/lib/ElementTree.js
src/lib/ElementTree/__init__.js
./ElementTree.js
```
I think it should search the files such as:
```
src/builtin/xml/etree.js
src/builtin/xml/etree/__init__.js
src/lib/xml/ElementTree.js
src/lib/xml/ElementTree/__init__.js
./xml/ElementTree.js

src/builtin/xml/etree/ElementTree.js
src/builtin/xml/etree/ElementTree/__init__.js
src/lib/xml/etree/ElementTree.js
src/lib/xml/etree/ElementTree/__init__.js
./xml/etree/ElementTree.js
```

**Comment by albertjan** [comment]
Hi @alexwenbj it does but you have to return something when you import an `__init__.py` file to indicate it's a package. See this jsbin: https://jsbin.com/fiwegiq/10/edit?js,console you'll see it tries the following files:

```
"file: src/builtin/xml.js"
"file: src/builtin/xml/__init__.js"
"file: src/lib/xml.js"
"file: src/lib/xml/__init__.js"
"file: ./xml.js"
"file: ./xml/__init__.js"
"file: /xml.js"
"file: /xml/__init__.js"
"file: src/builtin/xml.py"
"file: src/builtin/xml/__init__.py"
"file: src/lib/xml.py"
"file: src/lib/xml/__init__.py"
"file: ./xml.py"
"file: ./xml/__init__.py"
"found!"
"file: src/builtin/xml/etree.js"
"file: src/builtin/xml/etree/__init__.js"
"file: src/lib/xml/etree.js"
"file: src/lib/xml/etree/__init__.js"
"file: ./xml/etree.js"
"file: ./xml/etree/__init__.js"
"file: /xml/etree.js"
"file: /xml/etree/__init__.js"
"file: src/builtin/xml/etree.py"
"file: src/builtin/xml/etree/__init__.py"
"file: src/lib/xml/etree.py"
"file: src/lib/xml/etree/__init__.py"
"file: ./xml/etree.py"
"file: ./xml/etree/__init__.py"
"found!"
"file: src/builtin/xml/etree/ElementTree.js"
"file: src/builtin/xml/etree/ElementTree/__init__.js"
"file: src/lib/xml/etree/ElementTree.js"
"file: src/lib/xml/etree/ElementTree/__init__.js"
"file: ./xml/etree/ElementTree.js"
"file: ./xml/etree/ElementTree/__init__.js"
"file: /xml/etree/ElementTree.js"
"file: /xml/etree/ElementTree/__init__.js"
"file: src/builtin/xml/etree/ElementTree.py"
"file: src/builtin/xml/etree/ElementTree/__init__.py"
"file: src/lib/xml/etree/ElementTree.py"
"file: src/lib/xml/etree/ElementTree/__init__.py"
"file: ./xml/etree/ElementTree.py"
"file: src/builtin/sys.js"
"builtin: src/builtin/sys.js"
"ElementTree"
```

I've added three files: `./xml/__init__.py`, `./xml/etree/__init__.py` and `./xml/etree/ElementTree.py` make sure you ignore the ones in the `builtinFiles` see the jsbin.

**Comment by alexwenbj** [comment]
@albertjan,Thanks for your kindness and patience.
I read your jsbin example, but still not very clear about them:
1. How to indicate it is a package?Just like below?
```
var $builtinmodule = function(name) {
  var xml = {};

  return xml;
};

```
2. In my project, it only iterates the xml.js(py)/etree.js(py)/ElementTree.js(py),not include the xml/etree/ElementTree.js,What should i do to add the xml/etree/ElementTree...?
My customized read is as you wrote:
https://github.com/skulpt/skulpt/issues/855#issuecomment-491266090

Thank you again.

**Comment by albertjan** [comment]
No you can just return an empty string, the `__init__.js` file can be an empty file. You need to have all three files if you want to reach `/xml/etree/ElementTree.js`

```
./xml/__init__.js -> xml is a package
./xml/etree/__init__.js -> xml.etree is a package
./xml/etree/ElementTree.js -> xml.etree.ElemenTree is a class
```

**Comment by alexwenbj** [comment]
You mean,keep empty in ./xml/__init__.js?

**Comment by albertjan** [comment]
yeah like in my jsbin you see that I return an empty string when it tries to find `./xml/__init__.py`

**Comment by alexwenbj** [comment]
Maybe I should describe the whole case:
1. In the skulpt/src/lib/xml path,it provides `__init__.py`,the file content is:
`raise NotImplementedError("xml is not yet implemented in Skulpt")`
2. In my server side,I provide `xml/__init__.js,xml/etree/__init__.js and xml/etree/ElementTree.js`,the previous two files' content is like:
```
var $builtinmodule = function(name) {
  var xml = {};

  return xml;
};
```
3. If i change the file content from :
```
var $builtinmodule = function(name) {
  var xml = {};

  return xml;
};
```
to empty, it produced an error:`ReferenceError: $builtinmodule is not defined`
4. In my customize read function:
```
function builtinRead(x) {
      console.log(x);
      ......
}
```
it never iterates recursively the path such as xml/etree/ElementTree.js,it only iterates xml,etree and ElementTree files.
Very strange...

**Comment by alexwenbj** [comment]
If I stole your skulpt.js from jsbin ,it raised an error:xml is not yet implemented in Skulpt

**Comment by alexwenbj** [comment]
The KEY point is that in my page, it NEVER recursively iterates the path.

**Comment by alexwenbj** [comment]
@albertjan Got it done, finally!
Must set the key be:.`/xxx/__init__.js` or `./xxx/__init__.py`,if the key is` ./xxx.js`, will not iterate the sub package.For example:
```
        './xml/__init__.js' : {
		path : 'static/js/xml.sk/__init__.js'
	},
	'./xml/etree.js' : {//xml.etree
		path : 'static/js/xml.sk/etree/__init__.js'
	},
	'./xml/etree/ElementTree/__init__.js' : {//xml.etree.ElementTree
		path : 'static/js/xml.sk/etree/ElementTree-orig.js'
	}
```
Thank you again!
