### ISSUE TITLE
Can I get turtle result as a picture?

### ISSUE THREAD

**Issue by Dustyposa** [skulpt/skulpt#864]
I want to get the turtle result as picture.
I have a way to realize it.
Run the code and jump the turtle painting animation.
Then use canvas to save result as a picture.
How about this way?
Do skulpt has any easy way to realize it?

**Comment by albertjan** [comment]
Skulpt doesn't have this capability, but it's a canvas so you can get the image of that see: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by Dustyposa** [comment]
Oh I got it. Thanks.
