### ISSUE TITLE
turtle drawing will block in strange situation

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#868]
Please visit the link [here](https://trinket.io/library/trinkets/a29bcba579) ,It will block when the i is 126.And the drawing is stop,but the turtle head is still turn around slowly.
(Mac OS + Chrome 74.0.3729.157)
It is OK when run in Safari.

**Comment by bnmnetp** [comment]
I think you are just hitting an execution time limit.  Instead of speed(0) use tracer(32,0) to speed it up.

**Comment by alexwenbj** [comment]
> I think you are just hitting an execution time limit. Instead of speed(0) use tracer(32,0) to speed it up.

But it is OK in Python.Moreover,It is OK in Safari.

**Comment by alexwenbj** [comment]
If I add 3 lines code:
```
from turtle import *
speed(0)
colors = ["red","yellow","blue","black"] #Add line 1
for i in range(360):
    for j in range(4):
        color(colors[j%4])  #Add line 2
        forward(100)
        left(90)
        print("j=",j)  #Add line 3
    left(1)
    # print(i)
```
It is also OK.

**Comment by bnmnetp** [comment]
Python has no execution limit.  I'm not sure about trinket, but on my site I add an execution limit to keep beginners from locking up their page when they make an infinite loop.

But, I'm not sure what to make of your last example or why that would change the behavior in any significant way.

**Comment by alexwenbj** [comment]
I think it is not because of execution time limit.If you look at the drawing,you can find the forward is stop but the turn left is still executing,so I guess it is because the turn left and forward action is not synchronously after execute some times.The print() and change color function, slow down the whole actions, then the forward and turn left is synchronously.

**Comment by alexwenbj** [comment]
By the way,I looked inside the print.js code and found print function is supported the end argument,but when I run the code below:
```
for i in range(10):
  print(i,end=",")
```
It failed,do you know why?thank you. @bnmnetp

**Comment by bnmnetp** [comment]
I'm not sure what the default mode is for trinket.  But you need to be in python3 compatible mode for end to work.  Your example works fine for me.

It does seem like there is something funny going on with the "anonymous" turtle.  If I change your original example to explicitly use a turtle object, it works fine:

```
import turtle
t = turtle.Turtle()
t.speed(0)
for i in range(360):
    for j in range(4):
      t.forward(100)
      t.left(90)
    t.left(1)
    print(i)
```

This would not be the first time that the "anonymous" turtle had a bug in it.

**Comment by alexwenbj** [comment]
Yes,YOUR code is perfect in trinket and in older version turtle,but it still not work fine in the current turtle version. CC @albertjan 
About the print with end, you mean to enable the python3 mode by the configure:`Sk.python3 = true`?

**Comment by alexwenbj** [comment]
It seems the Sk.python3 conf is broken,`print("a","b")` outputs `(a,b)`,not the correct result `a b`.

**Comment by bnmnetp** [comment]
A couple of months ago we merged a lot of changes back to the master branch of skulpt from the trinket fork.  When we did this the way you configure for Python3 changed.  You need to do the following in the new version to get Python3 behavior:

```
Sk.configure({
...
__future__: Sk.python3,
...
}}
```

**Comment by alexwenbj** [comment]
When I add the conf as you showed,I got the exception in skulpt.js:`Uncaught Error: must specify Sk.__future__.print_function and it must be a boolean`.Any other configures?

**Comment by bnmnetp** [comment]
This works in Safari, but not in Chrome.
