### ISSUE TITLE
wrong output with class variable name

### ISSUE THREAD

**Issue by ANDEMEN** [skulpt/skulpt#870]
```python
class Dog:
  name = 'xxx'
  nickname = 'xxx'
  
print(Dog().name) # output: d
print(Dog().nickname) # output: xxx
```

why the output of the variable in class called name is always d ?

**Comment by albertjan** [comment]
You're right that's a bug.

```
➜  skulpt-ref git:(fix/repl-whitespace) ✗ ./m repl
Python 2.6(ish) (skulpt, Wed May 22 2019 09:04:06 GMT+0100 (British Summer Time))
[node: v11.14.0] on a system
Don't type "help", "copyright", "credits" or "license" unless you've assigned something to them
>>> class Test():
...     name = 'xxx'   
... 
>>> Test.name
klass
>>> 
>>> Test().name
klass
>>> class Test2:
...     name = 'xxx'
... 
>>> Test2.name
klass
>>> Test2().name    
klass
>>>
```

How has no-one ever tried to use a name field on a class. 😄 

This has to do with the fact that a function in javascript has a name property. And apparently we prioritise looking up stuff on the javascript class above stuff that lives in the class dict.  I'm unsure if we should change this priority or if we should make a special case for `name`.
