### ISSUE TITLE
import module

### ISSUE THREAD

**Issue by thlengane** [skulpt/skulpt#874]
Hi,

I am new on python, certainly new on skulpt. 

How can I "import os"? Also how do I import my own py file?

I tried to follow the instructions on the skulpt website but somehow I am failing to get the import working.

**Comment by Dustyposa** [comment]
#854 
you can look this issue.
maybe can solve your import problem.

**Comment by albertjan** [comment]
This jsbin also explains some stuff. https://jsbin.com/fiwegiq/10/edit?js,console for the `os` module you'll need the skulpt-stdlib. but the jsbin will show that too.

**Comment by thlengane** [comment]
@Dustyposa @albertjan , will try that. Thanks

**Comment by albertjan** [comment]
@thlengane did you get it to work?

**Comment by thlengane** [comment]
@albertjan , not at all. I think I struggling on the Sk.configure to import my own file. Basically, this is what I want to do:-

I have a file called download.py with the following code:

def launch_download(runId):
    import subprocess
    subprocess.Popen('java -jar C:/test/report.java ' + runId, shell=True, close_fds=True)

Now, in the html skulpt section, I want to do the following

from download import launch_download
launch_download('1234')


So do I have to configure the skulpt-stdlib.js? If so how?
What would be the Sk.configure code?

**Comment by albertjan** [comment]
@thlengane you can't do subprocess in a browser nor does it have java 😄 it compiles python to javascript. and then runs that in the browser you only have access to what would be in the browser.

**Comment by thlengane** [comment]
@albertjan I see, now it makes sense. I was trying to do some service that would execute  a shell command without using ActiveXObject/NodeJS or similar services. Thanks a lot for your assistance. I will try to find another way to overcome this, appreciated.
