### ISSUE TITLE
Build failed for the latest version

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#879]
It raise an error:
`Cannot find module 'google-closure-library'`
Maybe caused by [https://github.com/skulpt/skulpt/pull/869](https://github.com/skulpt/skulpt/pull/869)?

**Comment by albertjan** [comment]
@alexwenbj can you try running `npm install` in the root of the project and try again?

**Comment by alexwenbj** [comment]
It is OK now,thank you. @albertjan
