### ISSUE TITLE
Bringing new site online

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#883]
Hey @skulpt/committers   (and anyone else reading this)

Scott and I have the process moving forward so that I have control of the skulpt.org domain name. Yay!  This will make it easy for us to bring the new site online.

I think its mostly at least as good as the current site, and mostly better,  with the exception of the gallery page.

We need images/logos for projects.  I to propose we do away with the "Featured Project" language and just have a short description of the various projects that use skulpt in the wild. If you have a logo that I could use along side the project that would be great.  Right now its just Runestone, Trinket and Codeskulptor.  @meredydd I would be happy to add Anvil to that list if you want me to.

Others are welcome to add their project to this page by creating a PR against gallery.html on the gh-docs branch.

**Comment by bnmnetp** [comment]
Status update.

The new site is online.  --  I took ownership of the skulpt.org domain this morning.  Rather than spend time setting up dns to point at GAE, I decided to just point it to github-pages.

I'm pretty excited as we can now make updates to the site with PR's against the github-pages branch!

No extra steps to go through to deploy stuff to GAE.  I'll be putting together a PR to remove the GAE cruft in the next few days.

In the meantime would love a PR from @eah13 and @rixner with a screenshot for your sites, as they are currently gray placeholders.

**Comment by rixner** [comment]
@bnmnetp are you able to run the site locally?  I cannot.  Following the instructions in the README does not work for me.  The packages in package.json are very old versions that appear to be incompatible with the version of node I'm running, so upgrading them gets me farther, but still doesn't allow me to run the site.  I'd like to see that I'm doing the right thing before creating a pull request...  Also, is there any reason not to include the image in git locally rather than pointing the url somewhere else?

Also, this is great, thank you for putting in the time and effort to get this moved over!

**Comment by bnmnetp** [comment]
I will take a look at it.  The site has been "online" at skulpt.github.io/skulpt so I was just pushing changes and looking there.  Letting github do the lifting of running Jekyll to build the site.

I'll add this to my todo list so that we can all run it locally, and then make a PR.

**Comment by Dustyposa** [comment]
Hello，the new site is pretty than old site！
But I run an infinite loop code. The browser would be broken.
Like ```python
while 1:
    print(11111)
```
How can I solve it?

**Comment by rixner** [comment]
@bnmnetp I had some success updating the package dependencies individually to ```@latest``` and doing a ```bundle update```.  I'm not really sure if that was the right thing to do, though.  I don't use Ruby for anything so I am unfamiliar.  But, the web suggests that a ```bundle update``` updates everything to the latest versions, which might not be what you want.  It made massive changes to the ```Gemfile.lock``` file.

**Comment by bnmnetp** [comment]
@rixner, I just spent a while trying to get it to build on my machine.  I ran into a number of problems and missing pieces that were a bit frustrating.

I think I have it straightened out.  It may not be a Ruby/Jekyll experts perfect solution, but I'm not either of those things and don't really care to be.  I just want us to be able to build and test.

**Comment by rixner** [comment]
@bnmnetp is it something that you can commit so we can all build/test in the future?  Or is it something we'll all have to recreate?  As I said, I got it to work with something that isn't likely a "perfect" solution either after banging my head against the wall for hours.  (I also have no interest in becoming a Ruby/Jekyll expert!)

**Comment by bnmnetp** [comment]
@rixner -- sorry, the point of my post was to let you know that I had committed and pushed that to the gh-pages branch.

**Comment by rixner** [comment]
Sorry, should have checked!
