### ISSUE TITLE
Can I prohibited the raw_input by Sk.config?

### ISSUE THREAD

**Issue by Dustyposa** [skulpt/skulpt#890]
I want to prohibited  the raw_input , I know I can recompile skulpt to delete the `raw_input` keywords. Has any anther way?

**Comment by albertjan** [comment]
You could throw an error in your `inputfun` https://github.com/skulpt/skulpt/blob/master/src/env.js#L123

So use:
```
Sk.configure({
    // your other configure stuff,
    inputfun: function () { throw new Error("not implemented"); }
});
```

**Comment by Dustyposa** [comment]
This way will  prohibit input function. But I want to reserved keywords `input`, only delete `raw_input`. Because python3.

**Comment by albertjan** [comment]
Oh right what I think you can do is after your configure add: 

```
delete Sk.builtins.raw_input;
```

**Comment by Dustyposa** [comment]
Oh!! So clever. Thanks!!!!!
So good way, got it.
:)
