### ISSUE TITLE
A strange bug in turtle

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#891]
The turtle functions arguments length always one more than the actual arguments length.For example,if I print out the forward(100) argument:
`console.log(arguments)`
it will print out:
`Arguments(2) [100, undefined, callee: (...), Symbol(Symbol.iterator): ƒ]`
If I print out the color("red","yellow") arguments,it will print out:
`Arguments(5) ["red", "yellow", undefined, undefined, undefined, callee: (...), Symbol(Symbol.iterator): ƒ]`

First,the arguments is one more than actual.Second,the undefined value should not be there.

**Comment by bnmnetp** [comment]
@alexwenbj Check out the discussion for PR #850 It should shed some light on this for you.

**Comment by alexwenbj** [comment]
OK,thank you.@bnmnetp
