### ISSUE TITLE
Infinite loop make browser broken.

### ISSUE THREAD

**Issue by Dustyposa** [skulpt/skulpt#894]
The code:
```python
while 1:
    print(111)
```
i use skulpt in react. But I run this code, browser would be broken.
Similarly, [skulpt.org](http://skulpt.org) also have this problem.
How can i solve this problem?

**Comment by albertjan** [comment]
There are two avenues to solve this:

- execution timeout (cuts off skulpt execution if it takes longer then x milli-seconds) 
```
Sk.configure({
    ... your previous configures
    execLimit: 20000, // 20 seconds
});
```
- killableWhile/For this is slower (suspends skulpt every loop to let the browser do it's thing)
```
Sk.configure({
    ... your previous configures
    killableWhile: true,
    killableFor: true,
});
```

**Comment by Dustyposa** [comment]
got it. Thanks!
:)
