### ISSUE TITLE
How to get the "default" Turtle and its state?

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#895]
I tried to define Shape class for turtle in turtle.js file,and want to get the "default" Turtle(and its state) in Shape,How to get the "default" Turtle instance(it means use anonymous turtle) in turtle.js file.
Thank you in advance.

**Comment by bnmnetp** [comment]
Check out the use of ensureAnonymous in the turtle.js source.

**Comment by alexwenbj** [comment]
@bnmnetp Got it,Thank you!
