### ISSUE TITLE
ECMAScript Version

### ISSUE THREAD

**Issue by rixner** [skulpt/skulpt#896]
The closure compiler is a transpiler, so we can tell it what version of ECMAScript we want it to output.  I think the reasonable options are ECMASCRIPT 5 or ECMASCRIPT 2015.  If we all agree, I can make a trivial pull request to explicitly set the output language.  This will then set the stage for us to use more modern Javascript in the code base without breaking our browser compatibility.  (Note that given that we are already using the closure compiler, there is no need for us to add babel to the build process in order to allow us to write more modern Javascript.)

I will point out, though, that the libraries do **not** go through the closure compiler.  So, they get placed in ```skulpt-stdlib.js``` as-is (though they now get minified).  It likely behooves us to figure out a strategy to transpile the libraries to the same target ECMAScript version as the core of Skulpt....

**Comment by bnmnetp** [comment]
I would certainly cast my vote for ES6.

The libraries are going to be even more tricky because they are a mixture of python and js.  We should figure that out separately from whether we move to ES6 as it will definitely not be trivial.

**Comment by LeszekSwirski** [comment]
+1 to more modern code, particularly since then a Skulpt embedder can choose to have a different compilation target than the default (if e.g. they don't care about IE11) and get better/smaller code as a result.

**Comment by albertjan** [comment]
@bnmnetp the in language should be as high as it will go if you ask me. 

The out language, I'm ok with 2015, but we should be able to do a devbuild that builds to es5 for ie11. Because I know for a fact @trinketapp will want to keep supporting ie11 for a while. I don't know about you @bnmnetp what's your % of users on ie11?

**Comment by albertjan** [comment]
@LeszekSwirski we'll have to start using those new features too right? 😄 Because I think that the codebase is mostly es3 with maybe a few accidental es5 features.

**Comment by LeszekSwirski** [comment]
Well yes :) But imagine the cleanup you'd be able to do with rest parameters alone!

**Comment by albertjan** [comment]
![](https://i.imgflip.com/32q2w9.jpg)

**Comment by bnmnetp** [comment]
@albertjan IE accounts for only 1.3% of the traffic to runestone.

**Comment by rixner** [comment]
Based on this conversation, it seems like everyone is good with ECMAScript 2015 as the default output language?  The question, then, is whether people should just manually change that on their own (by editing ```webpack.config.js```) if they need a different build?  Or if we should provide some sort of flag command to either select among a few options or allow one to specify an arbitrary output language (that the closure compiler supports)?

Unfortunately, though, when I tell it to use ECMASCRIPT2015 as the output language, I get:

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)

With so little information, I have had trouble tracking this down so far.

**Comment by albertjan** [comment]
@rixner that's from jshint. try turning that off, jshint might not be able to understand es2015. but that's odd because it should run on the input not the output.

**Comment by albertjan** [comment]
@rixner https://github.com/facebook/create-react-app/issues/4458 did you see this?

**Comment by albertjan** [comment]
yeah if I set `languageOut: 'ECMASCRIPT_2015'` it works for me

**Comment by rixner** [comment]
@albertjan I hadn't seen that one, but it doesn't solve my problem.  Nothing I've found does and it's repeatable on different computers.  I really don't understand what's happening.

**Comment by rixner** [comment]
Got it working.  Had to just reboot/reinstall everything. Reboot the computer, blow away node_modules, ...

Hopefully, it doesn't come back.  So, back to my question: do we want to just set it to ECMASCRIPT_2015, and let others modify it locally, or create some sort of build option?

**Comment by rixner** [comment]
Would it be too cumbersome to make it default to ECMASCRIPT_2015, but you could override it with whatever valid string that the closure compiler accepts as follows:

```
$ npm run build
...
$ npm run build -- --env.languageOut=ECMASCRIPT5
...
$ npm run build -- --env.languageOut=ECMASCRIPT_2019
```

**Comment by bnmnetp** [comment]
As long as there is some clear documentation that will tell you what the option should be.  I personally have no clue what the `--` means between `build` and  `--env`.  I naively typed `npm run build --help` to see if that told me about options to build but that didn't give me anything useful.  

I definitely need to get up to speed on the whole npm way of life.

**Comment by rixner** [comment]
@bnmnetp yeah, that's not something I necessarily wanted.  The way it works is that the ```--``` starts the options that get passed to the command that npm runs, instead of to npm itself.  So, the ```--env``` option is being sent to the command that build runs (which is webpack), not to npm.  Personally, I think it's pretty cumbersome and it makes it unpleasant to pass options.

One alternative is to add ```npm run build-es5```, ```npm run build-es19```, etc.  I'd basically just make those commands hide the clunky syntax.  In some ways that limits you to the language variants we pick ahead of time, but you could always also just use the clunky syntax to pass anything.

**Comment by bnmnetp** [comment]
I think that if we put something in our documentation about how to build for different versions of ECMASCRIPT and give a couple of examples than we should be good, or have it documented in `npm run help`

**Comment by rixner** [comment]
I added, hopefully clear, documentation in ```npm run help```.

An alternative would be to set an environment variable or have some sort of configuration file, so that everyone can use their own default and just run ```npm run build```.  That seems like a reasonable approach, as well, but requires a little upfront effort to set up the configuration in the beginning.

For instance, is this something that gets commonly used for this sort of thing?

https://www.npmjs.com/package/config

**Comment by rixner** [comment]
On further consideration, that's probably too heavy-weight for what we need.  Something simpler (like https://www.npmjs.com/package/conf.js) is likely sufficient.  However, I'd be inclined to let everyone try it without such a thing and see if one of us comes up with a better idea as we see how everything fits our workflows.

**Comment by albertjan** [comment]
Let's leave it at this for now. We might want to build all a few versions and push them to skulpt-dist at some point. I expect most people to not be building their own versions of skulpt 😄
