### ISSUE TITLE
Processing

### ISSUE THREAD

**Issue by cgibin** [skulpt/skulpt#898]
Hello guys. Whats the state of it? The http://skulpt.org/static/proctest.html link is broken

**Comment by Dustyposa** [comment]
Oh I think change main site, forgot the files route. Maybe doc's file can use.

**Comment by albertjan** [comment]
@cgibin it still here in the repo: https://github.com/skulpt/skulpt/blob/master/doc/static/proctest.html

**Comment by bnmnetp** [comment]
As far as I can tell there were never any links on skulpt.org that pointed to proctest.html or any of the other files including the word `test` that lived in static.  As the name suggests these files were mainly there for testing features and integrations of skulpt.

I was going to make a PR today to clean up the old doc folder now that we are off of GAE.

@albertjan What do you think?  Should I preserve some of these xxxtest.html files?

**Comment by cgibin** [comment]
I don't remember how I got there, but google indexed that too http://webcache.googleusercontent.com/search?q=cache:KlPS93m5puYJ:www.skulpt.org/static/proctest.html
Also the web is polluted with "skulpt.org/static/" links. And all the examples are broken, since they using /static/skulpt.min.js
Even example on skulpt.org/using.html is not working.

**Comment by bnmnetp** [comment]
I've updated the gist to point to the correct location.  The skulpt.org/static folder was never meant to serve as a CDN for people to include any of the `skulpt.*.js` files, They are available under the js folder now as shown in the updated gist.  

Google search will sort itself out in time.  We are not the first to restructure a website.  But if lots of people think that backward compatibility to old stuff in /static is important that can be arranged.

**Comment by cgibin** [comment]
Thanks for clarification. I find it very strange what skulpt hides processing so deep. It adds great value to the skulpt and I think it would be nice to have easy accessible examples of its use. More content, more backlinks, more exposure

**Comment by bnmnetp** [comment]
Well, there is only so much time... I would welcome a PR against the gh-pages branch that highlighted our processing integration.

**Comment by rixner** [comment]
I don't know what to do about backward compatibility.  But, moving forward, it seems like we should have some explicit instructions about how to load Skulpt in examples or applications.  It should politely ask not to link to assets on Skulpt.org but instead to perhaps use a CDN (like [jsdelivr](https://www.jsdelivr.com/)) against the skulpt/skulpt-dist repo.  That would also allow people to use semantic versioning if they want.
