### ISSUE TITLE
The ondrag() function can't distinguish different Turtle instance

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#899]
Run the python demo code:
`https://github.com/python/cpython/blob/master/Lib/turtledemo/colormixer.py`,Skulpt `ondrag()` can't distinguish the different turtles.Drag one turtle,the other two will response too.

**Comment by alexwenbj** [comment]
Workaround:
Modify the turtle.js, replace from line 368 to 377 with code below:
                   ```
if (type === "mousemove" && managers[i].canMove() && managers[i].test(x, y, localX, localY)) {
                        managers[i].trigger([localX, localY]);
                    }
                    else if(type==="mousedown" && managers[i].test(x, y, localX, localY)){//For onclick event
                        managers[i].trigger([localX, localY]);
                    }
```

**Comment by albertjan** [comment]
Hey @alexwenbj can you do a PR for that please 😄 🙏

**Comment by Dustyposa** [comment]
please 🙏 @alexwenbj

**Comment by alexwenbj** [comment]
@albertjan I am not very sure it is a perfect solution.

**Comment by bnmnetp** [comment]
@alexwenbj it doesn't have to be perfect, as long as it is an improvement.
