### ISSUE TITLE
Inheritance of class variables in codeskulptor Python 3

### ISSUE THREAD

**Issue by ReblochonMasque** [skulpt/skulpt#902]
Class variables have a behavior inconsistent with cpython:

```python:
class temp:
    a = 1
    def f(self):
        pass

class c1(temp):
    def f(self):
        print(self.a)

class c2(temp):
    def f(self):
        print(self.a)

o1 = c1()
o2 = c2()
o1.f()
o2.f()
temp.a += 1
o1.f()
o2.f()
```
output in cpython 3:

```
1
1
2
2
```

output in [codeskulptor](https://py3.codeskulptor.org/#user303_k0d3VGXmjN_0.py) 

```
1
1
1
1
```

**Comment by s-cork** [comment]
this doesn't seem to be a current issue in skulpt - no problems with running the code on the website.

**Comment by ReblochonMasque** [comment]
A case of *"wait long enough and it will go away"*!
