### ISSUE TITLE
Byte Literals

### ISSUE THREAD

**Issue by rixner** [skulpt/skulpt#909]
I know we don't have a ```bytes``` type, yet, but I feel like this behavior could be better:

Program:
```
a = "abc"
print(a)
print(type(a))
c = b"abc"
print(c)
print(type(c))
d = r"abc"
print(d)
print(type(d))

```

Output:

```
abc
<class 'str'>
"abc
<class 'str'>
abc
<class 'str'>
```
It parses into a string, but not correctly.  Given that the "r" prefix works okay, I'm not sure why "b" is working out differently.

**Comment by meredydd** [comment]
Paging @albertjan - this is one for you, while you're next playing with that piece of the parser (*cough\*f-strings\*cough\*) :)

**Comment by rixner** [comment]
To be clear, I'm not asking for someone to implement the ```bytes``` type.  I just want the parser to parse it correctly so that we/someone else can.  I couldn't easily see what needed to be fixed.

**Comment by albertjan** [comment]
@rixner that's probably something I did wrong in the tokeniser.
