### ISSUE TITLE
Freshly built skulpt by master branch can not print Chinese

### ISSUE THREAD

**Issue by fatpandaria** [skulpt/skulpt#919]
+ how to repeat: pull the most recent master branch(at least until today 06262019 not fixed), run the `npm run dist` under *unix systeam because under windows there is a compiling problem.Or you can just try it out here http://skulpt.org/ (this should be the fresh one telling from its behaviour),while the one in this page  http://skulpt.org/using.html can still print Chinese(should be the old version). Then you just call `print('中文')`;
+ what is expected by calling `print('中文')` : it should just output 中文 according to the pycharm
+ what I saw : instead of the correct output ,there is an error being thrown out `SyntaxError: invalid string (possibly contains a unicode character) on line 1`;
+ after a global search of the `invalid string`, I located at the ast.js `function parsestrplus` ,which is a quite aged function, so maybe there is something wrong with the decode or encode of the input of the `print` function?

**Comment by bnmnetp** [comment]
I changed the settings on the skulpt homepage and your example works fine now.

**Comment by fatpandaria** [comment]
@bnmnetp so what kind of setting?Is the homepage skulpt built from the new master code?Because I am trying to implement a custom input and use open() function.I am stucked here because my old skulpt hasn't implemented open() with a file name ,so I merged the most recenlty master code and it turned out to be unable to print Chinese.I saw the example on Using Skulpt page (hosted on trinket),which is just what I want but I don't know how to get the source code.Do you have any suggestion?Thanks.

**Comment by fatpandaria** [comment]
@bnmnetp  Thanks , adding __future__:Sk.python3 works for me .

**Comment by callblueday** [comment]
```
Skuplt.configure({
        output: outf,
        read: builtinRead,
        __future__: Skuplt.python3
});
```
