### ISSUE TITLE
customize input() alert fail

### ISSUE THREAD

**Issue by viewerw** [skulpt/skulpt#928]
Can't customize the input（）alert  by this method?https://github.com/skulpt/skulpt/issues/685
config:
```
 Sk.configure({
            output: handleOutput,
            read: builtinRead,
            __future__: Sk.python3,
            execLimit: 60000,
            killableWhile: true,
            killableFor: true,
            timeoutMsg: () => '运行超时',
            nonreadopen: true,
            filewrite,
            fileopen,
            inputfun: showInput,
            inputfunTakesPrompt: true,
        });
showInput:

function showInput(prompt) {
    return new Promise((resolve, reject) => {
        resolve('1000');
        // Prompt({
        //     title: prompt,
        //     onOk: value => {
        //         resolve(value);
        //     },
        // });
    });
}
when run ,it caused err: valueError unknow

**Comment by albertjan** [comment]
are you running the latest version?

**Comment by albertjan** [comment]
Have a look at this:  https://jsbin.com/sixuvixasa/edit?js,console

**Comment by viewerw** [comment]
> are you running the latest version?

yea,the newest version

**Comment by viewerw** [comment]
> Have a look at this: https://jsbin.com/sixuvixasa/edit?js,console

change inputfun to inputFun? sadly not work

**Comment by albertjan** [comment]
But my example works right? What is different between my setup and yours?

**Comment by viewerw** [comment]
> Have a look at this: https://jsbin.com/sixuvixasa/edit?js,console

if you change the 'inputFun' to 'inputfun',the demo will not work,
I have read the resource code in 'env.js' about **sk.configure** ,the 'option' paramater dont have the'inputFun' field,just have 'inputfun',  so, it's a bug ,reply me pls

**Comment by viewerw** [comment]
> But my example works right? What is different between my setup and yours?
if you change the 'inputFun' to 'inputfun',the example will not work,

**Comment by albertjan** [comment]
No hahah thats because skulpt looks for a function called inputFun.

**Comment by viewerw** [comment]
skulpt looks for a function called inputfun not inputFun

**Comment by viewerw** [comment]
code here https://github.com/skulpt/skulpt/blob/master/src/env.js#L134

**Comment by albertjan** [comment]
Hey @viewerw sorry! You're absolutely right I've updated the example! see: https://jsbin.com/mofupilaso/edit?js,console

**Comment by viewerw** [comment]
> Hey @viewerw sorry! You're absolutely right I've updated the example! see: https://jsbin.com/mofupilaso/edit?js,console

it's not work right, there is no prompt in the window when I click run .Have you try to run this example?

**Comment by albertjan** [comment]
Right that didn't save, it should be window.prompt not window.query

**Comment by viewerw** [comment]
> Right that didn't save, it should be window.prompt not window.query

Even if window.prompt is used, the console does not print the input string.

**Comment by viewerw** [comment]
```
Sk.configure({
  read: function (filename) {
    console.log("file: " + filename);
    
    if (Sk.builtinFiles && 
        Sk.builtinFiles.files && 
        Sk.builtinFiles.files[filename] && 
        ignoredBuiltins.indexOf(filename) === -1) {
      console.log('builtin: ' + filename);
      return Sk.builtinFiles.files[filename];
    }
    
    throw new Error("not found");
  },
  write: function (str) {
    console.log(str);
  },
  inputfunTakesPrompt: true,
  inputfun: function(f) {
    return new Promise(function (resolve) { resolve(1000); });
  }
});
```
whats wrong with this code,why did the console not print 1000?

**Comment by albertjan** [comment]
Hi sorry for the delay here's the solution: https://jsbin.com/lutoyubefo/1/edit?js,console

I forgot to make sure we reentered the suspended program. When your program suspends you have to wrap the call to `importMainWithBody` with `asyncToPromise`.

```
Sk.asyncToPromise(function() {
    Sk.importMainWithBody(
        '__main__', 
        false,
        "print raw_input('x')",
        true 
    );
});
```

**Comment by viewerw** [comment]
hi ,its not work in python3,
try configure  __future__: Sk.python3, the example fail

**Comment by albertjan** [comment]
that's because it uses the `print` statement see here: https://jsbin.com/tawoxucero/edit?js,console
