### ISSUE TITLE
With new Skulpt,turtle register_shape() will raise error:wrapperFn() takes 0 positional arguments but 1 was  given 

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#931]
With this new version of Skulpt,the turtle register_shape() function will raise an error:`wrapperFn() takes 0 positional arguments but 1 was  given`.It is OK before the July version.The register_shape() invocation is as below:
`register_shape("football.png")`

**Comment by alexwenbj** [comment]
It should add the co_varnames for the register_shape() function:
`proto.$register_shape.co_varnames = ["name", "points"];`

**Comment by viewerw** [comment]
thank you for saving my time!
