### ISSUE TITLE
Where I can get the python version of the lib image?

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#932]
Hi guys,Where can I get the python version of image module?(`src/lib/image.js`)?I searched the web,but i failed to find it.
Thank you.

**Comment by alexwenbj** [comment]
cImage?`https://github.com/schellenberg/cImage`

**Comment by bnmnetp** [comment]
Yes, the schellenberg link is a fork from the original cImage that I wrote.  I need to bring a few of his modifications back to the original as it makes it more compatible with image.js. Each have grown in their own way over time and there has been some drifting apart.

**Comment by alexwenbj** [comment]
@bnmnetp Great!Maybe we also need to bring more features to image.js,such as toList()/clone()/ListImage and so on.

**Comment by alexwenbj** [comment]
Add some features according the cImage. #933

**Comment by alexwenbj** [comment]
@bnmnetp I reviewed the cImage.py source, and there is a question:why don't add the alpha support for it?
