### ISSUE TITLE
Multiple Decorator Support

### ISSUE THREAD

**Issue by acbart** [skulpt/skulpt#940]
I was thinking about teaching dataclasses this fall, but it looks like class decorators aren't implemented. They're parsed and have some partial compilation it seems. It looks like the basic idea would be the following changes in `cclass` of `compile.js`:
1. Uncomment the `vseqexpr` to have the decorators evaluated: https://github.com/skulpt/skulpt/blob/ac2d8cd0ba141f7c7588fe6eecd15c779bf8f5fa/src/compile.js#L2249

2. Assign the decos to a new `$decorators` list (like `buildcodeobj` does): https://github.com/skulpt/skulpt/blob/ac2d8cd0ba141f7c7588fe6eecd15c779bf8f5fa/src/compile.js#L2040

3. Near the end of the build process, call the decorators iteratively with `callsimOrSuspendArray` passing in the created class scope variable: https://github.com/skulpt/skulpt/blob/ac2d8cd0ba141f7c7588fe6eecd15c779bf8f5fa/src/compile.js#L2104

I also observe that multiple decorators still aren't supported. Casually, that seems like it would just require outputting a series of decorator calls one after the other, passing in the results repeatedly. So wrapping that last line in a loop, basically

All of this was mentioned in #428 (closed), but I think it needs to be restated. I considered posting in #400 but that seems pretty old. Perhaps it is time to create a new version of that Master Coordination Issue to track these kinds of things, or would you prefer I keep raising individual issues?

**Comment by albertjan** [comment]
I think #428 gave us some decorators and we were happy with that, that's why we closed it. Let's make this the ticket where we track multiple decorators. I don't think it will be trivial to add though because we would have done that back then. 😄

**Comment by meredydd** [comment]
Fixed in #977
