### ISSUE TITLE
Why are staticmethod.py, classmethod.py, and property.py python files and not JS?

### ISSUE THREAD

**Issue by acbart** [skulpt/skulpt#942]
I was curious if there was a reason why those three files (`staticmethod.py`, `classmethod.py`, and `property.py`) were implemented as python files and not JavaScript files? For example, couldn't you write `staticmethod.py` as `staticmethod.js` as something like:

```javascript
var $builtinmodule = function (name) {
    let mod = {};
    mod.staticmethod = Sk.misceval.buildClass(mod, function($gbl, $loc) {
        new Sk.builtins.str('Emulate PyStaticMethod_Type() in Objects/funcobject.c')
        var ___init__ = new Sk.builtin.func(function(self, f) {
            Sk.abstr.sattr(Sk.misceval.loadname('self', $gbl), Sk.builtins.str('f'), Sk.misceval.loadname('f', $gbl), true);
        }});
        ___init__.co_varnames = ['self', 'f']
        ___init__.$defaults = []
        $loc.__init__ = ___init__
        var ___get__ = new Sk.builtin.func(function(self, obj, objtype) {
            return Sk.abstr.gattr(Sk.misceval.loadname('self', $gbl), Sk.builtins.str('f'), true);
        }});
        ___get__.co_varnames = ['self', 'obj', 'objtype']
        ___get__.$defaults = [Sk.builtin.none.none$]
        $loc.__get__ = ___get__
    }, 'staticmethod', [Sk.misceval.loadname('object', $gbl)], {});
    return mod;
};
```

Wouldn't this be faster, less require load-up time, and better match the other files that are in the core?

**Comment by albertjan** [comment]
We could and it would probably be faster, but at the time we decided to use the pure python implementations because we were much more certain they were correct and it was faster to add them this way.

**Comment by acbart** [comment]
Definitely makes a lot of sense, and probably what I would have done too. I'm not at all confident in my example code, for instance. At some point, I'll probably try and port them over in a PR - assuming I can finish my stuff in a timely fashion!

**Comment by s-cork** [comment]
I've made versions of these that use the skulpt architecture. I will hopefully add them to #1092 

Though I'm probably a little far off a serious PR yet.
