### ISSUE TITLE
enumerate() method not support "start" argument name

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#954]
For example:
```
grocery = ['bread', 'milk', 'butter']
enumerateGrocery = enumerate(grocery, start = 10)
print(list(enumerateGrocery))
```
will raise an JS exception:`<native JS>() got an unexpected keyword argument 'start'`.

**Comment by alexwenbj** [comment]
@Dustyposa It seems your fix to this issue still not works for me.Have you tested it?Thank you.

**Comment by Dustyposa** [comment]
@alexwenbj can you share your test code? I add the code in test directory.

**Comment by alexwenbj** [comment]
Just I listed in this issue:
```
grocery = ['bread', 'milk', 'butter']
enumerateGrocery = enumerate(grocery, start = 10)
print(list(enumerateGrocery))
```
Thank you.

**Comment by Dustyposa** [comment]
@alexwenbj Did you can run cmd `npm run dist` and pass all test?  
I can't pass 
```Tests failed in  CounterTests.test_most_common
Ran 5 tests, passed: 4 failed: 1
```

**Comment by alexwenbj** [comment]
I didn't use the new test case,just add your code to the enumerate.js,it passed and generated the built dist file.

**Comment by Dustyposa** [comment]
emm..now I can't build dist file..I don't know way..I can't past all test. 
And even I only clone the master branch, then run `npm run dist`, didn't add any code.
It's so sad....

**Comment by alexwenbj** [comment]
Run `npm install `first? @Dustyposa

**Comment by Dustyposa** [comment]
@alexwenbj Only have one test can't pass, 
```
Tests failed in  CounterTests.test_most_common
Ran 5 tests, passed: 4 failed: 1
```

**Comment by alexwenbj** [comment]
No idea for that...

**Comment by Dustyposa** [comment]
Your Skulpt is latest version?

**Comment by alexwenbj** [comment]
Not the latest version.I cloned it in July.

**Comment by Dustyposa** [comment]
@alexwenbj  Sorry,It's a sand news,, my env have some thing wrong. Tomorrow, i use another computer to add test example.

**Comment by Dustyposa** [comment]
@alexwenbj 
https://github.com/Dustyposa/skulpt/blob/af73ebfdeec61f19f5bed2df26912651bec9a514/test/unit3/test_enumerate.py#L98-L101
I add your eg in test, and can pass it, how about update a new version for you application.

**Comment by alexwenbj** [comment]
@Dustyposa Thank you.Did you test in your browser code?I can pass the test case but can't get the correct result in browser.

**Comment by Dustyposa** [comment]
@alexwenbj Yes, it's work fine. 
You can clone skulpt in my warehouse. And test it.

**Comment by alexwenbj** [comment]
OK,Thank you.@Dustyposa
