### ISSUE TITLE
Why can't pass all test in my computer?...

### ISSUE THREAD

**Issue by Dustyposa** [skulpt/skulpt#956]
I clone a latest version in my computer, then i run the cmd
```shell
cd skulpt
npm install
npm run dist
```
But always can't pass a test.
```
Fail: Expected [('l', 5), ('e', 4), ('o', 3), ('r', 2), ('h', 2), (' ', 2), ('!', 2), ('d', 1), ('w', 1), ('u', 1), ('n', 1), ('i', 1), ('v', 1), ('s', 1)] to equal [('l', 5), ('e', 4), ('o', 3), ('h', 2), (' ', 2), ('r', 2), ('!', 2), ('w', 1), ('d', 1), ('u', 1), ('n', 1), ('i', 1), ('v', 1), ('s', 1)]
Tests failed in  CounterTests.test_most_common  
Ran 5 tests, passed: 4 failed: 1

```
Only this test can't pass..I have no idea...
And I run the same cmd in other computer, it's fine..
My env make this error? The reason is ? :(

**Comment by albertjan** [comment]
Ah yes probably, what version of node have you got there?

**Comment by Dustyposa** [comment]
The latest, `12.9.1`  
Does it seem that I need to use "10.xx.x"?

**Comment by Dustyposa** [comment]
thanks `v10.16.3` solve it.
