### ISSUE TITLE
Python3 printing syntax is not supported

### ISSUE THREAD

**Issue by yzxnwj** [skulpt/skulpt#958]
print('a',end="@") error   but i look print.js Python3 printing syntax is supported.   why?

 thanks

**Comment by yzxnwj** [comment]
> print('a',end="@") error but i look print.js Python3 printing syntax is supported. why?
> 
> thanks

**Comment by wensonH** [comment]
@yzxnwj I try your code manually, and the result is right. Perhaps something wrong in your code?

**Comment by ebertmi** [comment]
Have you enabled the python3 mode?

**Comment by yzxnwj** [comment]
thanks I've found the problem    python3 mode  error  I reintroduced the file
