### ISSUE TITLE
Cyrillic breaks with control characters.

### ISSUE THREAD

**Issue by piterskikhsa** [skulpt/skulpt#965]
Cyrillic breaks when I write control characters.
`print('yjdf')
print('новая планета')
print('новая планета \n asdasda')
print('тест2')
print(r'новая планета \n новая плантеа2')
print('тест3')
print('cjdctv yjdfz  \n asdasda')
print('тест4')
print(r'новая планета \t новая плантеа2')
print('''тест 
тест2
тест3''')`

![Снимок экрана от 2019-09-17 12-34-49](https://user-images.githubusercontent.com/24404628/65030231-d9b60180-d947-11e9-9f39-69a73b880fd5.png)

**Comment by alexwenbj** [comment]
Maybe you should use print(u'...\t...') rather than print(r'...')

**Comment by alexwenbj** [comment]
And,the newest version should have fixed the issue,see #873

**Comment by albertjan** [comment]
Yeah this was fixed in this PR: #924 we should update the website.
