### ISSUE TITLE
Three-Argument version of type() doesn't work

### ISSUE THREAD

**Issue by l4mpi** [skulpt/skulpt#97]
In this example code, the class definition and the `type` call should produce identical classes:

```python
class c(object): x = "bar"
#c = type("c", (object, ), {"x":"bar"})
i = c()
print c, "\n", i, "\n", dir(c)
print "attr:", c.x, i.x
```
The output using the class statement is as expected:
```
<class '__main__.t'>
<__main__.t object>
['__module__', 'x']
attr: bar bar
```
Uncommenting the `type` call yields a dramatically different result:

```
<class '[object Object]'>
<[object Object] object>
['9', 'get', 'has_key', 'items', 'keys', 'size', 'values']
attr:
```

I've tried a few more variations of `type` calls, e.g. using an empty tuple for the base classes, and none of them worked, all producing a class with the representation `<class '[object Object]'>`.

**Comment by waywaaard** [comment]
I just debugged into this, seems that the dict is not the same format as it would be used with the class keyword:

in type.js 
```
for (v in dict) {
    klass.prototype[v] = dict[v];
    klass[v] = dict[v];
}
```

When I am using the given code snippet this loop creates a attribute called '3', though it should access the dict.items and use the lhs and rhs. Seems that the dict does not get unwrapped here.

**Comment by waywaaard** [comment]
Ok got a fix for this behavior:

```python
        // this checks if the dict has been already successfully unwrapped
        // in case of creating classes with class keyword, skulpt automatically
        // unwrap the arguments and sets the module in the buildClass function
        if(dict["tp$name"] && dict["tp$name"] === "dict") {
          var it, k;
          for (it = dict.tp$iter(), k = it.tp$iternext(); k !== undefined; k = it.tp$iternext()) {
            v = dict.mp$subscript(k);
            if (v === undefined) {
              v = null;
            }
            klass.prototype[k.v] = v;
            klass[k.v] = v;
          }

          // set __module__
          dict["__module__"] = Sk.globals["__name__"];
        } else {
          for (v in dict) {
              klass.prototype[v] = dict[v];
              klass[v] = dict[v];
          }
        }

        // checks if name is builtin type of js object
        if(Sk.builtin.checkString(name)) {
            name = name.v;
        }

        // unwrap bases if required
        if(bases["tp$name"] && bases["tp$name"] === "tuple") {
            bases = bases.v;
        }
```

The type() builtin arguments get automatically unwrapped when building a class. If you call type() directly the arguments do not get unwrapped. The above snippet can fix this. However I would be feasible to add a proper check for the ```bases``` argument, hence it has to be of the type tuple.

Another thing that I've noticed is, that the ```dir(c)``` behaves not similiar to cpython. It omits attributes in skulpt.

**Comment by LeszekSwirski** [comment]
First of all, good job debugging this! The fix you have is functional, but IMHO overengineered. `type` is a Python function, so both the `bases` and `dict` arguments should be Python types, and should be operated on using their Python APIs. Any instances where `type` is passed Javascript objects should be considered a bug.

**Comment by waywaaard** [comment]
That's correct, however I do not know why the compiler does not pass python types to the type() builtin. Though at least the new added checks are still missing in this function.

**Comment by waywaaard** [comment]
Issue can be closed.
