### ISSUE TITLE
Itertools not implemented

### ISSUE THREAD

**Issue by yashaslokesh** [skulpt/skulpt#971]
It seems that `itertools` hasn't been implemented yet, I checked in `src/lib/` and there was no `itertools.py`. Am I looking in the right place?

I can start work on this if `itertools` really has not been implemented, yet.

**Comment by alexwenbj** [comment]
Yeah, according to the README, functools and itertools are not yet implemented.It is a nice work to implement it.

**Comment by s-cork** [comment]
i've had a go at starting this - if anyone wants to join you can find the branch I'm working on here:
https://github.com/s-cork/skulpt/tree/pr/itertools

changes:
(https://github.com/skulpt/skulpt/compare/master...s-cork:pr/itertools)

At this time I have:
- count w/tests
- islice w/tests

**Comment by alexwenbj** [comment]
@s-cork Thanks for your contributions. Here are some itertools written in JS/ES, maybe you can get some inspiration from them, just FYI:
https://github.com/iter-tools/iter-tools
https://www.npmjs.com/package/iter-tools
https://github.com/abozhilov/ES-Iter

**Comment by s-cork** [comment]
thanks @alexwenbj  - i'll take a look - current workflow is - look at the python version of the function in the [docs](https://docs.python.org/3/library/itertools.html) and then try to translate that.

There's basically two parts. The set-up (check all the args) and then the generator. 
It seems a Skulpt generator is a bit like a recursive function so there's a lot of mentally converting a python generator that typically has a looping structure into a recursive function. 

Once that's tackled - the conversion is straightforward enough.  

### Count

#### Looping
```python
def count(start=0, step=1):
    # count(10) --> 10 11 12 13 14 ...
    # count(2.5, 0.5) -> 2.5 3.0 3.5 ...
    n = start
    while True:
        yield n
        n += step
```

#### Intermediary Recursion Style for sculpt 
```python
def _count_gen(**gen):
    n = gen['n']
    step = gen['step']
    yield n
    n += step
    gen['n'] = n
    count_gen(**gen)

def _count(start=0, step=1):
    # check args 
    n = start
    count_gen(n=n, step = step)

count = _count
```

#### Skulpt
```javascript
   var _count_gen = function ($gen) {
        const n = $gen.gi$locals.n;
        const step = $gen.gi$locals.step;
            try {
                return [ /*resume*/ , /*ret*/ n];
            } finally {
                $gen.gi$locals.n = Sk.abstr.numberInplaceBinOp(n, step, "Add");
            }
    };

    var _count = function (start, step) {
        Sk.builtin.pyCheckArgsLen("count", arguments.length, 0, 2);
        Sk.builtin.pyCheckType("start", "number", Sk.builtin.checkNumber(start));
        Sk.builtin.pyCheckType("step", "number", Sk.builtin.checkNumber(step));
        const n = start;
        return new Sk.builtin.generator(_count_gen, Sk.$gbl, [n, step]);
    };
    _count.co_name = new Sk.builtins.str("count");
    _count.$defaults = [new Sk.builtin.int_(0), new Sk.builtin.int_(1)];
    _count.co_varnames = ["start", "step"];
    _count_gen.co_name = new Sk.builtins.str("count");
    _count_gen.co_varnames = ["n", "step"];

    mod.count = new Sk.builtin.func(_count);

```



i've done `cycle` now, `repeat` should be easy enough...

**Comment by alexwenbj** [comment]
@s-cork All of these js libs are inspired by the Python.Maybe the best solution is use one of them as external lib for Skulpt, and implement a lib base on it for Skulpt.
Good luck!

**Comment by albertjan** [comment]
@s-cork you're on fire 🔥 . I don't think any of those libs could be a drop in replacement for this, but there might be inspiration to be found 😄

**Comment by s-cork** [comment]
@albertjan my current issue that I'm facing...

I see that actually all the functions in the itertools module are not functions but classes... who new!
```
for t in dir(itertools):
  print(getattr(t))

# prints the following
<class 'itertools.chain'>
<class 'itertools.count'>
<class 'itertools.cycle'>
<class 'itertools.islice'>
<class 'itertools.repeat'>
```

Whereas I'm working with `Sk.builtin.func` so my version of the itertools module looks like
```
for t in dir(itertools):
  print(getattr(t))

# prints the following
<function chain>
<function count>
<function cycle>
<function islice>
<function repeat>
```

Should I change how I construct the functions so that they're classes instead?

I think I can probably piece this together from a couple of examples in the `re.js` module maybe...

**Comment by s-cork** [comment]
update on the above question: since `zip` is a function in skulpt and not a class, i'm gonna stick with functions too.

**Comment by albertjan** [comment]
yeah having the functionality is more important then the exact correct type.

**Comment by s-cork** [comment]
I think the Pull Request #1020 is ready for review 😄
