### ISSUE TITLE
Promise in inputfun causes error

### ISSUE THREAD

**Issue by ThomasDumazet** [skulpt/skulpt#980]
Hello,
I want to change the behavior of the input function so that I use my own.
I have added `inputfun: myFunction` and `inputfunTakesPrompt: true` to `Sk.configure`.
Then I have generated `myFunction`.
When I run Skulpt with Python code containing an `input()`, `myFunction` is called.
Till there everything works well.
But when `myFunction` returns a Promise, it causes an error and the message 

> SuspensionError: Cannot call a function that blocks or suspends here on line 1

is displayed.
I don't know why it doesn't work, I have seen that it should work (issue #685 for example).

The skulpt I am working on has been set up on July 2019.

Thank you for your help and your great work.

**Comment by Dustyposa** [comment]
Can we see your code that about `Sk.configuration` and the function `myFunction`.

**Comment by ThomasDumazet** [comment]
You can see it there : 
https://gist.github.com/ThomasDumazet/16a417bb85a9e7d22cff1db2032aad4e

**Comment by albertjan** [comment]
Make sure you set `canSuspend` to true in your `importMainWithBody` see: https://github.com/skulpt/skulpt/blob/master/src/import.js#L436

```is
Sk.importMainWithBody("__main__", 'print(input(">>>"))', false, true);
// this --------------------------------------------------------^
```

**Comment by ThomasDumazet** [comment]
Your solution works perfectly.
Thank you for your help ;)
