### ISSUE TITLE
Float conversion no longer matches Python 3

### ISSUE THREAD

**Issue by gdagrove** [skulpt/skulpt#981]
Using latest version of Skulpt, when I try `print(1/2)` it gives 0 instead of 0.5, and print(1.0/2.0) gives 0.5.

However, my local Python gives 0.5 with an implicit conversion to floating point number:

```
Python 3.7.5 (default, Nov  1 2019, 02:16:32)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print(1/2)
0.5
```

This behavior was working on older versions of Skulpt.

**Comment by albertjan** [comment]
@gdagrove what does your `Sk.configure` look like?

**Comment by gdagrove** [comment]
@albertjan My config has`python3: true`, but `python3: false` gives me the same result.

**Comment by gdagrove** [comment]
@albertjan The issue can also be reproduced in the REPL on the master branch of this repository by running `yarn repl`.

**Comment by gdagrove** [comment]
Found another test case. `print(10/10)` gives `1` in Skulpt (an integer) but `1.0` in Python 3.7 (a float).

**Comment by gdagrove** [comment]
Turns out I wasn't in Python 3 mode, I switched my config to add `__future__: Sk.python3,` and now everything works as expected

**Comment by albertjan** [comment]
I was just about to put that here! Glad you figured it out!
