### ISSUE TITLE
working with kwargs

### ISSUE THREAD

**Issue by s-cork** [skulpt/skulpt#999]
Hi - i'm working on my first pull request. I've been a user of @meredydd project for a while now and thought i'd dip my toes into the world of open-source with some contributions to Skulpt. 

I'm hoping my first contribution will fill in the gaps of missing functions in the math.js file. 

I've been successful with a number of functions and following the guidelines (though it's not always easy 🙃 )

**What I'm struggling with**: `isclose`
`isclose` has exactly 2 arguments and up to 2 kwargs with default values. 
I couldn't find an example of this sort of function in any of the implemented modules. 
The only example I seemed to find was the python 3 print function -  but because of the 0-infinity args it wasn't entirely helpful. This was the same for the suggested approach in the Hacking.md file.

Would be grateful for any suggestions on how to get started with this function...

**Comment by albertjan** [comment]
you assign `$defaults` and `co_varnames` to your function. Use `Sk.builtin.none.none$` for no default. Don't forget to check the number of args in a function with `Sk.builtin.pyCheckArgsLen`. Good luck! 😄 Don't hesitate to ask more questions. 

```
function isclose(a, b, c, d) {
  
}

isclose.$defaults = [Sk.builtin.none.none$ ,Sk.builtin.none.none$, 5 ,6];
isclose.co_varnames = ['a' ,'b' ,'c' ,'d']
```

**Comment by s-cork** [comment]
thanks - that makes sense. There are some examples of that style in re.js

In `isclose` there's a subtle difference in that `c` and `d` are keyword-only arguments. 

if I do `Sk.builtin.pyCheckArgsLen("isclose", arguments.length, 2, 4);` 
then it works, except that c and d are now positional arguments but according to python docs they should be keyword-only arguments...

so if I do ```isclose(1,3,5)``` in python
I should get an error ```isclose() takes at most 2 positional arguments (3 given)```

**Comment by albertjan** [comment]
what I would suggest is writing the function in python and let skulpt compile it, put a `debugger` statement at the bottom of your python code, and see what kwonlyargs look like. I would have to do the same as I don't know of the top of my head. 😄

**Comment by s-cork** [comment]
thanks for the tip @albertjan was super useful - I hadn't realised that the compiled code could provide the template for the function... 

```javascript
_isclose = function(a, b, c, d) {
  // function
};
    _isclose.co_name = new Sk.builtins.str('isclose');
    _isclose.co_varnames = ['a', 'b', 'c', 'd'];
    _isclose.co_argcount = 2;
    _isclose.co_kwonlyargcount = 2;
    _isclose.$kwdefs = [5, 6];

isclose = new Sk.builtin.func(_isclose);
```

**Comment by albertjan** [comment]
nice one @s-cork.
